// Code generated by api-blueprint (Go server); DO NOT EDIT.

package types

type AccountProfile struct {
	UserId   string `json:"user_id" xml:"user_id" form:"user_id"`
	Nickname string `json:"nickname" xml:"nickname" form:"nickname"`
}

type RoomSummary struct {
	RoomId string `json:"room_id" xml:"room_id" form:"room_id"`
	Title  string `json:"title" xml:"title" form:"title"`
}

type LegacyJsonCompatPayload struct {
	Target        any      `json:"target" xml:"target" form:"target"`
	Ids           []any    `json:"ids" xml:"ids" form:"ids"`
	NormalizedIds []string `json:"normalized_ids" xml:"normalized_ids" form:"normalized_ids"`
}
