// Code generated by api-blueprint (Java client); DO NOT EDIT.
package com.example.apiblueprint.static_.routes.static_;

import com.example.apiblueprint.static_.runtime.GenApiChannelBridge;
import com.example.apiblueprint.static_.runtime.GenApiRequest;
import com.example.apiblueprint.static_.runtime.GenApiRequestBodySpec;
import com.example.apiblueprint.static_.runtime.GenApiRequestOptions;
import com.example.apiblueprint.static_.runtime.GenApiRawResponse;
import com.example.apiblueprint.static_.runtime.GenApiResponseEnvelope;
import com.example.apiblueprint.static_.runtime.GenApiResponseSpec;
import com.example.apiblueprint.static_.runtime.GenApiStreamResponse;
import com.example.apiblueprint.static_.runtime.GenApiStreamBridge;
import com.example.apiblueprint.static_.runtime.GenApiTransport;

import com.example.apiblueprint.static_.runtime.GenApiTypes;

import com.example.apiblueprint.static_.runtime.binary.GenApiBinaryBody;

public class GenStaticApi {
    protected final GenApiTransport transport;

    public GenStaticApi(GenApiTransport transport) {
        this.transport = transport;
    }

    public GenStaticTypes.DocJsonResponse docJson(
    ) throws Exception {
        return docJson(
            GenApiRequestOptions.none()
        );
    }

    public GenStaticTypes.DocJsonResponse docJson(
        GenApiRequestOptions options
    ) throws Exception {
        GenApiRequestOptions effectiveOptions = options == null ? GenApiRequestOptions.none() : options;
        GenApiRequest<GenStaticTypes.DocJsonResponse> request = new GenApiRequest<>(
            "static.static.get.docjson",
            "GET",
            "/static/doc.json",
            null,
            new GenApiRequestBodySpec(
                null,
                null,
                null,
                null,
                "none"
            ),
            new GenApiResponseSpec<>(
                GenApiResponseEnvelope.of("NoEnvelope", "none", "none", 0, "ok", new GenApiResponseEnvelope.Fields("code", "message", "data", "error", "ok")),
                GenStaticTypes.DocJsonResponse.class,
                "application/json",
                "json",
                null
            ),
            effectiveOptions.headers(),
            effectiveOptions.timeout()
        );
        return transport.execute(request);
    }

    public GenStaticTypes.DochahaResponse dochaha(
    ) throws Exception {
        return dochaha(
            GenApiRequestOptions.none()
        );
    }

    public GenStaticTypes.DochahaResponse dochaha(
        GenApiRequestOptions options
    ) throws Exception {
        GenApiRequestOptions effectiveOptions = options == null ? GenApiRequestOptions.none() : options;
        GenApiRequest<GenStaticTypes.DochahaResponse> request = new GenApiRequest<>(
            "static.static.get.dochaha",
            "GET",
            "/static/dochaha",
            null,
            new GenApiRequestBodySpec(
                null,
                null,
                null,
                null,
                "none"
            ),
            new GenApiResponseSpec<>(
                GenApiResponseEnvelope.of("NoEnvelope", "none", "none", 0, "ok", new GenApiResponseEnvelope.Fields("code", "message", "data", "error", "ok")),
                GenStaticTypes.DochahaResponse.class,
                "application/json",
                "json",
                null
            ),
            effectiveOptions.headers(),
            effectiveOptions.timeout()
        );
        return transport.execute(request);
    }

}
