// Code generated by api-blueprint (Kotlin server); DO NOT EDIT.
package com.example.apiblueprint.legacy.runtime

import kotlinx.serialization.json.Json

public val ApiJson: Json = Json {
    ignoreUnknownKeys = true
}
