// Code generated by api-blueprint (Wails V3); DO NOT EDIT.

package wailsv3

import (
	runtime "demo/views/_wailsv3/runtime"
	sharedprovider "demo/views/provider"
)

type DemoService struct {
	impl                   RouterInterface
	sessions               *runtime.SocketHub
	abcExecutor            *sharedprovider.RouteExecutor[REQ_Abc_QUERY, any, RSP_Abc]
	testPostExecutor       *sharedprovider.RouteExecutor[any, REQ_TestPost_JSON, RSP_TestPost]
	z1putExecutor          *sharedprovider.RouteExecutor[REQ_Z1put_QUERY, REQ_Z1put_JSON, RSP_Z1put]
	deleteExecutor         *sharedprovider.RouteExecutor[REQ_Delete_QUERY, any, RSP_Delete]
	wsExecutor             *sharedprovider.RouteExecutor[REQ_Ws_QUERY, any, RSP_Ws]
	postDeprecatedExecutor *sharedprovider.RouteExecutor[any, REQ_PostDeprecated_JSON, RSP_PostDeprecated]
	rawExecutor            *sharedprovider.RouteExecutor[any, any, RSP_Raw]
	mapModelExecutor       *sharedprovider.RouteExecutor[any, any, RSP_MapModel]
}

func NewDemoService(impl RouterInterface, dispatcher runtime.EventDispatcher) *DemoService {
	return &DemoService{
		impl:                   impl,
		sessions:               runtime.NewSocketHub(dispatcher),
		abcExecutor:            sharedprovider.NewRouteExecutor[REQ_Abc_QUERY, any, RSP_Abc]("req=Q|auth|handle|rsp=json@GeneralWrapper", impl.Abc),
		testPostExecutor:       sharedprovider.NewRouteExecutor[any, REQ_TestPost_JSON, RSP_TestPost]("req=J|auth|handle|rsp=json@GeneralWrapper", impl.TestPost),
		z1putExecutor:          sharedprovider.NewRouteExecutor[REQ_Z1put_QUERY, REQ_Z1put_JSON, RSP_Z1put]("req=QJ|auth|handle|rsp=json@GeneralWrapper", impl.Z1put),
		deleteExecutor:         sharedprovider.NewRouteExecutor[REQ_Delete_QUERY, any, RSP_Delete]("req=Q|auth|handle|rsp=xml@GeneralWrapper", impl.Delete),
		wsExecutor:             sharedprovider.NewRouteExecutor[REQ_Ws_QUERY, any, RSP_Ws]("req=Q|auth|ws_handle|rsp=json@GeneralWrapper", impl.Ws),
		postDeprecatedExecutor: sharedprovider.NewRouteExecutor[any, REQ_PostDeprecated_JSON, RSP_PostDeprecated]("req=J|auth|handle|rsp=json@GeneralWrapper", impl.PostDeprecated),
		rawExecutor:            sharedprovider.NewRouteExecutor[any, any, RSP_Raw]("req|auth|handle|rsp=json@GeneralWrapper", impl.Raw),
		mapModelExecutor:       sharedprovider.NewRouteExecutor[any, any, RSP_MapModel]("req|auth|handle|rsp=json@GeneralWrapper", impl.MapModel),
	}
}

func (svc *DemoService) Abc(envelope *INVOKE_Abc) (rsp *sharedprovider.RSP_JSON_GeneralWrapper[RSP_Abc], err error) {
	req, reqErr := runtime.EnvelopeToReq[REQ_Abc_QUERY, any](envelope, runtime.ReqEnvelopeOptions{
		BindQuery: true,
		BindJSON:  false,
		BindForm:  false,
	})
	if reqErr != nil {
		err = reqErr
		return
	}
	ctx := sharedprovider.NewWailsContext[REQ_Abc_QUERY, any, RSP_Abc]("DemoService", "Abc", runtime.EnvelopeHeaders(envelope))
	ctx.Req = &sharedprovider.ReqContext[REQ_Abc_QUERY, any, RSP_Abc]{Request: req}
	execErr := svc.abcExecutor.Run(ctx)
	response, invokeErr := ctx.HandleResult()
	if invokeErr == nil {
		invokeErr = execErr
	}

	return sharedprovider.WrapRSP_JSON_GeneralWrapper[RSP_Abc](response, invokeErr), nil
}

func (svc *DemoService) TestPost(envelope *INVOKE_TestPost) (rsp *sharedprovider.RSP_JSON_GeneralWrapper[RSP_TestPost], err error) {
	req, reqErr := runtime.EnvelopeToReq[any, REQ_TestPost_JSON](envelope, runtime.ReqEnvelopeOptions{
		BindQuery: false,
		BindJSON:  true,
		BindForm:  false,
	})
	if reqErr != nil {
		err = reqErr
		return
	}
	ctx := sharedprovider.NewWailsContext[any, REQ_TestPost_JSON, RSP_TestPost]("DemoService", "TestPost", runtime.EnvelopeHeaders(envelope))
	ctx.Req = &sharedprovider.ReqContext[any, REQ_TestPost_JSON, RSP_TestPost]{Request: req}
	execErr := svc.testPostExecutor.Run(ctx)
	response, invokeErr := ctx.HandleResult()
	if invokeErr == nil {
		invokeErr = execErr
	}

	return sharedprovider.WrapRSP_JSON_GeneralWrapper[RSP_TestPost](response, invokeErr), nil
}

func (svc *DemoService) Z1put(envelope *INVOKE_Z1put) (rsp *sharedprovider.RSP_JSON_GeneralWrapper[RSP_Z1put], err error) {
	req, reqErr := runtime.EnvelopeToReq[REQ_Z1put_QUERY, REQ_Z1put_JSON](envelope, runtime.ReqEnvelopeOptions{
		BindQuery: true,
		BindJSON:  true,
		BindForm:  false,
	})
	if reqErr != nil {
		err = reqErr
		return
	}
	ctx := sharedprovider.NewWailsContext[REQ_Z1put_QUERY, REQ_Z1put_JSON, RSP_Z1put]("DemoService", "Z1put", runtime.EnvelopeHeaders(envelope))
	ctx.Req = &sharedprovider.ReqContext[REQ_Z1put_QUERY, REQ_Z1put_JSON, RSP_Z1put]{Request: req}
	execErr := svc.z1putExecutor.Run(ctx)
	response, invokeErr := ctx.HandleResult()
	if invokeErr == nil {
		invokeErr = execErr
	}

	return sharedprovider.WrapRSP_JSON_GeneralWrapper[RSP_Z1put](response, invokeErr), nil
}

func (svc *DemoService) Delete(envelope *INVOKE_Delete) (rsp string, err error) {
	req, reqErr := runtime.EnvelopeToReq[REQ_Delete_QUERY, any](envelope, runtime.ReqEnvelopeOptions{
		BindQuery: true,
		BindJSON:  false,
		BindForm:  false,
	})
	if reqErr != nil {
		err = reqErr
		return
	}
	ctx := sharedprovider.NewWailsContext[REQ_Delete_QUERY, any, RSP_Delete]("DemoService", "Delete", runtime.EnvelopeHeaders(envelope))
	ctx.Req = &sharedprovider.ReqContext[REQ_Delete_QUERY, any, RSP_Delete]{Request: req}
	execErr := svc.deleteExecutor.Run(ctx)
	response, invokeErr := ctx.HandleResult()
	if invokeErr == nil {
		invokeErr = execErr
	}

	if invokeErr != nil {
		return "", invokeErr
	}
	xmlProvider := &sharedprovider.RspProvider[REQ_Delete_QUERY, any, RSP_Delete]{
		Type:    "xml",
		Options: "GeneralWrapper",
	}
	return sharedprovider.MarshalXMLResponse(xmlProvider, response)
}

func (svc *DemoService) ConnectWs(envelope *WS_CONNECT_Ws) (rsp *runtime.SocketSessionDescriptor, err error) {
	req, reqErr := runtime.EnvelopeToReq[REQ_Ws_QUERY, any](envelope, runtime.ReqEnvelopeOptions{
		BindQuery: true,
		BindJSON:  false,
		BindForm:  false,
	})
	if reqErr != nil {
		err = reqErr
		return
	}
	ctx := sharedprovider.NewWailsContext[REQ_Ws_QUERY, any, RSP_Ws]("DemoService", "ConnectWs", runtime.EnvelopeHeaders(envelope))
	ctx.Req = &sharedprovider.ReqContext[REQ_Ws_QUERY, any, RSP_Ws]{Request: req}
	if err := svc.wsExecutor.RunWSPreflight(ctx); err != nil {
		return nil, err
	}

	session := svc.sessions.Open("api.demo.ws.ws")
	ctx.WsHandle = &sharedprovider.WsHandleContext[REQ_Ws_QUERY, any, RSP_Ws]{Conn: session}

	go func() {
		if runErr := svc.wsExecutor.RunWSHandler(ctx); runErr != nil {
			ctx.WsHandle.Error = runErr
			_ = session.Close(1011, runErr.Error())
		}
	}()

	descriptor := session.Descriptor()
	return &descriptor, nil
}

func (svc *DemoService) SendWs(request *WS_SEND_Ws) error {
	session, err := svc.sessions.Get(request.SessionID)
	if err != nil {
		return err
	}
	return session.Push(request.Payload)
}

func (svc *DemoService) CloseWs(request *WS_CLOSE_Ws) error {
	session, err := svc.sessions.Get(request.SessionID)
	if err != nil {
		return err
	}
	code := request.Code
	if code == 0 {
		code = 1000
	}
	return session.Close(code, request.Reason)
}

func (svc *DemoService) PostDeprecated(envelope *INVOKE_PostDeprecated) (rsp *sharedprovider.RSP_JSON_GeneralWrapper[RSP_PostDeprecated], err error) {
	req, reqErr := runtime.EnvelopeToReq[any, REQ_PostDeprecated_JSON](envelope, runtime.ReqEnvelopeOptions{
		BindQuery: false,
		BindJSON:  true,
		BindForm:  false,
	})
	if reqErr != nil {
		err = reqErr
		return
	}
	ctx := sharedprovider.NewWailsContext[any, REQ_PostDeprecated_JSON, RSP_PostDeprecated]("DemoService", "PostDeprecated", runtime.EnvelopeHeaders(envelope))
	ctx.Req = &sharedprovider.ReqContext[any, REQ_PostDeprecated_JSON, RSP_PostDeprecated]{Request: req}
	execErr := svc.postDeprecatedExecutor.Run(ctx)
	response, invokeErr := ctx.HandleResult()
	if invokeErr == nil {
		invokeErr = execErr
	}

	return sharedprovider.WrapRSP_JSON_GeneralWrapper[RSP_PostDeprecated](response, invokeErr), nil
}

func (svc *DemoService) Raw(envelope *INVOKE_Raw) (rsp *sharedprovider.RSP_JSON_GeneralWrapper[RSP_Raw], err error) {
	req, reqErr := runtime.EnvelopeToReq[any, any](envelope, runtime.ReqEnvelopeOptions{
		BindQuery: false,
		BindJSON:  false,
		BindForm:  false,
	})
	if reqErr != nil {
		err = reqErr
		return
	}
	ctx := sharedprovider.NewWailsContext[any, any, RSP_Raw]("DemoService", "Raw", runtime.EnvelopeHeaders(envelope))
	ctx.Req = &sharedprovider.ReqContext[any, any, RSP_Raw]{Request: req}
	execErr := svc.rawExecutor.Run(ctx)
	response, invokeErr := ctx.HandleResult()
	if invokeErr == nil {
		invokeErr = execErr
	}

	return sharedprovider.WrapRSP_JSON_GeneralWrapper[RSP_Raw](response, invokeErr), nil
}

func (svc *DemoService) MapModel(envelope *INVOKE_MapModel) (rsp *sharedprovider.RSP_JSON_GeneralWrapper[RSP_MapModel], err error) {
	req, reqErr := runtime.EnvelopeToReq[any, any](envelope, runtime.ReqEnvelopeOptions{
		BindQuery: false,
		BindJSON:  false,
		BindForm:  false,
	})
	if reqErr != nil {
		err = reqErr
		return
	}
	ctx := sharedprovider.NewWailsContext[any, any, RSP_MapModel]("DemoService", "MapModel", runtime.EnvelopeHeaders(envelope))
	ctx.Req = &sharedprovider.ReqContext[any, any, RSP_MapModel]{Request: req}
	execErr := svc.mapModelExecutor.Run(ctx)
	response, invokeErr := ctx.HandleResult()
	if invokeErr == nil {
		invokeErr = execErr
	}

	return sharedprovider.WrapRSP_JSON_GeneralWrapper[RSP_MapModel](response, invokeErr), nil
}
