// Code generated by api-blueprint (Go server); DO NOT EDIT.

package providers

import (
	"fmt"
	"mime/multipart"
	"net/textproto"
	"strings"
)

const (
	PROV_REQ = "req"
)

type RequestContext[Path, Query, Body any] struct {
	Value *REQ[Path, Query, Body]
	Error error

	binder RequestBinder[Path, Query, Body]
	bound  bool
}

type RequestBinder[Path, Query, Body any] func() (*REQ[Path, Query, Body], error)

func NewRequestContext[Path, Query, Body any](
	value *REQ[Path, Query, Body],
	err error,
) *RequestContext[Path, Query, Body] {
	return &RequestContext[Path, Query, Body]{
		Value: value,
		Error: err,
		bound: true,
	}
}

func NewLazyRequestContext[Path, Query, Body any](
	binder RequestBinder[Path, Query, Body],
) *RequestContext[Path, Query, Body] {
	return &RequestContext[Path, Query, Body]{
		binder: binder,
	}
}

func (ctx *RequestContext[Path, Query, Body]) EnsureBound() (*REQ[Path, Query, Body], error) {
	if ctx == nil {
		return nil, fmt.Errorf("[RequestContext] request context is missing")
	}
	if !ctx.bound {
		ctx.bound = true
		if ctx.binder != nil {
			ctx.Value, ctx.Error = ctx.binder()
		}
		ctx.binder = nil
	}
	if ctx.Error != nil {
		return nil, ctx.Error
	}
	if ctx.Value == nil {
		ctx.Error = fmt.Errorf("[RequestContext] request must be bound by transport adapter")
		return nil, ctx.Error
	}
	return ctx.Value, nil
}

func (ctx *RequestContext[Path, Query, Body]) Bound() (*REQ[Path, Query, Body], bool) {
	if ctx == nil || !ctx.bound || ctx.Error != nil || ctx.Value == nil {
		return nil, false
	}
	return ctx.Value, true
}

type ReqProvider[Path, Query, Body, Response any] struct {
	Data          string
	Route         RouteInfo
	BindPath      bool
	BindQuery     bool
	BindJSON      bool
	BindForm      bool
	BindMultipart bool
	// BindBinary bool is kept as a stable generated marker for binary body support.
	BindBinary bool
}

type MultipartFile struct {
	Filename    string
	ContentType string
	Size        int64
	Header      textproto.MIMEHeader
	File        multipart.File
}

func NewReqProvider[Path, Query, Body, Response any](
	data string,
	handler func(c *Context[Path, Query, Body, Response], req *REQ[Path, Query, Body]) (rsp *Response, err error),
) *ReqProvider[Path, Query, Body, Response] {
	var bindPath, bindQuery, bindJSON, bindForm, bindMultipart, bindBinary bool
	if hasReqToken(data, "path") {
		bindPath = true
	}
	if hasReqToken(data, "query") {
		bindQuery = true
	}
	if hasReqToken(data, "json") {
		bindJSON = true
	}
	if hasReqToken(data, "form") {
		bindForm = true
	}
	if hasReqToken(data, "multipart") {
		bindMultipart = true
	}
	if hasReqToken(data, "binary") {
		bindBinary = true
	}
	return &ReqProvider[Path, Query, Body, Response]{
		Data:          data,
		BindPath:      bindPath,
		BindQuery:     bindQuery,
		BindJSON:      bindJSON,
		BindForm:      bindForm,
		BindMultipart: bindMultipart,
		BindBinary:    bindBinary,
	}
}

func (prov *ReqProvider[Path, Query, Body, Response]) GetName() string {
	return PROV_REQ
}

func (prov *ReqProvider[Path, Query, Body, Response]) Handle(anyCtx ContextInterface) {
	ctx := AdaptContext[Path, Query, Body, Response](anyCtx)
	if _, err := ctx.Request.EnsureBound(); err != nil {
		ctx.Abort(err)
		return
	}
	ctx.Next()
}

func hasReqToken(data string, name string) bool {
	for _, token := range strings.Split(data, ",") {
		if strings.TrimSpace(token) == name {
			return true
		}
	}
	return false
}
