// Code generated by api-blueprint (Swift client); DO NOT EDIT.
import Foundation
import ABClientRuntime

open class GenConflictAPI {
    public let transport: APITransport

    public init(transport: APITransport) {
        self.transport = transport
    }

    public func default_(
        query: ConflictDefaultQuery? = nil,
        options: APIRequestOptions = APIRequestOptions()
    ) async throws -> ConflictModel {
        let jsonBody: ((APICodingConfig) throws -> Data)? = nil
        let formBody: [String: String?]? = nil
        let multipartBody: [String: Any?]? = nil
        let binaryBody: Data? = nil
        return try await transport.request(
            APIRequest<ConflictModel>(
                routeID: "alt.conflict.get.default",
                method: "GET",
                path: "/alt/conflict/default",
                query: query?.toQueryItems() ?? [],
                options: options,
                json: jsonBody,
                form: formBody,
                multipart: multipartBody,
                binary: binaryBody,
                binaryContentType: nil,
                responseMediaType: "application/json",
                responseKind: "json",
                responseEnvelope: APIResponseEnvelope(name: "OkDataErrorEnvelope", kind: "ok_data_error", errorIdentity: "nested", successCode: 0, successMessage: "ok", fields: APIResponseEnvelopeFields(code: "code", message: "message", data: "data", error: "error", ok: "ok")),
                decodeData: { data, envelope, coding in try apiDecodeResponse(ConflictModel.self, from: data, envelope: envelope, routeID: "alt.conflict.get.default", coding: coding) },
                decode: { value in try apiDecodeValue(ConflictModel.self, from: value) }
            )
        )
    }

}
