// Code generated by api-blueprint (Go server HTTP adapter); DO NOT EDIT.

package status

import (
	sharedprovider "example.com/project/golang/server/views/providers"
	shared "example.com/project/golang/server/views/routes/runtime/status"
	httptransport "example.com/project/golang/server/views/transports/http"

	"github.com/gin-gonic/gin"
)

type MountOption = httptransport.MountOption
type ErrorMapperFunc = sharedprovider.ErrorMapperFunc

func WithRouteIDs(routeIDs ...string) MountOption {
	return httptransport.WithRouteIDs(routeIDs...)
}

func WithErrorMapper(mapper ErrorMapperFunc) MountOption {
	return httptransport.WithErrorMapper(mapper)
}

const (
	RouteIDRuntimeCurrentStatus = shared.RouteIDRuntimeCurrentStatus
)

const (
	RoutePathRuntimeCurrentStatus = shared.RoutePathRuntimeCurrentStatus
)

const (
	HTTPRoutePathRuntimeCurrentStatus = "/runtime/status/current"
)

func Mount(router gin.IRouter, impl shared.RouterInterface, options ...MountOption) shared.RouterInterface {
	if httptransport.IsNilRouterImpl(impl) {
		impl = shared.NewRouter()
	}
	mountOptions := httptransport.NewMountOptions(options...)

	if mountOptions.ShouldMountRoute(RouteIDRuntimeCurrentStatus) {
		httptransport.GET(
			HTTPRoutePathRuntimeCurrentStatus,
			sharedprovider.NewRouteExecutor(
				sharedprovider.RouteInfo{
					Root:      "runtime",
					Group:     "status",
					Namespace: "status",
					Service:   "StatusService",
					Operation: "RuntimeCurrentStatus",
					RouteID:   RouteIDRuntimeCurrentStatus,
					Path:      RoutePathRuntimeCurrentStatus,
					Methods:   []string{"GET"},
					Transport: sharedprovider.TransportHTTP,
					Scope:     sharedprovider.ConnectionScope(""),
					HTTP: sharedprovider.HTTPRouteInfo{
						Request: sharedprovider.HTTPRequestInfo{
							PathParams:             []string{},
							BinaryContentEncodings: []string{},
						},
						Response: sharedprovider.HTTPResponseInfo{
							ManualResponse:  false,
							DefaultFilename: "",
						},
					},
				},
				"req|request-signature|handle|rsp=json@CodeMessageDataEnvelope",
				impl.RuntimeCurrentStatus,
				mountOptions.RuntimeOptions()...,
			),
			router,
		)
	}

	return impl
}

func NewRouter(router gin.IRouter, options ...MountOption) *shared.Router {
	impl := shared.NewRouter()
	Mount(router, impl, options...)
	return impl
}

func NewImpl(router gin.IRouter, options ...MountOption) *shared.Router {
	return NewRouter(router, options...)
}
