// Code generated by api-blueprint (Swift client); DO NOT EDIT.
import Foundation
#if canImport(FoundationNetworking)
import FoundationNetworking
#endif

public final class URLSessionAPITransport: APITransport {
    public let config: HTTPAPIConfig

    public init(config: HTTPAPIConfig = HTTPAPIConfig()) {
        self.config = config
    }

    public func request<Response>(_ request: APIRequest<Response>) async throws -> Response {
        let urlRequest = try buildRequest(request)

        if request.responseKind == "byte_stream" {
            let (bytes, response) = try await config.session.bytes(for: urlRequest)
            guard let httpResponse = response as? HTTPURLResponse else {
                throw APIDecodeError.invalidResponse("expected HTTP response")
            }
            try validateStatus(httpResponse, body: Data(), routeID: request.routeID, envelope: request.responseEnvelope)
            let stream = AsyncThrowingStream<Data, Error> { continuation in
                Task {
                    do {
                        for try await byte in bytes {
                            continuation.yield(Data([byte]))
                        }
                        continuation.finish()
                    } catch {
                        continuation.finish(throwing: error)
                    }
                }
            }
            return try request.decode(streamResponse(stream, response: httpResponse, defaultContentType: request.responseMediaType))
        }
        let (data, response) = try await config.session.data(for: urlRequest)

        guard let httpResponse = response as? HTTPURLResponse else {
            throw APIDecodeError.invalidResponse("expected HTTP response")
        }
        try validateStatus(httpResponse, body: data, routeID: request.routeID, envelope: request.responseEnvelope)

        if request.responseKind == "bytes" || request.responseKind == "file" {
            return try request.decode(rawResponse(data, response: httpResponse, defaultContentType: request.responseMediaType))
        }
        if request.responseKind == "byte_stream" {
            let stream = AsyncThrowingStream<Data, Error> { continuation in
                continuation.yield(data)
                continuation.finish()
            }
            return try request.decode(streamResponse(stream, response: httpResponse, defaultContentType: request.responseMediaType))
        }
        if request.responseKind == "binary_schema" {
            return try request.decode(data)
        }
        if !isJSONResponse(httpResponse) {
            return try request.decode(String(data: data, encoding: .utf8) ?? "")
        }
        let json = data.isEmpty ? nil : try JSONSerialization.jsonObject(with: data, options: [])
        let payload = try apiUnwrapResponseEnvelope(json, envelope: request.responseEnvelope, routeID: request.routeID)
        return try request.decode(payload)
    }

    public func openStream<Recv, Close>(_ options: APIStreamConnectOptions<Recv, Close>) -> APIStreamBridge<Recv, Close> {
        // SSE is a protocol bridge only; apps can wrap APITransport for custom lifecycle/backpressure policy.
        return apiHTTPEmptyStreamBridge(routeID: options.routeID)
    }

    public func openChannel<Recv, Send, Close>(_ options: APIChannelConnectOptions<Recv, Send, Close>) -> APIChannelBridge<Recv, Send, Close> {
        let url = buildWebSocketURL(path: options.path, query: options.query)
        let socket = config.session.webSocketTask(with: url, protocols: options.protocols)
        return apiHTTPWebSocketBridge(
            routeID: options.routeID,
            socket: socket,
            decodeMessage: options.decodeMessage,
            encodeMessage: options.encodeMessage,
            decodeClose: options.decodeClose
        )
    }

    private func buildRequest<Response>(_ request: APIRequest<Response>) throws -> URLRequest {
        let url = buildURL(path: request.path, query: request.query)
        var urlRequest = URLRequest(url: url)
        urlRequest.httpMethod = request.method
        for (name, value) in config.defaultHeaders {
            urlRequest.setValue(value, forHTTPHeaderField: name)
        }
        for (name, value) in request.options.headers {
            urlRequest.setValue(value, forHTTPHeaderField: name)
        }
        if let timeout = request.options.timeout ?? config.timeout {
            urlRequest.timeoutInterval = timeout
        }
        if let json = request.json {
            urlRequest.setValue("application/json", forHTTPHeaderField: "Content-Type")
            urlRequest.httpBody = try JSONSerialization.data(withJSONObject: json, options: [])
        } else if let form = request.form {
            urlRequest.setValue("application/x-www-form-urlencoded", forHTTPHeaderField: "Content-Type")
            urlRequest.httpBody = encodeForm(form).data(using: .utf8)
        } else if let multipart = request.multipart {
            let boundary = "api-blueprint-\(UUID().uuidString)"
            urlRequest.setValue("multipart/form-data; boundary=\(boundary)", forHTTPHeaderField: "Content-Type")
            urlRequest.httpBody = encodeMultipart(multipart, boundary: boundary)
        } else if let binary = request.binary {
            urlRequest.setValue(request.binaryContentType ?? "application/octet-stream", forHTTPHeaderField: "Content-Type")
            urlRequest.httpBody = binary
        }
        if urlRequest.value(forHTTPHeaderField: "Accept") == nil {
            urlRequest.setValue("application/json", forHTTPHeaderField: "Accept")
        }
        return urlRequest
    }

    private func buildURL(path: String, query: [URLQueryItem]) -> URL {
        let normalizedPath = path.hasPrefix("/") ? path : "/\(path)"
        let base = config.baseURL ?? URL(string: "http://localhost")!
        let raw = base.absoluteString.trimmingCharacters(in: CharacterSet(charactersIn: "/")) + normalizedPath
        var components = URLComponents(string: raw)!
        let existing = components.queryItems ?? []
        components.queryItems = (existing + query).filter { $0.value != nil }
        return components.url!
    }

    private func buildWebSocketURL(path: String, query: [URLQueryItem]) -> URL {
        var components = URLComponents(url: buildURL(path: path, query: query), resolvingAgainstBaseURL: false)!
        if components.scheme == "http" {
            components.scheme = "ws"
        } else if components.scheme == "https" {
            components.scheme = "wss"
        }
        return components.url!
    }

    private func validateStatus(_ response: HTTPURLResponse, body: Data, routeID: String, envelope: APIResponseEnvelope) throws {
        if response.statusCode < 400 {
            return
        }
        let text = String(data: body, encoding: .utf8) ?? ""
        if let json = try? JSONSerialization.jsonObject(with: body, options: []) {
            throw APIError(payload: apiErrorPayload(from: json, routeID: routeID), routeID: routeID, raw: text)
        }
        throw APIHTTPError(statusCode: response.statusCode, body: text)
    }

    private func isJSONResponse(_ response: HTTPURLResponse) -> Bool {
        let contentType = response.value(forHTTPHeaderField: "Content-Type")?.split(separator: ";").first?.lowercased() ?? ""
        return contentType == "application/json" || contentType.hasSuffix("+json")
    }

    private func rawResponse(_ data: Data, response: HTTPURLResponse, defaultContentType: String) -> APIRawResponse {
        APIRawResponse(
            body: data,
            headers: headers(response),
            statusCode: response.statusCode,
            contentType: response.value(forHTTPHeaderField: "Content-Type") ?? defaultContentType,
            contentDisposition: response.value(forHTTPHeaderField: "Content-Disposition") ?? "",
            filename: filename(response)
        )
    }

    private func streamResponse(_ stream: AsyncThrowingStream<Data, Error>, response: HTTPURLResponse, defaultContentType: String) -> APIStreamResponse {
        APIStreamResponse(
            body: stream,
            headers: headers(response),
            statusCode: response.statusCode,
            contentType: response.value(forHTTPHeaderField: "Content-Type") ?? defaultContentType,
            contentDisposition: response.value(forHTTPHeaderField: "Content-Disposition") ?? "",
            filename: filename(response)
        )
    }

    private func headers(_ response: HTTPURLResponse) -> [String: String] {
        var result: [String: String] = [:]
        for (name, value) in response.allHeaderFields {
            result[String(describing: name)] = String(describing: value)
        }
        return result
    }

    private func filename(_ response: HTTPURLResponse) -> String? {
        guard let disposition = response.value(forHTTPHeaderField: "Content-Disposition") else {
            return nil
        }
        for part in disposition.split(separator: ";") {
            let trimmed = part.trimmingCharacters(in: .whitespaces)
            if trimmed.lowercased().hasPrefix("filename=") {
                return String(trimmed.dropFirst("filename=".count)).trimmingCharacters(in: CharacterSet(charactersIn: "\""))
            }
        }
        return nil
    }

    private func encodeForm(_ form: [String: String?]) -> String {
        form.compactMap { name, value in
            guard let value else {
                return nil
            }
            return "\(escape(name))=\(escape(value))"
        }.joined(separator: "&")
    }

    private func escape(_ value: String) -> String {
        value.addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed) ?? value
    }

    private func encodeMultipart(_ fields: [String: Any?], boundary: String) -> Data {
        var data = Data()
        for (name, value) in fields {
            guard let value else {
                continue
            }
            data.append("--\(boundary)\r\n".data(using: .utf8)!)
            if let file = value as? APIFilePart {
                data.append("Content-Disposition: form-data; name=\"\(name)\"; filename=\"\(file.filename)\"\r\n".data(using: .utf8)!)
                data.append("Content-Type: \(file.contentType)\r\n\r\n".data(using: .utf8)!)
                data.append(file.data)
                data.append("\r\n".data(using: .utf8)!)
            } else {
                data.append("Content-Disposition: form-data; name=\"\(name)\"\r\n\r\n".data(using: .utf8)!)
                data.append(String(describing: value).data(using: .utf8)!)
                data.append("\r\n".data(using: .utf8)!)
            }
        }
        data.append("--\(boundary)--\r\n".data(using: .utf8)!)
        return data
    }
}
