// Code generated by api-blueprint (Go server); DO NOT EDIT.

package media

import (
	providers "example.com/project/golang/server/views/providers"
	types "example.com/project/golang/server/views/routes/api/_gen_types"
)

type REQ_MediaPreview_FORM = types.MediaPreviewRequest

type REQ_MediaPreview = providers.REQ[
	any,
	any,
	REQ_MediaPreview_FORM,
]

type RSP_MediaPreview = providers.RawResponse

type CTX_MediaPreview = providers.Context[
	any,
	any,
	REQ_MediaPreview_FORM,
	providers.RawResponse,
]

type REQ_MediaFrame = providers.REQ[
	any,
	any,
	any,
]

type RSP_MediaFrame = providers.RawResponse

type CTX_MediaFrame = providers.Context[
	any,
	any,
	any,
	providers.RawResponse,
]

type REQ_MediaDownload = providers.REQ[
	any,
	any,
	any,
]

type RSP_MediaDownload = providers.RawResponse

type CTX_MediaDownload = providers.Context[
	any,
	any,
	any,
	providers.RawResponse,
]

type REQ_MediaDownloadDynamic = providers.REQ[
	any,
	any,
	any,
]

type RSP_MediaDownloadDynamic = providers.RawResponse

type CTX_MediaDownloadDynamic = providers.Context[
	any,
	any,
	any,
	providers.RawResponse,
]

type REQ_MediaDownloadFilenameEdge = providers.REQ[
	any,
	any,
	any,
]

type RSP_MediaDownloadFilenameEdge = providers.RawResponse

type CTX_MediaDownloadFilenameEdge = providers.Context[
	any,
	any,
	any,
	providers.RawResponse,
]

type REQ_MediaErrorFrame_QUERY struct {
	Mode string `json:"mode" xml:"mode" form:"mode" uri:"mode"`
}

type REQ_MediaErrorFrame = providers.REQ[
	any,
	REQ_MediaErrorFrame_QUERY,
	any,
]

type RSP_MediaErrorFrame = providers.RawResponse

type CTX_MediaErrorFrame = providers.Context[
	any,
	REQ_MediaErrorFrame_QUERY,
	any,
	providers.RawResponse,
]

type REQ_MediaMjpeg = providers.REQ[
	any,
	any,
	any,
]

type RSP_MediaMjpeg = providers.RawResponse

type CTX_MediaMjpeg = providers.Context[
	any,
	any,
	any,
	providers.RawResponse,
]
