// Code generated by api-blueprint (Golang); DO NOT EDIT.

package api

import (
	"demo/views/api/demo"
	"demo/views/api/hello"

	"github.com/gin-gonic/gin"
)

type Blueprint struct {
	Router      *Router
	DemoRouter  *demo.Router
	HelloRouter *hello.Router
}

func NewBlueprint(eng *gin.Engine) *Blueprint {
	return &Blueprint{
		Router:      NewImpl(eng),
		DemoRouter:  demo.NewImpl(eng),
		HelloRouter: hello.NewImpl(eng),
	}
}
