// Code generated by api-blueprint (Kotlin server); DO NOT EDIT.
package com.example.apiblueprint.api.routes.api.demo

import com.example.apiblueprint.api.runtime.*

public interface GenDemoService {

    public suspend fun abc(
        query: DemoAbcQuery
    ): ApiDemoA

    public suspend fun testPost(
        json: DemoTestPostJson
    ): DemoTestPostResponse

    public suspend fun formSubmit(
        form: DemoFormSubmitForm
    ): DemoFormSubmitResponse

    public suspend fun requestOptions(
        query: DemoRequestOptionsQuery
    ): RequestOptionsResponse

    public suspend fun pathEcho(
        path: PathEchoPath
    ): PathEchoResponse

    public suspend fun emptyResponse(
    ): DemoEmptyResponseResponse

    public suspend fun putDemo(
        query: DemoPutDemoQuery,
        json: DemoPutDemoJson
    ): DemoPutDemoResponse

    public suspend fun delete(
        query: DemoDeleteQuery
    ): String

    public suspend fun sweepEvents(
        openData: SweepOpen,
        stream: ApiServerStream<SweepStreamMessage, ConnectionClose>
    ): Unit

    public suspend fun assistantSession(
        openData: AssistantOpen,
        channel: ApiServerChannel<AssistantClientMessage, AssistantServerMessage, ConnectionClose>
    ): Unit

    public suspend fun postDeprecated(
        json: DemoPostDeprecatedJson
    ): DemoPostDeprecatedResponse

    public suspend fun raw(
    ): DemoRawResponse

    public suspend fun mapModel(
    ): DemoMapModelResponse

    public suspend fun errorDemo(
        query: DemoErrorDemoQuery
    ): DemoErrorDemoResponse

}
