// Code generated by api-blueprint; DO NOT EDIT.
package com.example.apiblueprint.api.routes.api.binary;

import com.example.apiblueprint.api.runtime.ApiChannelBridge;
import com.example.apiblueprint.api.runtime.ApiRequest;
import com.example.apiblueprint.api.runtime.ApiSocketBridge;
import com.example.apiblueprint.api.runtime.ApiStreamBridge;
import com.example.apiblueprint.api.runtime.ApiTransport;
import com.example.apiblueprint.api.runtime.GenModels;
import com.example.apiblueprint.api.runtime.binary.ApiBinaryBody;
import java.util.Map;

public class GenBinaryApi {
    protected final ApiTransport transport;

    public GenBinaryApi(ApiTransport transport) {
        this.transport = transport;
    }

    public GenBinaryApiModels.RspPacket packet(
        GenBinaryApiModels.ReqPacketQuery query,
        ApiBinaryBody binaryBody
    ) throws Exception {
        ApiRequest<GenBinaryApiModels.RspPacket> request = new ApiRequest<>(
            "POST",
            "/api/binary/packet",
            query,
            null,
            null,
            binaryBody,
            "GeneralWrapper",
            GenBinaryApiModels.RspPacket.class,
            "application/json",
            Map.of()
        );
        return transport.execute(request);
    }

}
