/* eslint-disable */
/* istanbul ignore file */
// Code generated by api-blueprint (TypeScript client); DO NOT EDIT.

import type * as Types from "./types";
import type * as Shared from "../../runtime/types";
import { ApiChannelBridge, ApiClientConfig, ApiRequestOptions, ApiStreamBridge, BaseClient } from "../../runtime/client";

export class StaticClient extends BaseClient {
  constructor(config: ApiClientConfig = {}) {
    super(config);
  }

  /**
   * Route: /static/doc.json

   * Tags: static
   */

  async docJson(
    request: {

    } = {},
    options?: ApiRequestOptions,
  ): Promise<Types.DocJsonResponse> {
    return this.request<Types.DocJsonResponse>({
      routeId: "static.static.get.docjson",
      method: "GET",
      path: "/static/doc.json",
      service: "StaticService",
      operation: "DocJson",
      namespace: "static",
      headers: options?.headers,
      init: options?.init,
      responseType: "json",
      responseEnvelope: {"name": "NoEnvelope", "kind": "none", "error_identity": "none", "success_code": 0, "success_message": "ok", "fields": {}},
      timeoutMs: options?.timeoutMs,
    });
  }

  /**
   * Route: /static/dochaha

   * Tags: static
   */

  async dochaha(
    request: {

    } = {},
    options?: ApiRequestOptions,
  ): Promise<Types.DochahaResponse> {
    return this.request<Types.DochahaResponse>({
      routeId: "static.static.get.dochaha",
      method: "GET",
      path: "/static/dochaha",
      service: "StaticService",
      operation: "Dochaha",
      namespace: "static",
      headers: options?.headers,
      init: options?.init,
      responseType: "json",
      responseEnvelope: {"name": "NoEnvelope", "kind": "none", "error_identity": "none", "success_code": 0, "success_message": "ok", "fields": {}},
      timeoutMs: options?.timeoutMs,
    });
  }

}
