.DEFAULT_GOAL := help

RELEASE_TAG ?=
DIST_DIR ?= dist
BINARY_BENCH_TARGET ?= go
BINARY_BENCH_COUNT ?= 10000
BINARY_BENCH_COMPARE_HEAD ?= 0
EXAMPLE_CONFORMANCE_SERVER ?= go
EXAMPLE_CONFORMANCE_SERVERS ?= $(EXAMPLE_CONFORMANCE_SERVER)
EXAMPLE_CONFORMANCE_CLIENTS ?= go,typescript,kotlin,flutter
EXAMPLE_CONFORMANCE_SCENARIOS ?=
EXAMPLE_CONFORMANCE_KEEP_WORKSPACE ?= 0
EXAMPLE_CONFORMANCE_SCENARIO_ARG = $(if $(strip $(EXAMPLE_CONFORMANCE_SCENARIOS)),--scenario "$(EXAMPLE_CONFORMANCE_SCENARIOS)")
EXAMPLE_CONFORMANCE_KEEP_ARG = $(if $(filter 1,$(EXAMPLE_CONFORMANCE_KEEP_WORKSPACE)),--keep-workspace)
EXAMPLE_CONFORMANCE_MATRIX_ARGS = --servers "$(EXAMPLE_CONFORMANCE_SERVERS)" --clients "$(EXAMPLE_CONFORMANCE_CLIENTS)" $(EXAMPLE_CONFORMANCE_SCENARIO_ARG)

include make/core.mk
include make/examples.mk
include make/wails.mk
include make/release.mk
