// Code generated by api-blueprint (Java server); DO NOT EDIT.
package com.example.apiblueprint.api.routes.api.hello;

import com.example.apiblueprint.api.runtime.ApiTypes;

import com.example.apiblueprint.api.runtime.binary.ApiBinaryBody;

public class HelloServiceStub implements HelloService {

    @Override
    public HelloTypes.AbcResponse abc(
        HelloTypes.AbcQuery query
    ) {
        throw new UnsupportedOperationException("abc");
    }

    @Override
    public HelloTypes.MapEnumResponse mapEnum(
    ) {
        throw new UnsupportedOperationException("mapEnum");
    }

    @Override
    public HelloTypes.ListEnumResponse listEnum(
    ) {
        throw new UnsupportedOperationException("listEnum");
    }

    @Override
    public HelloTypes.StringResponse string(
    ) {
        throw new UnsupportedOperationException("string");
    }

    @Override
    public HelloTypes.Uint64Response uint64(
    ) {
        throw new UnsupportedOperationException("uint64");
    }

    @Override
    public HelloTypes.StringEmunResponse stringEmun(
    ) {
        throw new UnsupportedOperationException("stringEmun");
    }

    @Override
    public Object helloWay(
        HelloTypes.HelloWayQuery query
    ) {
        throw new UnsupportedOperationException("helloWay");
    }

}
