/* eslint-disable */
/* istanbul ignore file */
// Code generated by api-blueprint (TypeScript); DO NOT EDIT.

import type { ApiClientConfig } from "./client";
import { HelloClient } from "../hello/client";


export interface GeneratedClients {
  helloClient: HelloClient;
}

export function createClients(config: ApiClientConfig = {}): GeneratedClients {
  return {
    helloClient: new HelloClient(config),
  };
}
