// Code generated by api-blueprint (Java server); DO NOT EDIT.
package com.example.apiblueprint.api.spring;

import com.example.apiblueprint.api.annotations.ApiBlueprintOperation;
import java.lang.annotation.Annotation;
import java.lang.reflect.Method;
import java.lang.reflect.Parameter;
import java.util.ArrayList;
import java.util.Collection;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Set;
import org.springframework.core.annotation.AnnotatedElementUtils;
import org.springframework.util.AntPathMatcher;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.method.HandlerMethod;
import org.springframework.web.servlet.mvc.method.RequestMappingInfo;
import org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping;

public final class GenSpringMvcContractAssertions {
    private static final ContractMode DEFAULT_MODE = ContractMode.PUBLIC;
    private static final AntPathMatcher PATH_MATCHER = new AntPathMatcher();
    private static final List<String> PUBLIC_PATHS = List.of(
        "/api/**",
        "/legacy/**",
        "/runtime/**",
        "/static/**"
    );
    private static final List<String> EXCLUDE_SERVER_PATHS = List.of(
        "/internal/**"
    );
    private static final List<RouteSpec> ROUTES = List.of(
        new RouteSpec(
            "api.api.channel.ws",
            Set.of(),
            "/api/ws",
            "com.example.apiblueprint.api.annotations.api.GenHelloChannel",
            List.of(),
            List.of(),
            "",
            List.of(),
            "generated",
            "generated"
        ),
        new RouteSpec(
            "api.binary.post.packet",
            Set.of("POST"),
            "/api/binary/packet",
            "com.example.apiblueprint.api.annotations.api.binary.GenPacket",
            List.of(),
            List.of("com.example.apiblueprint.api.types.api.binary.GenBinaryTypes.PacketQuery", "com.example.apiblueprint.api.types.api.binary.GenBinaryTypes.DemoPacket"),
            "com.example.apiblueprint.api.types.api.binary.GenBinaryTypes.PacketResponse",
            List.of(),
            "generated",
            "generated"
        ),
        new RouteSpec(
            "api.binary.post.auditpacket",
            Set.of("POST"),
            "/api/binary/audit-packet",
            "com.example.apiblueprint.api.annotations.api.binary.GenAuditPacket",
            List.of(),
            List.of("com.example.apiblueprint.api.types.api.binary.GenBinaryTypes.AuditPacketQuery", "com.example.apiblueprint.api.types.api.binary.GenBinaryTypes.AuditPacket"),
            "com.example.apiblueprint.api.types.api.binary.GenBinaryTypes.AuditPacketResponse",
            List.of(),
            "generated",
            "generated"
        ),
        new RouteSpec(
            "api.binary.post.widepacket",
            Set.of("POST"),
            "/api/binary/wide-packet",
            "com.example.apiblueprint.api.annotations.api.binary.GenWidePacket",
            List.of(),
            List.of("com.example.apiblueprint.api.types.api.binary.GenBinaryTypes.WidePacketQuery", "com.example.apiblueprint.api.types.api.binary.GenBinaryTypes.WidePacket"),
            "com.example.apiblueprint.api.types.api.binary.GenBinaryTypes.WidePacketResponse",
            List.of(),
            "generated",
            "generated"
        ),
        new RouteSpec(
            "api.binary.get.auditpacketresponse",
            Set.of("GET"),
            "/api/binary/audit-packet-response",
            "com.example.apiblueprint.api.annotations.api.binary.GenAuditPacketResponse",
            List.of(),
            List.of(),
            "com.example.apiblueprint.api.types.api.binary.GenBinaryTypes.AuditPacket",
            List.of(),
            "generated",
            "generated"
        ),
        new RouteSpec(
            "api.conflict.get.default",
            Set.of("GET"),
            "/api/conflict/default",
            "com.example.apiblueprint.api.annotations.api.conflict.GenDefault",
            List.of(),
            List.of("com.example.apiblueprint.api.types.api.conflict.GenConflictTypes.DefaultQuery"),
            "com.example.apiblueprint.api.runtime.GenApiTypes.BlueprintsApiConflictConflictModel",
            List.of(),
            "generated",
            "generated"
        ),
        new RouteSpec(
            "api.demo.get.abc",
            Set.of("GET"),
            "/api/demo/abc",
            "com.example.apiblueprint.api.annotations.api.demo.GenDemoAbc",
            List.of("com.example.apiblueprint.security.SignatureRequired"),
            List.of("com.example.apiblueprint.api.types.api.demo.GenDemoTypes.AbcQuery"),
            "com.example.apiblueprint.api.runtime.GenApiTypes.ApiDemoA",
            List.of(),
            "generated",
            "generated"
        ),
        new RouteSpec(
            "api.demo.post.testpost",
            Set.of("POST"),
            "/api/demo/test_post",
            "com.example.apiblueprint.api.annotations.api.demo.GenTestPost",
            List.of(),
            List.of("com.example.apiblueprint.api.types.api.demo.GenDemoTypes.TestPostJSON"),
            "com.example.apiblueprint.api.types.api.demo.GenDemoTypes.TestPostResponse",
            List.of("req1"),
            "generated",
            "generated"
        ),
        new RouteSpec(
            "api.demo.post.formsubmit",
            Set.of("POST"),
            "/api/demo/form-submit",
            "com.example.apiblueprint.api.annotations.api.demo.GenFormSubmit",
            List.of(),
            List.of("com.example.apiblueprint.api.types.api.demo.GenDemoTypes.FormSubmitForm"),
            "com.example.apiblueprint.api.types.api.demo.GenDemoTypes.FormSubmitResponse",
            List.of("title"),
            "generated",
            "generated"
        ),
        new RouteSpec(
            "api.demo.get.requestoptions",
            Set.of("GET"),
            "/api/demo/request-options",
            "com.example.apiblueprint.api.annotations.api.demo.GenRequestOptions",
            List.of(),
            List.of("com.example.apiblueprint.api.types.api.demo.GenDemoTypes.RequestOptionsQuery"),
            "com.example.apiblueprint.api.runtime.GenApiTypes.RequestOptionsResponse",
            List.of(),
            "generated",
            "generated"
        ),
        new RouteSpec(
            "api.demo.put.z1put",
            Set.of("PUT"),
            "/api/demo/1put",
            "com.example.apiblueprint.api.annotations.api.demo.GenPutDemo",
            List.of(),
            List.of("com.example.apiblueprint.api.types.api.demo.GenDemoTypes.PutDemoQuery", "com.example.apiblueprint.api.types.api.demo.GenDemoTypes.PutDemoJSON"),
            "com.example.apiblueprint.api.types.api.demo.GenDemoTypes.PutDemoResponse",
            List.of("req1"),
            "generated",
            "generated"
        ),
        new RouteSpec(
            "api.demo.delete.delete",
            Set.of("DELETE"),
            "/api/demo/delete$",
            "com.example.apiblueprint.api.annotations.api.demo.GenDelete",
            List.of(),
            List.of("com.example.apiblueprint.api.types.api.demo.GenDemoTypes.DeleteQuery"),
            "com.example.apiblueprint.api.types.api.demo.GenDemoTypes.DeleteResponse",
            List.of(),
            "generated",
            "generated"
        ),
        new RouteSpec(
            "api.demo.stream.sweepevents",
            Set.of(),
            "/api/demo/sweep-events",
            "com.example.apiblueprint.api.annotations.api.demo.GenSweepEvents",
            List.of(),
            List.of("com.example.apiblueprint.api.runtime.GenApiTypes.SweepOpen"),
            "",
            List.of(),
            "generated",
            "generated"
        ),
        new RouteSpec(
            "api.demo.channel.assistantsession",
            Set.of(),
            "/api/demo/assistant-session",
            "com.example.apiblueprint.api.annotations.api.demo.GenAssistantSession",
            List.of(),
            List.of("com.example.apiblueprint.api.runtime.GenApiTypes.AssistantOpen"),
            "",
            List.of(),
            "generated",
            "generated"
        ),
        new RouteSpec(
            "api.demo.post.postdeprecated",
            Set.of("POST"),
            "/api/demo/post_deprecated",
            "com.example.apiblueprint.api.annotations.api.demo.GenPostDeprecated",
            List.of(),
            List.of("com.example.apiblueprint.api.types.api.demo.GenDemoTypes.PostDeprecatedJSON"),
            "com.example.apiblueprint.api.types.api.demo.GenDemoTypes.PostDeprecatedResponse",
            List.of("req1"),
            "generated",
            "generated"
        ),
        new RouteSpec(
            "api.demo.post.raw",
            Set.of("POST"),
            "/api/demo/raw",
            "com.example.apiblueprint.api.annotations.api.demo.GenRaw",
            List.of(),
            List.of(),
            "com.example.apiblueprint.api.types.api.demo.GenDemoTypes.RawResponse",
            List.of(),
            "generated",
            "generated"
        ),
        new RouteSpec(
            "api.demo.post.mapmodel",
            Set.of("POST"),
            "/api/demo/map_model",
            "com.example.apiblueprint.api.annotations.api.demo.GenMapModel",
            List.of(),
            List.of(),
            "com.example.apiblueprint.api.types.api.demo.GenDemoTypes.MapModelResponse",
            List.of(),
            "generated",
            "generated"
        ),
        new RouteSpec(
            "api.demo.get.errordemo",
            Set.of("GET"),
            "/api/demo/error-demo",
            "com.example.apiblueprint.api.annotations.api.demo.GenErrorDemo",
            List.of(),
            List.of("com.example.apiblueprint.api.types.api.demo.GenDemoTypes.ErrorDemoQuery"),
            "com.example.apiblueprint.api.types.api.demo.GenDemoTypes.ErrorDemoResponse",
            List.of(),
            "generated",
            "generated"
        ),
        new RouteSpec(
            "api.media.post.preview",
            Set.of("POST"),
            "/api/media/preview",
            "com.example.apiblueprint.api.annotations.api.media.GenMediaPreview",
            List.of(),
            List.of("com.example.apiblueprint.api.runtime.GenApiTypes.MediaPreviewRequest"),
            "com.example.apiblueprint.api.runtime.GenApiRawResponse",
            List.of("image"),
            "generated",
            "generated"
        ),
        new RouteSpec(
            "api.media.get.frame",
            Set.of("GET"),
            "/api/media/frame",
            "com.example.apiblueprint.api.annotations.api.media.GenMediaFrame",
            List.of(),
            List.of(),
            "com.example.apiblueprint.api.runtime.GenApiRawResponse",
            List.of(),
            "generated",
            "generated"
        ),
        new RouteSpec(
            "api.media.get.download",
            Set.of("GET"),
            "/api/media/download",
            "com.example.apiblueprint.api.annotations.api.media.GenMediaDownload",
            List.of(),
            List.of(),
            "com.example.apiblueprint.api.runtime.GenApiRawResponse",
            List.of(),
            "generated",
            "generated"
        ),
        new RouteSpec(
            "api.media.get.downloaddynamic",
            Set.of("GET"),
            "/api/media/download-dynamic",
            "com.example.apiblueprint.api.annotations.api.media.GenMediaDownloadDynamic",
            List.of(),
            List.of(),
            "com.example.apiblueprint.api.runtime.GenApiRawResponse",
            List.of(),
            "generated",
            "generated"
        ),
        new RouteSpec(
            "api.media.get.downloadfilenameedge",
            Set.of("GET"),
            "/api/media/download-filename-edge",
            "com.example.apiblueprint.api.annotations.api.media.GenMediaDownloadFilenameEdge",
            List.of(),
            List.of(),
            "com.example.apiblueprint.api.runtime.GenApiRawResponse",
            List.of(),
            "generated",
            "generated"
        ),
        new RouteSpec(
            "api.media.get.errorframe",
            Set.of("GET"),
            "/api/media/error-frame",
            "com.example.apiblueprint.api.annotations.api.media.GenMediaErrorFrame",
            List.of(),
            List.of("com.example.apiblueprint.api.types.api.media.GenMediaTypes.MediaErrorFrameQuery"),
            "com.example.apiblueprint.api.runtime.GenApiRawResponse",
            List.of(),
            "generated",
            "generated"
        ),
        new RouteSpec(
            "api.media.get.mjpeg",
            Set.of("GET"),
            "/api/media/mjpeg",
            "com.example.apiblueprint.api.annotations.api.media.GenMediaMjpeg",
            List.of(),
            List.of(),
            "com.example.apiblueprint.api.runtime.GenApiStreamResponse",
            List.of(),
            "generated",
            "generated"
        ),
        new RouteSpec(
            "api.hello.get.abc",
            Set.of("GET"),
            "/api/hello/abc",
            "com.example.apiblueprint.api.annotations.api.hello.GenAbc",
            List.of(),
            List.of("com.example.apiblueprint.api.types.api.hello.GenHelloTypes.AbcQuery"),
            "com.example.apiblueprint.api.types.api.hello.GenHelloTypes.AbcResponse",
            List.of("type"),
            "generated",
            "generated"
        ),
        new RouteSpec(
            "api.hello.get.mapenum",
            Set.of("GET"),
            "/api/hello/map-enum",
            "com.example.apiblueprint.api.annotations.api.hello.GenMapEnum",
            List.of(),
            List.of(),
            "com.example.apiblueprint.api.types.api.hello.GenHelloTypes.MapEnumResponse",
            List.of(),
            "generated",
            "generated"
        ),
        new RouteSpec(
            "api.hello.get.listenum",
            Set.of("GET"),
            "/api/hello/list-enum",
            "com.example.apiblueprint.api.annotations.api.hello.GenListEnum",
            List.of(),
            List.of(),
            "com.example.apiblueprint.api.types.api.hello.GenHelloTypes.ListEnumResponse",
            List.of(),
            "generated",
            "generated"
        ),
        new RouteSpec(
            "api.hello.get.string",
            Set.of("GET"),
            "/api/hello/string",
            "com.example.apiblueprint.api.annotations.api.hello.GenString",
            List.of(),
            List.of(),
            "com.example.apiblueprint.api.types.api.hello.GenHelloTypes.StringResponse",
            List.of(),
            "generated",
            "generated"
        ),
        new RouteSpec(
            "api.hello.get.uint64",
            Set.of("GET"),
            "/api/hello/uint64",
            "com.example.apiblueprint.api.annotations.api.hello.GenUint64",
            List.of(),
            List.of(),
            "com.example.apiblueprint.api.types.api.hello.GenHelloTypes.Uint64Response",
            List.of(),
            "generated",
            "generated"
        ),
        new RouteSpec(
            "api.hello.get.stringemun",
            Set.of("GET"),
            "/api/hello/string-emun",
            "com.example.apiblueprint.api.annotations.api.hello.GenStringEmun",
            List.of(),
            List.of(),
            "com.example.apiblueprint.api.types.api.hello.GenHelloTypes.StringEmunResponse",
            List.of(),
            "generated",
            "generated"
        ),
        new RouteSpec(
            "api.hello.get.helloway",
            Set.of("GET"),
            "/api/hello/hello-way",
            "com.example.apiblueprint.api.annotations.api.hello.GenHelloWay",
            List.of(),
            List.of("com.example.apiblueprint.api.types.api.hello.GenHelloTypes.HelloWayQuery"),
            "",
            List.of(),
            "generated",
            "generated"
        )
    );

    private GenSpringMvcContractAssertions() {
    }

    public static ContractReport assertMatches(RequestMappingHandlerMapping mappings) {
        return assertMatches(mappings, DEFAULT_MODE);
    }

    public static ContractReport assertMatches(RequestMappingHandlerMapping mappings, ContractMode mode) {
        ContractMode effectiveMode = mode == null ? DEFAULT_MODE : mode;
        ContractReport report = inspect(mappings, effectiveMode);
        if ((effectiveMode == ContractMode.PUBLIC || effectiveMode == ContractMode.STRICT) && report.hasErrors()) {
            throw new AssertionError(report.toString());
        }
        return report;
    }

    public static ContractReport inspect(RequestMappingHandlerMapping mappings) {
        return inspect(mappings, DEFAULT_MODE);
    }

    public static ContractReport inspect(RequestMappingHandlerMapping mappings, ContractMode mode) {
        ContractMode effectiveMode = mode == null ? DEFAULT_MODE : mode;
        ContractReport report = new ContractReport();
        List<RuntimeRoute> runtimeRoutes = runtimeRoutes(mappings);
        Set<RuntimeRoute> matched = new LinkedHashSet<>();
        for (RouteSpec route : ROUTES) {
            RuntimeRoute runtime = findRuntimeRoute(route, runtimeRoutes);
            if (runtime == null) {
                report.add(Severity.ERROR, "missing_server_route", route.id(), route.methodText() + " " + route.path());
                continue;
            }
            matched.add(runtime);
            validateOperationMarker(report, route, runtime);
            validatePolicies(report, route, runtime);
            validateRequestBoundary(report, route, runtime);
            validateResponseBoundary(report, route, runtime);
        }
        if (effectiveMode == ContractMode.STRICT) {
            for (RuntimeRoute runtime : runtimeRoutes) {
                if (matched.contains(runtime) || !isPublicServerRoute(runtime.path())) {
                    continue;
                }
                report.add(
                    Severity.ERROR,
                    "server_only_public_route",
                    runtime.methodText() + " " + runtime.path(),
                    "matched public server surface but no Blueprint route declares it"
                );
            }
        }
        return report;
    }

    private static void validateOperationMarker(ContractReport report, RouteSpec route, RuntimeRoute runtime) {
        ApiBlueprintOperation operation = AnnotatedElementUtils.findMergedAnnotation(
            runtime.handler().getMethod(),
            ApiBlueprintOperation.class
        );
        if (operation == null) {
            report.add(Severity.ERROR, "operation_marker_missing", route.id(), runtime.methodText() + " " + runtime.path());
            return;
        }
        if (!Objects.equals(route.id(), operation.value())) {
            report.add(
                Severity.ERROR,
                "operation_marker_mismatch",
                route.id(),
                "handler declares " + operation.value()
            );
        }
    }

    private static void validatePolicies(ContractReport report, RouteSpec route, RuntimeRoute runtime) {
        for (String policy : route.policies()) {
            Class<? extends Annotation> policyClass = annotationClass(policy);
            if (policyClass == null) {
                report.add(Severity.WARNING, "policy_class_missing", route.id(), policy);
                continue;
            }
            if (!AnnotatedElementUtils.hasAnnotation(runtime.handler().getMethod(), policyClass)) {
                report.add(Severity.ERROR, "policy_annotation_missing", route.id(), policy);
            }
        }
    }

    private static void validateRequestBoundary(ContractReport report, RouteSpec route, RuntimeRoute runtime) {
        if ("annotations-only".equals(route.requestBinding())) {
            report.add(Severity.INFO, "request_boundary_skipped", route.id(), "annotations-only");
            return;
        }
        if ("legacy-bindable".equals(route.requestBinding())) {
            report.add(Severity.WARNING, "request_boundary_partial", route.id(), "legacy-bindable");
            return;
        }
        Set<String> parameterTypes = parameterTypes(runtime.handler().getMethod());
        for (String requestType : route.requestTypes()) {
            if (!parameterTypes.contains(requestType)) {
                report.add(Severity.ERROR, "request_type_missing", route.id(), requestType);
            }
        }
    }

    private static void validateResponseBoundary(ContractReport report, RouteSpec route, RuntimeRoute runtime) {
        if (route.responseType().isEmpty() || "annotations-only".equals(route.responseBinding())) {
            return;
        }
        if ("legacy-raw".equals(route.responseBinding())) {
            report.add(Severity.WARNING, "response_boundary_partial", route.id(), "legacy-raw");
            return;
        }
        String responseType = runtime.handler().getMethod().getGenericReturnType().getTypeName().replace('$', '.');
        if (!responseType.contains(route.responseType())) {
            report.add(Severity.ERROR, "response_type_missing", route.id(), route.responseType());
        }
    }

    private static RuntimeRoute findRuntimeRoute(RouteSpec route, List<RuntimeRoute> runtimeRoutes) {
        for (RuntimeRoute runtime : runtimeRoutes) {
            if (!Objects.equals(route.path(), runtime.path())) {
                continue;
            }
            if (runtime.methods().isEmpty() || intersects(route.methods(), runtime.methods())) {
                return runtime;
            }
        }
        return null;
    }

    private static List<RuntimeRoute> runtimeRoutes(RequestMappingHandlerMapping mappings) {
        List<RuntimeRoute> routes = new ArrayList<>();
        for (Map.Entry<RequestMappingInfo, HandlerMethod> entry : mappings.getHandlerMethods().entrySet()) {
            Set<String> methods = requestMethods(entry.getKey());
            for (String path : paths(entry.getKey())) {
                routes.add(new RuntimeRoute(methods, path, entry.getValue()));
            }
        }
        return routes;
    }

    private static Set<String> requestMethods(RequestMappingInfo info) {
        Set<String> methods = new LinkedHashSet<>();
        for (RequestMethod method : info.getMethodsCondition().getMethods()) {
            methods.add(method.name());
        }
        return methods;
    }

    private static Set<String> paths(RequestMappingInfo info) {
        Set<String> paths = new LinkedHashSet<>();
        collectStringSet(paths, invoke(invoke(info, "getPathPatternsCondition"), "getPatternValues"));
        collectStringSet(paths, invoke(invoke(info, "getPatternsCondition"), "getPatterns"));
        return paths;
    }

    private static Object invoke(Object target, String methodName) {
        if (target == null) {
            return null;
        }
        try {
            Method method = target.getClass().getMethod(methodName);
            return method.invoke(target);
        } catch (ReflectiveOperationException error) {
            return null;
        }
    }

    private static void collectStringSet(Set<String> output, Object value) {
        if (value instanceof Collection<?> collection) {
            for (Object item : collection) {
                if (item != null) {
                    output.add(item.toString());
                }
            }
        }
    }

    private static boolean intersects(Set<String> left, Set<String> right) {
        for (String value : left) {
            if (right.contains(value)) {
                return true;
            }
        }
        return false;
    }

    private static Set<String> parameterTypes(Method method) {
        Set<String> names = new LinkedHashSet<>();
        for (Parameter parameter : method.getParameters()) {
            Class<?> type = parameter.getType();
            String canonicalName = type.getCanonicalName();
            names.add(canonicalName == null ? type.getName().replace('$', '.') : canonicalName);
        }
        return names;
    }

    @SuppressWarnings("unchecked")
    private static Class<? extends Annotation> annotationClass(String name) {
        try {
            Class<?> type = Class.forName(name);
            if (!Annotation.class.isAssignableFrom(type)) {
                return null;
            }
            return (Class<? extends Annotation>) type;
        } catch (ClassNotFoundException error) {
            return null;
        }
    }

    private static boolean isPublicServerRoute(String path) {
        if (PUBLIC_PATHS.isEmpty()) {
            return false;
        }
        for (String excluded : EXCLUDE_SERVER_PATHS) {
            if (PATH_MATCHER.match(excluded, path)) {
                return false;
            }
        }
        for (String included : PUBLIC_PATHS) {
            if (PATH_MATCHER.match(included, path)) {
                return true;
            }
        }
        return false;
    }

    public enum ContractMode {
        AUDIT,
        PUBLIC,
        STRICT
    }

    public enum Severity {
        ERROR,
        WARNING,
        INFO
    }

    public record ContractIssue(Severity severity, String code, String route, String detail) {
    }

    public static final class ContractReport {
        private final List<ContractIssue> issues = new ArrayList<>();

        public List<ContractIssue> issues() {
            return List.copyOf(issues);
        }

        public boolean hasErrors() {
            return issues.stream().anyMatch(issue -> issue.severity() == Severity.ERROR);
        }

        private void add(Severity severity, String code, String route, String detail) {
            issues.add(new ContractIssue(severity, code, route, detail));
        }

        @Override
        public String toString() {
            StringBuilder builder = new StringBuilder("api-blueprint contract mismatch");
            for (ContractIssue issue : issues) {
                builder.append(System.lineSeparator())
                    .append(issue.severity())
                    .append(" ")
                    .append(issue.code())
                    .append(System.lineSeparator())
                    .append("  ")
                    .append(issue.route())
                    .append(System.lineSeparator())
                    .append("  ")
                    .append(issue.detail());
            }
            return builder.toString();
        }
    }

    private record RouteSpec(
        String id,
        Set<String> methods,
        String path,
        String annotation,
        List<String> policies,
        List<String> requestTypes,
        String responseType,
        List<String> requiredRequestFields,
        String requestBinding,
        String responseBinding
    ) {
        String methodText() {
            return String.join(",", methods);
        }
    }

    private record RuntimeRoute(Set<String> methods, String path, HandlerMethod handler) {
        String methodText() {
            return methods.isEmpty() ? "*" : String.join(",", methods);
        }
    }
}
