// Code generated by api-blueprint (Kotlin server); DO NOT EDIT.
package com.example.apiblueprint.api.runtime

public data class ApiServerResponse(
    public val statusCode: Int,
    public val body: String,
    public val contentType: String = "application/json",
    public val headers: Map<String, String> = emptyMap(),
)

public data class ApiResponseEnvelope(
    public val name: String = "NoEnvelope",
    public val kind: String = "none",
    public val errorIdentity: String = "none",
    public val successCode: Int = 0,
    public val successMessage: String = "ok",
    public val fields: ApiResponseEnvelopeFields = ApiResponseEnvelopeFields(),
) {
    public companion object {
        public fun none(): ApiResponseEnvelope = ApiResponseEnvelope()
    }
}

public data class ApiResponseEnvelopeFields(
    public val code: String = "code",
    public val message: String = "message",
    public val data: String = "data",
    public val error: String = "error",
    public val ok: String = "ok",
)

public interface ApiServerStream<Message, Close> {
    public suspend fun send(message: Message)

    public suspend fun close(close: Close)

    public suspend fun abort(code: Int = 1011, reason: String? = null)
}

public interface ApiServerChannel<Recv, Send, Close> : ApiServerStream<Send, Close> {
    public suspend fun receive(): Recv?
}
