# Code generated by api-blueprint (Python client); DO NOT EDIT.
from __future__ import annotations

from dataclasses import dataclass
from typing import Any, AsyncIterator, BinaryIO, Generic, Mapping, Protocol, TypedDict, TypeVar

from .binary import ApiBinaryBody


RecvT = TypeVar("RecvT")
SendT = TypeVar("SendT")
CloseT = TypeVar("CloseT")
RawT = TypeVar("RawT")


ApiUploadFile = bytes | bytearray | memoryview | BinaryIO | tuple[str, bytes] | tuple[str, bytes, str] | Any


@dataclass(frozen=True)
class ApiRawResponse(Generic[RawT]):
    body: RawT
    headers: Mapping[str, str]
    status: int
    content_type: str = ""
    content_disposition: str = ""
    filename: str | None = None


class ApiStreamResponse(ApiRawResponse[AsyncIterator[bytes]]):
    async def aclose(self) -> None:
        ...

    def __aiter__(self) -> AsyncIterator[bytes]:
        return self.body


class ApiResponseEnvelopeFields(TypedDict, total=False):
    code: str
    message: str
    data: str
    error: str
    ok: str


class ApiResponseEnvelope(TypedDict):
    name: str
    kind: str
    error_identity: str
    success_code: int
    success_message: str
    fields: ApiResponseEnvelopeFields


class ApiClientTransport(Protocol):
    async def request(
        self,
        method: str,
        path: str,
        *,
        route_id: str = "",
        query: Mapping[str, Any] | None = None,
        json: Any = None,
        form: Mapping[str, Any] | None = None,
        multipart: Mapping[str, Any] | None = None,
        binary: bytes | ApiBinaryBody | None = None,
        open_data: Mapping[str, Any] | None = None,
        response_type: str | None = None,
        response_envelope: ApiResponseEnvelope | None = None,
    ) -> Any:
        ...

    def open_stream(
        self,
        *,
        route_id: str,
        path: str,
        query: Mapping[str, Any] | None = None,
        open_data: Mapping[str, Any] | None = None,
        headers: Mapping[str, str] | None = None,
    ) -> "ApiStreamBridge[Any, Any]":
        ...

    def open_channel(
        self,
        *,
        route_id: str,
        path: str,
        query: Mapping[str, Any] | None = None,
        open_data: Mapping[str, Any] | None = None,
        headers: Mapping[str, str] | None = None,
        protocols: tuple[str, ...] = (),
    ) -> "ApiChannelBridge[Any, Any, Any]":
        ...


class ApiStreamBridge(Protocol, Generic[RecvT, CloseT]):
    def __aiter__(self) -> AsyncIterator[RecvT]:
        ...

    async def close(self) -> CloseT | None:
        ...


class ApiChannelBridge(ApiStreamBridge[RecvT, CloseT], Protocol, Generic[RecvT, SendT, CloseT]):
    async def send(self, message: SendT) -> None:
        ...
