// Code generated by api-blueprint (Go client); DO NOT EDIT.

package account

import (
	"context"
	runtime "example.com/project/golang/client/runtime"
)

type GenAccountClient struct {
	transport runtime.Transport
}

func NewGenAccountClient(transport runtime.Transport) *GenAccountClient {
	return &GenAccountClient{transport: transport}
}

type Client = GenAccountClient

var NewClient = NewGenAccountClient

type AccountClient = GenAccountClient

var NewAccountClient = NewGenAccountClient

func (client *GenAccountClient) AccountProfile(ctx context.Context, opts ...runtime.RequestOption) (*AccountProfileResponse, error) {
	request := runtime.Request{
		RouteID:          "legacy.account.get.profile",
		Method:           "GET",
		Path:             "/account/profile",
		ResponseEnvelope: runtime.ApiResponseEnvelope{Name: "CodeMessageDataEnvelope", Kind: "code_message_data", ErrorIdentity: "nested", SuccessCode: runtime.ApiErrorCode(0), SuccessMessage: "ok", Fields: runtime.ApiResponseEnvelopeFields{Code: "code", Message: "message", Data: "data", Error: "error", Ok: "ok"}},
		BodyKind:         runtime.RequestBodyKind("none"),
		ResponseKind:     runtime.ResponseKind("json"),
	}
	request.ApplyOptions(opts...)
	var response AccountProfileResponse
	if err := client.transport.Do(ctx, request, &response); err != nil {
		return nil, err
	}
	return &response, nil
}
