// Code generated by api-blueprint (Wails V2); DO NOT EDIT.

package static

import (
	runtime "example.com/apiblueprint/wailsv2/runtime"
)

type StaticService struct {
	impl     RouterInterface
	sessions *runtime.SocketHub
}

func NewStaticService(impl RouterInterface, dispatcher runtime.EventDispatcher) *StaticService {
	return &StaticService{
		impl:     impl,
		sessions: runtime.NewSocketHub(dispatcher),
	}
}

func (svc *StaticService) DocJson(envelope *INVOKE_DocJson) (rsp *RSP_DocJson, err error) {
	req := runtime.EnvelopeToReq[any, any](envelope)
	ctx := runtime.NewInvokeContext[any, any, RSP_DocJson_BODY]("StaticService", "DocJson", runtime.EnvelopeHeaders(envelope))
	ctx.Req = &runtime.ReqContext[any, any, RSP_DocJson_BODY]{Request: req}
	rsp, err = svc.impl.DocJson(ctx, req)
	ctx.Handle = &runtime.HandleContext[any, any, RSP_DocJson_BODY]{
		Response: rsp,
		Error:    err,
	}
	return rsp, err
}

func (svc *StaticService) Dochaha(envelope *INVOKE_Dochaha) (rsp *RSP_Dochaha, err error) {
	req := runtime.EnvelopeToReq[any, any](envelope)
	ctx := runtime.NewInvokeContext[any, any, RSP_Dochaha_BODY]("StaticService", "Dochaha", runtime.EnvelopeHeaders(envelope))
	ctx.Req = &runtime.ReqContext[any, any, RSP_Dochaha_BODY]{Request: req}
	rsp, err = svc.impl.Dochaha(ctx, req)
	ctx.Handle = &runtime.HandleContext[any, any, RSP_Dochaha_BODY]{
		Response: rsp,
		Error:    err,
	}
	return rsp, err
}
