// Code generated by api-blueprint (Java server); DO NOT EDIT.
package com.example.apiblueprint.runtime.adapters.runtime.status;

import com.example.apiblueprint.runtime.runtime.GenApiTypes;

import com.example.apiblueprint.runtime.runtime.GenApiRawResponse;
import com.example.apiblueprint.runtime.runtime.GenApiStreamResponse;
import com.example.apiblueprint.runtime.types.runtime.status.GenStatusTypes;

public final class GenStatusAdapters {
    private GenStatusAdapters() {
    }

    public static GenApiTypes.RuntimeStatus runtimeCurrentStatusResponse(GenApiTypes.RuntimeStatus value) {
        return value;
    }

}
