// Code generated by api-blueprint (Java server); DO NOT EDIT.
package com.example.apiblueprint.api.routes.api.binary.controllers;

import com.example.apiblueprint.api.annotations.ApiBlueprintOperation;
import com.example.apiblueprint.api.routes.api.binary.delegates.GenBinaryDelegate;
import com.example.apiblueprint.api.routes.api.binary.types.GenBinaryTypes;
import com.example.apiblueprint.api.runtime.GenApiRawResponse;
import com.example.apiblueprint.api.runtime.GenApiResponseEnvelope;
import com.example.apiblueprint.api.runtime.GenApiStreamResponse;
import com.example.apiblueprint.api.runtime.GenApiTypes;
import com.example.apiblueprint.api.spring.GenSpringRequestBinder;
import com.example.apiblueprint.api.spring.GenSpringRequestContext;
import com.example.apiblueprint.api.spring.GenSpringResponseWriter;
import com.example.apiblueprint.security.SignatureRequired;
import jakarta.servlet.http.HttpServletRequest;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.multipart.MultipartHttpServletRequest;

@RestController
public class GenBinaryController {
    private final GenBinaryDelegate delegate;

    public GenBinaryController(GenBinaryDelegate delegate) {
        this.delegate = delegate;
    }

    @RequestMapping(path = "/api/binary/packet", method = {RequestMethod.POST})
    @SignatureRequired
    @ApiBlueprintOperation("api.binary.post.packet")
    public ResponseEntity<?> packet(
        @ModelAttribute GenBinaryTypes.PacketQuery query,
        @RequestBody byte[] binaryBody,
        HttpServletRequest servletRequest
    ) throws Exception {
        GenBinaryTypes.DemoPacket binary = GenBinaryTypes.DemoPacketWire.parse(binaryBody);
        GenBinaryTypes.PacketResponse result = delegate.packet(
            query,
            binary,
            GenSpringRequestContext.of(servletRequest)
        );
        return GenSpringResponseWriter.response(result, GenApiResponseEnvelope.of("CodeMessageDataEnvelope", "code_message_data", "nested", 0, "ok", new GenApiResponseEnvelope.Fields("code", "message", "data", "error", "ok")), "application/json", "json");
    }

    @RequestMapping(path = "/api/binary/audit-packet", method = {RequestMethod.POST})
    @SignatureRequired
    @ApiBlueprintOperation("api.binary.post.auditpacket")
    public ResponseEntity<?> auditPacket(
        @ModelAttribute GenBinaryTypes.AuditPacketQuery query,
        @RequestBody byte[] binaryBody,
        HttpServletRequest servletRequest
    ) throws Exception {
        GenBinaryTypes.AuditPacket binary = GenBinaryTypes.AuditPacketWire.parse(binaryBody);
        GenBinaryTypes.AuditPacketResponse result = delegate.auditPacket(
            query,
            binary,
            GenSpringRequestContext.of(servletRequest)
        );
        return GenSpringResponseWriter.response(result, GenApiResponseEnvelope.of("CodeMessageDataEnvelope", "code_message_data", "nested", 0, "ok", new GenApiResponseEnvelope.Fields("code", "message", "data", "error", "ok")), "application/json", "json");
    }

    @RequestMapping(path = "/api/binary/wide-packet", method = {RequestMethod.POST})
    @SignatureRequired
    @ApiBlueprintOperation("api.binary.post.widepacket")
    public ResponseEntity<?> widePacket(
        @ModelAttribute GenBinaryTypes.WidePacketQuery query,
        @RequestBody byte[] binaryBody,
        HttpServletRequest servletRequest
    ) throws Exception {
        GenBinaryTypes.WidePacket binary = GenBinaryTypes.WidePacketWire.parse(binaryBody);
        GenBinaryTypes.WidePacketResponse result = delegate.widePacket(
            query,
            binary,
            GenSpringRequestContext.of(servletRequest)
        );
        return GenSpringResponseWriter.response(result, GenApiResponseEnvelope.of("CodeMessageDataEnvelope", "code_message_data", "nested", 0, "ok", new GenApiResponseEnvelope.Fields("code", "message", "data", "error", "ok")), "application/json", "json");
    }

    @RequestMapping(path = "/api/binary/audit-packet-response", method = {RequestMethod.GET})
    @SignatureRequired
    @ApiBlueprintOperation("api.binary.get.auditpacketresponse")
    public ResponseEntity<?> auditPacketResponse(
        HttpServletRequest servletRequest
    ) throws Exception {
        GenBinaryTypes.AuditPacket result = delegate.auditPacketResponse(
            GenSpringRequestContext.of(servletRequest)
        );
        return GenSpringResponseWriter.binary(GenBinaryTypes.AuditPacketWire.toBinaryBody(result));
    }

}
