// Code generated by api-blueprint (Go client); DO NOT EDIT.

package demo

import (
	"encoding/json"
)

type SweepStreamMessage struct {
	Type string          `json:"type"`
	Data json.RawMessage `json:"data,omitempty"`
}
