// Code generated by api-blueprint (Go client); DO NOT EDIT.

package demo

import (
	"errors"
	"fmt"
)

func VisitAssistantServerMessage[C any](
	ctx C,
	message *AssistantServerMessage,
	processor AssistantServerMessageProcessor[C],
) error {
	if message == nil {
		return newAssistantServerMessageError(AssistantServerMessageErrorNilMessage, "", fmt.Errorf("AssistantServerMessage is nil"))
	}
	if processor == nil {
		return newAssistantServerMessageError(AssistantServerMessageErrorNilProcessor, message.Type, fmt.Errorf("AssistantServerMessageProcessor is nil"))
	}
	switch message.Type {
	case AssistantServerMessageTypeDelta:
		return wrapAssistantServerMessageHandlerError(message.Type, processor.OnDelta(ctx, &AssistantServerMessageDeltaCase{message: message}))
	case AssistantServerMessageTypeDone:
		return wrapAssistantServerMessageHandlerError(message.Type, processor.OnDone(ctx, &AssistantServerMessageDoneCase{message: message}))
	case AssistantServerMessageTypeLog:
		return wrapAssistantServerMessageHandlerError(message.Type, processor.OnLog(ctx, &AssistantServerMessageLogCase{message: message}))
	default:
		return newAssistantServerMessageError(AssistantServerMessageErrorUnknownType, message.Type, fmt.Errorf("unsupported AssistantServerMessage type %q", message.Type))
	}
}

type AssistantServerMessageErrorKind string

const (
	AssistantServerMessageErrorNilMessage    AssistantServerMessageErrorKind = "nil_message"
	AssistantServerMessageErrorNilProcessor  AssistantServerMessageErrorKind = "nil_processor"
	AssistantServerMessageErrorUnknownType   AssistantServerMessageErrorKind = "unknown_type"
	AssistantServerMessageErrorDecodeFailed  AssistantServerMessageErrorKind = "decode_failed"
	AssistantServerMessageErrorHandlerFailed AssistantServerMessageErrorKind = "handler_failed"
)

type AssistantServerMessageError struct {
	Kind AssistantServerMessageErrorKind
	Type string
	Err  error
}

func newAssistantServerMessageError(kind AssistantServerMessageErrorKind, typ string, err error) *AssistantServerMessageError {
	return &AssistantServerMessageError{Kind: kind, Type: typ, Err: err}
}

func (err *AssistantServerMessageError) Error() string {
	if err == nil {
		return ""
	}
	if err.Type != "" && err.Err != nil {
		return fmt.Sprintf("%s: %s: %v", err.Kind, err.Type, err.Err)
	}
	if err.Type != "" {
		return fmt.Sprintf("%s: %s", err.Kind, err.Type)
	}
	if err.Err != nil {
		return fmt.Sprintf("%s: %v", err.Kind, err.Err)
	}
	return string(err.Kind)
}

func (err *AssistantServerMessageError) Unwrap() error {
	if err == nil {
		return nil
	}
	return err.Err
}

func AsAssistantServerMessageError(err error) (*AssistantServerMessageError, bool) {
	var messageErr *AssistantServerMessageError
	if errors.As(err, &messageErr) {
		return messageErr, true
	}
	return nil, false
}

func IsAssistantServerMessageErrorKind(err error, kinds ...AssistantServerMessageErrorKind) bool {
	messageErr, ok := AsAssistantServerMessageError(err)
	return ok && messageErr.IsKind(kinds...)
}

func (err *AssistantServerMessageError) IsKind(kinds ...AssistantServerMessageErrorKind) bool {
	if err == nil {
		return false
	}
	if len(kinds) == 0 {
		return true
	}
	for _, kind := range kinds {
		if err.Kind == kind {
			return true
		}
	}
	return false
}

func (err *AssistantServerMessageError) MessageType() string {
	if err == nil {
		return ""
	}
	return err.Type
}

func (err *AssistantServerMessageError) Cause() error {
	if err == nil {
		return nil
	}
	return err.Err
}

func wrapAssistantServerMessageHandlerError(typ string, err error) error {
	if err == nil {
		return nil
	}
	if _, ok := AsAssistantServerMessageError(err); ok {
		return err
	}
	return newAssistantServerMessageError(AssistantServerMessageErrorHandlerFailed, typ, err)
}
