// Code generated by api-blueprint (Go client); DO NOT EDIT.

package demo

import (
	"context"
	runtime "example.com/project/golang/client/runtime"
)

type GenDemoClient struct {
	transport runtime.Transport
}

func NewGenDemoClient(transport runtime.Transport) *GenDemoClient {
	return &GenDemoClient{transport: transport}
}

type Client = GenDemoClient

var NewClient = NewGenDemoClient

type DemoClient = GenDemoClient

var NewDemoClient = NewGenDemoClient

func (client *GenDemoClient) Abc(ctx context.Context, query AbcQuery) (*AbcResponse, error) {
	request := runtime.Request{
		RouteID:          "api.demo.get.abc",
		Method:           "GET",
		Path:             "/api/demo/abc",
		ResponseEnvelope: runtime.ApiResponseEnvelope{Name: "CodeMessageDataEnvelope", Kind: "code_message_data", ErrorIdentity: "nested", SuccessCode: runtime.ApiErrorCode(0), SuccessMessage: "ok", Fields: runtime.ApiResponseEnvelopeFields{Code: "code", Message: "message", Data: "data", Error: "error", Ok: "ok"}},
		Query:            query,
	}
	var response AbcResponse
	if err := client.transport.Do(ctx, request, &response); err != nil {
		return nil, err
	}
	return &response, nil
}

func (client *GenDemoClient) TestPost(ctx context.Context, jsonBody TestPostJSON) (*TestPostResponse, error) {
	request := runtime.Request{
		RouteID:          "api.demo.post.testpost",
		Method:           "POST",
		Path:             "/api/demo/test_post",
		ResponseEnvelope: runtime.ApiResponseEnvelope{Name: "CodeMessageDataEnvelope", Kind: "code_message_data", ErrorIdentity: "nested", SuccessCode: runtime.ApiErrorCode(0), SuccessMessage: "ok", Fields: runtime.ApiResponseEnvelopeFields{Code: "code", Message: "message", Data: "data", Error: "error", Ok: "ok"}},
		JSON:             jsonBody,
	}
	var response TestPostResponse
	if err := client.transport.Do(ctx, request, &response); err != nil {
		return nil, err
	}
	return &response, nil
}

func (client *GenDemoClient) PutDemo(ctx context.Context, query PutDemoQuery, jsonBody PutDemoJSON) (*PutDemoResponse, error) {
	request := runtime.Request{
		RouteID:          "api.demo.put.z1put",
		Method:           "PUT",
		Path:             "/api/demo/1put",
		ResponseEnvelope: runtime.ApiResponseEnvelope{Name: "CodeMessageDataEnvelope", Kind: "code_message_data", ErrorIdentity: "nested", SuccessCode: runtime.ApiErrorCode(0), SuccessMessage: "ok", Fields: runtime.ApiResponseEnvelopeFields{Code: "code", Message: "message", Data: "data", Error: "error", Ok: "ok"}},
		Query:            query,
		JSON:             jsonBody,
	}
	var response PutDemoResponse
	if err := client.transport.Do(ctx, request, &response); err != nil {
		return nil, err
	}
	return &response, nil
}

func (client *GenDemoClient) Delete(ctx context.Context, query DeleteQuery) (*DeleteResponse, error) {
	request := runtime.Request{
		RouteID:          "api.demo.delete.delete",
		Method:           "DELETE",
		Path:             "/api/demo/delete$",
		ResponseEnvelope: runtime.ApiResponseEnvelope{Name: "CodeMessageDataEnvelope", Kind: "code_message_data", ErrorIdentity: "nested", SuccessCode: runtime.ApiErrorCode(0), SuccessMessage: "ok", Fields: runtime.ApiResponseEnvelopeFields{Code: "code", Message: "message", Data: "data", Error: "error", Ok: "ok"}},
		Query:            query,
	}
	var response DeleteResponse
	if err := client.transport.Do(ctx, request, &response); err != nil {
		return nil, err
	}
	return &response, nil
}

func (client *GenDemoClient) SubscribeSweepEvents(ctx context.Context, openData SweepEventsOpen) error {
	request := runtime.ConnectionRequest{
		Kind:    "stream",
		RouteID: "api.demo.stream.sweepevents",
		Path:    "/api/demo/sweep-events",
		Open:    openData,
	}
	return client.transport.StreamUnsupported(ctx, request)
}

func (client *GenDemoClient) OpenAssistantSession(ctx context.Context, openData AssistantSessionOpen) error {
	request := runtime.ConnectionRequest{
		Kind:    "channel",
		RouteID: "api.demo.channel.assistantsession",
		Path:    "/api/demo/assistant-session",
		Open:    openData,
	}
	return client.transport.ChannelUnsupported(ctx, request)
}

func (client *GenDemoClient) PostDeprecated(ctx context.Context, jsonBody PostDeprecatedJSON) (*PostDeprecatedResponse, error) {
	request := runtime.Request{
		RouteID:          "api.demo.post.postdeprecated",
		Method:           "POST",
		Path:             "/api/demo/post_deprecated",
		ResponseEnvelope: runtime.ApiResponseEnvelope{Name: "CodeMessageDataEnvelope", Kind: "code_message_data", ErrorIdentity: "nested", SuccessCode: runtime.ApiErrorCode(0), SuccessMessage: "ok", Fields: runtime.ApiResponseEnvelopeFields{Code: "code", Message: "message", Data: "data", Error: "error", Ok: "ok"}},
		JSON:             jsonBody,
	}
	var response PostDeprecatedResponse
	if err := client.transport.Do(ctx, request, &response); err != nil {
		return nil, err
	}
	return &response, nil
}

func (client *GenDemoClient) Raw(ctx context.Context) (*RawResponse, error) {
	request := runtime.Request{
		RouteID:          "api.demo.post.raw",
		Method:           "POST",
		Path:             "/api/demo/raw",
		ResponseEnvelope: runtime.ApiResponseEnvelope{Name: "CodeMessageDataEnvelope", Kind: "code_message_data", ErrorIdentity: "nested", SuccessCode: runtime.ApiErrorCode(0), SuccessMessage: "ok", Fields: runtime.ApiResponseEnvelopeFields{Code: "code", Message: "message", Data: "data", Error: "error", Ok: "ok"}},
	}
	var response RawResponse
	if err := client.transport.Do(ctx, request, &response); err != nil {
		return nil, err
	}
	return &response, nil
}

func (client *GenDemoClient) MapModel(ctx context.Context) (*MapModelResponse, error) {
	request := runtime.Request{
		RouteID:          "api.demo.post.mapmodel",
		Method:           "POST",
		Path:             "/api/demo/map_model",
		ResponseEnvelope: runtime.ApiResponseEnvelope{Name: "CodeMessageDataEnvelope", Kind: "code_message_data", ErrorIdentity: "nested", SuccessCode: runtime.ApiErrorCode(0), SuccessMessage: "ok", Fields: runtime.ApiResponseEnvelopeFields{Code: "code", Message: "message", Data: "data", Error: "error", Ok: "ok"}},
	}
	var response MapModelResponse
	if err := client.transport.Do(ctx, request, &response); err != nil {
		return nil, err
	}
	return &response, nil
}

func (client *GenDemoClient) ErrorDemo(ctx context.Context, query ErrorDemoQuery) (*ErrorDemoResponse, error) {
	request := runtime.Request{
		RouteID:          "api.demo.get.errordemo",
		Method:           "GET",
		Path:             "/api/demo/error-demo",
		ResponseEnvelope: runtime.ApiResponseEnvelope{Name: "CodeMessageDataEnvelope", Kind: "code_message_data", ErrorIdentity: "nested", SuccessCode: runtime.ApiErrorCode(0), SuccessMessage: "ok", Fields: runtime.ApiResponseEnvelopeFields{Code: "code", Message: "message", Data: "data", Error: "error", Ok: "ok"}},
		Query:            query,
	}
	var response ErrorDemoResponse
	if err := client.transport.Do(ctx, request, &response); err != nil {
		return nil, err
	}
	return &response, nil
}
