// Code generated by api-blueprint; DO NOT EDIT.
package com.example.apiblueprint.static_.transports.http.static_;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.example.apiblueprint.static_.routes.static_.StaticService;
import com.example.apiblueprint.static_.routes.static_.GenStaticServiceStub;
import com.example.apiblueprint.static_.routes.static_.GenStaticServiceModels;
import com.example.apiblueprint.static_.runtime.GenModels;
import com.example.apiblueprint.static_.runtime.binary.ApiBinaryBody;
import java.util.LinkedHashMap;
import java.util.Map;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

@RestController
public class GenStaticController {
    private final StaticService service;
    private final ObjectMapper objectMapper;

    public GenStaticController(
        @Autowired(required = false) StaticService service,
        ObjectMapper objectMapper
    ) {
        this.service = service == null ? new GenStaticServiceStub() : service;
        this.objectMapper = objectMapper;
    }

    @RequestMapping(path = "/static/doc.json", method = RequestMethod.GET)
    public Object docJson(
        @RequestParam Map<String, String> queryParams
    ) throws Exception {
        Object result = service.docJson(
        );
        return wrapResponse("NoneWrapper", result);
    }

    @RequestMapping(path = "/static/dochaha", method = RequestMethod.GET)
    public Object dochaha(
        @RequestParam Map<String, String> queryParams
    ) throws Exception {
        Object result = service.dochaha(
        );
        return wrapResponse("NoneWrapper", result);
    }

    private Object wrapResponse(String wrapper, Object data) {
        if (!"GeneralWrapper".equals(wrapper)) {
            return data;
        }
        Map<String, Object> envelope = new LinkedHashMap<>();
        envelope.put("code", 0);
        envelope.put("message", "");
        envelope.put("data", data);
        return envelope;
    }
}
