// Code generated by api-blueprint (Go client); DO NOT EDIT.

package client

import (
	alt_conflict "example.com/project/golang/client/routes/alt/conflict"
	api "example.com/project/golang/client/routes/api"
	binary "example.com/project/golang/client/routes/api/binary"
	api_conflict "example.com/project/golang/client/routes/api/conflict"
	demo "example.com/project/golang/client/routes/api/demo"
	hello "example.com/project/golang/client/routes/api/hello"
	media "example.com/project/golang/client/routes/api/media"
	static "example.com/project/golang/client/routes/static"
	runtime "example.com/project/golang/client/runtime"
	httptransport "example.com/project/golang/client/transports/http"
)

type HTTPConfig = httptransport.HttpConfig

type Client struct {
	Api         *api.Client
	Binary      *binary.Client
	APIConflict *api_conflict.Client
	Demo        *demo.Client
	Media       *media.Client
	Hello       *hello.Client
	Static      *static.Client
	AltConflict *alt_conflict.Client
}

func NewHTTP(config HTTPConfig) *Client {
	transport := httptransport.NewClient(config)
	return NewClient(transport)
}

func NewClient(transport runtime.Transport) *Client {
	return &Client{
		Api:         api.NewClient(transport),
		Binary:      binary.NewClient(transport),
		APIConflict: api_conflict.NewClient(transport),
		Demo:        demo.NewClient(transport),
		Media:       media.NewClient(transport),
		Hello:       hello.NewClient(transport),
		Static:      static.NewClient(transport),
		AltConflict: alt_conflict.NewClient(transport),
	}
}
