// Code generated by api-blueprint (Swift client); DO NOT EDIT.
import Foundation
import ABClientRuntime
import ABClientAPIRoutes
import ABClientAltRoutes
import ABClientRuntimeRoutes

public typealias APITransport = ABClientRuntime.APITransport
public typealias APIRequestOptions = ABClientRuntime.APIRequestOptions
public typealias HTTPAPIConfig = ABClientRuntime.HTTPAPIConfig
public typealias URLSessionAPITransport = ABClientRuntime.URLSessionAPITransport

open class GenABClient {
    public let transport: APITransport

    public init(transport: APITransport) {
        self.transport = transport
    }

    public lazy var api = ABClientAPIRoutes.APIRootClient(transport: transport)

    public lazy var alt = ABClientAltRoutes.AltRootClient(transport: transport)

    public lazy var runtime = ABClientRuntimeRoutes.RuntimeRootClient(transport: transport)

}
