// Code generated by api-blueprint (Java server); DO NOT EDIT.
package com.example.apiblueprint.static_.annotations.static_;

import com.example.apiblueprint.static_.annotations.ApiBlueprintOperation;
import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

import org.springframework.web.bind.annotation.RequestMapping;

import org.springframework.web.bind.annotation.RequestMethod;

@Target(ElementType.METHOD)
@Retention(RetentionPolicy.RUNTIME)
@RequestMapping(path = "/static/dochaha", method = {RequestMethod.GET})

@ApiBlueprintOperation("static.static.get.dochaha")
public @interface GenDochaha {
}
