# Code generated by api-blueprint (Python server); DO NOT EDIT.
from __future__ import annotations

import asyncio
import json
from dataclasses import asdict, is_dataclass
from typing import Any

from fastapi import APIRouter, WebSocket, Request, HTTPException, WebSocketDisconnect
from starlette.responses import StreamingResponse, JSONResponse

from ...runtime.errors import ApiError, make_api_error_payload
from ...routes.static.service import StaticService, StaticServiceStub


def create_router(
    static_service: StaticService | None = None,
) -> APIRouter:
    router = APIRouter()
    static_service_impl = static_service or StaticServiceStub()

    @router.api_route("/static/doc.json", methods=["GET"])
    async def static_doc_json(request: Request) -> Any:
        service = static_service_impl
        try:
            result = await service.doc_json(
            )
            return _wrap_response({"name": "NoEnvelope", "kind": "none", "error_identity": "none", "success_code": 0, "success_message": "ok", "fields": {}}, result)
        except ApiError as error:
            return _wrap_api_error({"name": "NoEnvelope", "kind": "none", "error_identity": "none", "success_code": 0, "success_message": "ok", "fields": {}}, error, "static.static.get.docjson")

    @router.api_route("/static/dochaha", methods=["GET"])
    async def static_dochaha(request: Request) -> Any:
        service = static_service_impl
        try:
            result = await service.dochaha(
            )
            return _wrap_response({"name": "NoEnvelope", "kind": "none", "error_identity": "none", "success_code": 0, "success_message": "ok", "fields": {}}, result)
        except ApiError as error:
            return _wrap_api_error({"name": "NoEnvelope", "kind": "none", "error_identity": "none", "success_code": 0, "success_message": "ok", "fields": {}}, error, "static.static.get.dochaha")

    return router


def _query_params(request: Request) -> dict[str, Any] | None:
    values = dict(request.query_params)
    return values or None


async def _json_body(request: Request) -> dict[str, Any] | None:
    body = await request.body()
    if not body:
        return None
    try:
        value = json.loads(body.decode("utf-8"))
    except (UnicodeDecodeError, json.JSONDecodeError) as err:
        raise HTTPException(status_code=400, detail="invalid JSON body") from err
    return value if isinstance(value, dict) else None


async def _form_body(request: Request) -> dict[str, Any] | None:
    values = await request.form()
    result = {key: value for key, value in values.multi_items()}
    return result or None


def _jsonable(value: Any) -> Any:
    if is_dataclass(value):
        return {key: item for key, item in asdict(value).items() if item is not None}
    if isinstance(value, dict):
        return {key: _jsonable(item) for key, item in value.items() if item is not None}
    if isinstance(value, (list, tuple)):
        return [_jsonable(item) for item in value]
    if isinstance(value, bytes):
        return value.decode("utf-8")
    return value


def _wrap_response(envelope: dict[str, Any], data: Any) -> Any:
    payload = _jsonable(data)
    kind = envelope.get("kind") or "none"
    fields = envelope.get("fields") or {}
    if kind == "none":
        return payload
    if kind == "code_message_data":
        return {
            fields.get("code", "code"): envelope.get("success_code", 0),
            fields.get("message", "message"): envelope.get("success_message", "ok"),
            fields.get("data", "data"): payload,
        }
    if kind == "ok_data_error":
        return {
            fields.get("ok", "ok"): True,
            fields.get("data", "data"): payload,
        }
    return payload


def _wrap_api_error(envelope: dict[str, Any], error: ApiError, route_id: str) -> Any:
    payload = _jsonable(make_api_error_payload(_jsonable(error.payload), route_id))
    kind = envelope.get("kind") or "none"
    fields = envelope.get("fields") or {}
    if kind == "none":
        return JSONResponse(payload, status_code=500)
    if kind == "code_message_data":
        body = {
            fields.get("code", "code"): payload.get("code", 0),
            fields.get("message", "message"): payload.get("message", ""),
            fields.get("data", "data"): None,
        }
        if envelope.get("error_identity") != "none":
            body[fields.get("error", "error")] = payload
        return body
    if kind == "ok_data_error":
        return {
            fields.get("ok", "ok"): False,
            fields.get("error", "error"): payload,
        }
    return JSONResponse(payload, status_code=500)


class _SseStream:
    def __init__(self) -> None:
        self._queue: asyncio.Queue[str | None] = asyncio.Queue()
        self.closed = False

    def __aiter__(self):
        return self

    async def __anext__(self) -> str:
        item = await self._queue.get()
        if item is None:
            raise StopAsyncIteration
        return item

    async def send(self, message: Any) -> None:
        if self.closed:
            return
        await self._queue.put("data: " + json.dumps(_jsonable(message), ensure_ascii=False) + "\n\n")

    async def close(self, close: Any) -> None:
        if self.closed:
            return
        self.closed = True
        await self._queue.put(
            "event: close\n"
            + "data: "
            + json.dumps(_jsonable(close), ensure_ascii=False)
            + "\n\n"
        )
        await self._queue.put(None)

    async def abort(self, code: int = 1011, reason: str | None = None) -> None:
        await self.close({"code": code, "reason": reason or ""})


class _WebSocketChannel:
    def __init__(self, websocket: WebSocket) -> None:
        self.websocket = websocket
        self.closed = False

    async def receive(self) -> Any:
        try:
            payload = await self.websocket.receive_text()
        except WebSocketDisconnect as err:
            self.closed = True
            raise _WebSocketClosed() from err
        try:
            return json.loads(payload)
        except (UnicodeDecodeError, json.JSONDecodeError) as err:
            await self.abort(1003, "invalid WebSocket message")
            raise _WebSocketClosed() from err

    async def send(self, message: Any) -> None:
        if self.closed:
            return
        await self.websocket.send_text(
            json.dumps({"type": "message", "data": _jsonable(message)}, ensure_ascii=False)
        )

    async def close(self, close: Any) -> None:
        if self.closed:
            return
        self.closed = True
        await self._send_close(close, 1000)

    async def abort(self, code: int = 1011, reason: str | None = None) -> None:
        if self.closed:
            return
        self.closed = True
        await self._send_close({"code": code, "reason": reason or ""}, code)

    async def _send_close(self, close: Any, code: int) -> None:
        try:
            await self.websocket.send_text(
                json.dumps({"type": "close", "data": _jsonable(close)}, ensure_ascii=False)
            )
        finally:
            await self.websocket.close(code=code)


class _WebSocketClosed(Exception):
    pass
