// Code generated by api-blueprint (Java server); DO NOT EDIT.
package com.example.apiblueprint.static_.runtime;

public interface GenApiServerChannel<Recv, Send, Close> extends GenApiServerStream<Send, Close> {
    Recv receive() throws Exception;
}