/* eslint-disable */
/* istanbul ignore file */
// Code generated by api-blueprint (TypeScript); DO NOT EDIT.

import type { ApiClientConfig } from "../../(shared)/client";
import { WailsV2Transport } from "../../(shared)/(wailsv2)/transport";
import { StaticClient as SharedStaticClient } from "../client";


export type StaticClient = SharedStaticClient;


export function createClient(config: ApiClientConfig = {}): StaticClient {
  return new SharedStaticClient({
    ...config,
    transport: config.transport ?? new WailsV2Transport(config),
  }) as StaticClient;
}
