// Code generated by api-blueprint; DO NOT EDIT.
package com.example.apiblueprint.api.runtime;

import java.util.Map;
import java.util.Optional;

public final class GenApiErrorCatalog {
    private GenApiErrorCatalog() {
    }

    public static final int COMMONERR_UNKNOWN = -1;

    public static final int COMMONERR_TOKEN_EXPIRE = 55555;

    public static final Map<String, ApiErrorCatalogEntry> ERROR_CATALOG_BY_ID = Map.ofEntries(
        Map.entry(
            "CommonErr.UNKNOWN",
            new ApiErrorCatalogEntry(
                "CommonErr.UNKNOWN",
                "CommonErr",
                "UNKNOWN",
                -1,
                "未知错误",
                new ApiToastSpec(
                    "CommonErr.UNKNOWN",
                    "error",
                    "未知错误"
                )
            )
        ),
        Map.entry(
            "CommonErr.TOKEN_EXPIRE",
            new ApiErrorCatalogEntry(
                "CommonErr.TOKEN_EXPIRE",
                "CommonErr",
                "TOKEN_EXPIRE",
                55555,
                "token登录态失效",
                new ApiToastSpec(
                    "auth.token_expire",
                    "warning",
                    "登录状态已失效，请重新登录"
                )
            )
        )
    );

    public static Optional<ApiErrorCatalogEntry> findById(String id) {
        return Optional.ofNullable(ERROR_CATALOG_BY_ID.get(id));
    }
}