// Code generated by api-blueprint (Go server HTTP adapter); DO NOT EDIT.

package account

import (
	sharedprovider "example.com/project/golang/server/views/providers"
	shared "example.com/project/golang/server/views/routes/legacy/account"
	httptransport "example.com/project/golang/server/views/transports/http"

	"github.com/gin-gonic/gin"
)

func Mount(eng *gin.Engine, impl *shared.Router) *shared.Router {
	if impl == nil {
		impl = shared.NewRouter()
	}

	httptransport.GET(
		"/account/profile",
		sharedprovider.NewRouteExecutor(
			sharedprovider.RouteInfo{
				Root:      "legacy",
				Group:     "account",
				Namespace: "account",
				Service:   "AccountService",
				Operation: "AccountProfile",
				RouteID:   "legacy.account.get.profile",
				Path:      "/account/profile",
				Methods:   []string{"GET"},
				Transport: sharedprovider.TransportHTTP,
				Scope:     sharedprovider.ConnectionScope(""),
				HTTP: sharedprovider.HTTPRouteInfo{
					Request: sharedprovider.HTTPRequestInfo{
						BinaryContentEncodings: []string{},
					},
					Response: sharedprovider.HTTPResponseInfo{
						ManualResponse:  false,
						DefaultFilename: "",
					},
				},
			},
			"req|request-signature|handle|rsp=json@CodeMessageDataEnvelope",
			impl.AccountProfile,
		),
		eng,
	)

	return impl
}

func NewRouter(eng *gin.Engine) *shared.Router {
	return Mount(eng, shared.NewRouter())
}

func NewImpl(eng *gin.Engine) *shared.Router {
	return NewRouter(eng)
}
