/* eslint-disable */
/* istanbul ignore file */
// Code generated by api-blueprint (TypeScript client); DO NOT EDIT.

import type * as Types from "./types";
import type * as Shared from "../../../runtime/types";
import { ApiChannelBridge, ApiClientConfig, ApiRequestOptions, ApiStreamBridge, BaseClient } from "../../../runtime/client";

export class AccountClient extends BaseClient {
  constructor(config: ApiClientConfig = {}) {
    super(config);
  }

  /**
   * Rootless account profile example
   * Covers a rootless Blueprint group under /account.
   * Tags: legacy, api
   */

  async accountProfile(
    request: {} = {},
    options?: ApiRequestOptions,
  ): Promise<Types.AccountProfileResponse> {
    return this.request<Types.AccountProfileResponse>({
      routeId: "legacy.account.get.profile",
      method: "GET",
      path: "/account/profile",
      service: "AccountService",
      operation: "AccountProfile",
      namespace: "account",
      headers: options?.headers,
      init: options?.init,
      responseType: "json",
      responseEnvelope: {"name": "CodeMessageDataEnvelope", "kind": "code_message_data", "error_identity": "nested", "success_code": 0, "success_message": "ok", "fields": {"code": "code", "message": "message", "data": "data", "error": "error"}},
      timeoutMs: options?.timeoutMs,
    });
  }

}
