// Code generated by api-blueprint (Go server); DO NOT EDIT.

package enums

//go:generate go-enum --nocase --names --values --mustparse --output-suffix=_gen --file=$GOFILE

/*
ENUM(

	PING = "ping"
	PONG = "pong"
	JOIN = "join"
	LEAVE = "leave"
	FORGEROUND = "forgeround"
	UPGRADE = "upgrade"

)
*/
type HelloChannelMsgTypeEnum string

/*
ENUM(

	DEFAULT = "default"
	CLASS = "class"

)
*/
type KeywordEnum string

/*
ENUM(

	RED = "red" // Red color
	GREEN = "green" // Green color
	BLUE = "blue" // Blue color

)
*/
type ColorEnum string

/*
ENUM(

	PENDING = 1 // Pending status
	RUNNING = 2 // Running status
	FINISHED = 3 // Finished status

)
*/
type StatusEnum int

/*
ENUM(

	A = "a"
	B = "b"

)
*/
type MapEnum string

/*
ENUM(

	ASD = "ASD"

)
*/
type HelloWayEnum string
