// Code generated by api-blueprint (Flutter client); DO NOT EDIT.
// ignore_for_file: unused_import

import 'package:api_blueprint_example/src/api/runtime/gen_api_transport.dart';
import 'package:api_blueprint_example/src/api/runtime/gen_api_errors.dart';
import 'package:api_blueprint_example/src/api/runtime/gen_api_types.dart';
import 'gen_conflict_types.dart';


class GenConflictApi {
  final ApiTransport transport;

  GenConflictApi(this.transport);



  Future<ConflictModel> default_({
    ConflictDefaultQuery? query,
    Map<String, String> headers = const {},
  }) {
    return transport.request(
      ApiRequest<ConflictModel>(
        routeId: "api.conflict.get.default",
        method: "GET",
        path: "/api/conflict/default",
        query: query?.toQueryMap() ?? const <String, String?>{},
        headers: headers,
        responseMediaType: "application/json",
        responseEnvelope: ApiResponseEnvelope(name: "CodeMessageDataEnvelope", kind: "code_message_data", errorIdentity: "nested", successCode: 0, successMessage: "ok", fields: ApiResponseEnvelopeFields(code: "code", message: "message", data: "data", error: "error", ok: "ok")),
        decode: ConflictModel.fromJsonValue,
      ),
    );
  }


}
