// Code generated by api-blueprint (Go server HTTP adapter); DO NOT EDIT.

package hello

import (
	"reflect"

	sharedprovider "example.com/project/golang/server/views/providers"
	shared "example.com/project/golang/server/views/routes/api/hello"
	httptransport "example.com/project/golang/server/views/transports/http"

	"github.com/gin-gonic/gin"
)

func Mount(router gin.IRouter, impl shared.RouterInterface) shared.RouterInterface {
	return MountSelected(router, impl, nil)
}

func MountSelected(router gin.IRouter, impl shared.RouterInterface, routeIDs map[string]struct{}) shared.RouterInterface {
	if isNilRouterInterface(impl) {
		impl = shared.NewRouter()
	}

	if shouldMountRoute(routeIDs, "api.hello.get.abc") {

		httptransport.GET(
			"/api/hello/abc",
			sharedprovider.NewRouteExecutor(
				sharedprovider.RouteInfo{
					Root:      "api",
					Group:     "hello",
					Namespace: "hello",
					Service:   "HelloService",
					Operation: "Abc",
					RouteID:   "api.hello.get.abc",
					Path:      "/api/hello/abc",
					Methods:   []string{"GET"},
					Transport: sharedprovider.TransportHTTP,
					Scope:     sharedprovider.ConnectionScope(""),
					HTTP: sharedprovider.HTTPRouteInfo{
						Request: sharedprovider.HTTPRequestInfo{
							PathParams:             []string{},
							BinaryContentEncodings: []string{},
						},
						Response: sharedprovider.HTTPResponseInfo{
							ManualResponse:  false,
							DefaultFilename: "",
						},
					},
				},
				"req=query|auth|request-signature|handle|rsp=json@CodeMessageDataEnvelope",
				impl.Abc,
			),
			router,
		)

	}

	if shouldMountRoute(routeIDs, "api.hello.get.mapenum") {

		httptransport.GET(
			"/api/hello/map-enum",
			sharedprovider.NewRouteExecutor(
				sharedprovider.RouteInfo{
					Root:      "api",
					Group:     "hello",
					Namespace: "hello",
					Service:   "HelloService",
					Operation: "MapEnum",
					RouteID:   "api.hello.get.mapenum",
					Path:      "/api/hello/map-enum",
					Methods:   []string{"GET"},
					Transport: sharedprovider.TransportHTTP,
					Scope:     sharedprovider.ConnectionScope(""),
					HTTP: sharedprovider.HTTPRouteInfo{
						Request: sharedprovider.HTTPRequestInfo{
							PathParams:             []string{},
							BinaryContentEncodings: []string{},
						},
						Response: sharedprovider.HTTPResponseInfo{
							ManualResponse:  false,
							DefaultFilename: "",
						},
					},
				},
				"req|auth|request-signature|handle|rsp=json@CodeMessageDataEnvelope",
				impl.MapEnum,
			),
			router,
		)

	}

	if shouldMountRoute(routeIDs, "api.hello.get.listenum") {

		httptransport.GET(
			"/api/hello/list-enum",
			sharedprovider.NewRouteExecutor(
				sharedprovider.RouteInfo{
					Root:      "api",
					Group:     "hello",
					Namespace: "hello",
					Service:   "HelloService",
					Operation: "ListEnum",
					RouteID:   "api.hello.get.listenum",
					Path:      "/api/hello/list-enum",
					Methods:   []string{"GET"},
					Transport: sharedprovider.TransportHTTP,
					Scope:     sharedprovider.ConnectionScope(""),
					HTTP: sharedprovider.HTTPRouteInfo{
						Request: sharedprovider.HTTPRequestInfo{
							PathParams:             []string{},
							BinaryContentEncodings: []string{},
						},
						Response: sharedprovider.HTTPResponseInfo{
							ManualResponse:  false,
							DefaultFilename: "",
						},
					},
				},
				"req|auth|request-signature|handle|rsp=json@CodeMessageDataEnvelope",
				impl.ListEnum,
			),
			router,
		)

	}

	if shouldMountRoute(routeIDs, "api.hello.get.string") {

		httptransport.GET(
			"/api/hello/string",
			sharedprovider.NewRouteExecutor(
				sharedprovider.RouteInfo{
					Root:      "api",
					Group:     "hello",
					Namespace: "hello",
					Service:   "HelloService",
					Operation: "String",
					RouteID:   "api.hello.get.string",
					Path:      "/api/hello/string",
					Methods:   []string{"GET"},
					Transport: sharedprovider.TransportHTTP,
					Scope:     sharedprovider.ConnectionScope(""),
					HTTP: sharedprovider.HTTPRouteInfo{
						Request: sharedprovider.HTTPRequestInfo{
							PathParams:             []string{},
							BinaryContentEncodings: []string{},
						},
						Response: sharedprovider.HTTPResponseInfo{
							ManualResponse:  false,
							DefaultFilename: "",
						},
					},
				},
				"req|auth|request-signature|handle|rsp=json@CodeMessageDataEnvelope",
				impl.String,
			),
			router,
		)

	}

	if shouldMountRoute(routeIDs, "api.hello.get.uint64") {

		httptransport.GET(
			"/api/hello/uint64",
			sharedprovider.NewRouteExecutor(
				sharedprovider.RouteInfo{
					Root:      "api",
					Group:     "hello",
					Namespace: "hello",
					Service:   "HelloService",
					Operation: "Uint64",
					RouteID:   "api.hello.get.uint64",
					Path:      "/api/hello/uint64",
					Methods:   []string{"GET"},
					Transport: sharedprovider.TransportHTTP,
					Scope:     sharedprovider.ConnectionScope(""),
					HTTP: sharedprovider.HTTPRouteInfo{
						Request: sharedprovider.HTTPRequestInfo{
							PathParams:             []string{},
							BinaryContentEncodings: []string{},
						},
						Response: sharedprovider.HTTPResponseInfo{
							ManualResponse:  false,
							DefaultFilename: "",
						},
					},
				},
				"req|auth|request-signature|handle|rsp=json@CodeMessageDataEnvelope",
				impl.Uint64,
			),
			router,
		)

	}

	if shouldMountRoute(routeIDs, "api.hello.get.stringemun") {

		httptransport.GET(
			"/api/hello/string-emun",
			sharedprovider.NewRouteExecutor(
				sharedprovider.RouteInfo{
					Root:      "api",
					Group:     "hello",
					Namespace: "hello",
					Service:   "HelloService",
					Operation: "StringEmun",
					RouteID:   "api.hello.get.stringemun",
					Path:      "/api/hello/string-emun",
					Methods:   []string{"GET"},
					Transport: sharedprovider.TransportHTTP,
					Scope:     sharedprovider.ConnectionScope(""),
					HTTP: sharedprovider.HTTPRouteInfo{
						Request: sharedprovider.HTTPRequestInfo{
							PathParams:             []string{},
							BinaryContentEncodings: []string{},
						},
						Response: sharedprovider.HTTPResponseInfo{
							ManualResponse:  false,
							DefaultFilename: "",
						},
					},
				},
				"req|auth|request-signature|handle|rsp=json@CodeMessageDataEnvelope",
				impl.StringEmun,
			),
			router,
		)

	}

	if shouldMountRoute(routeIDs, "api.hello.get.helloway") {

		httptransport.GET(
			"/api/hello/hello-way",
			sharedprovider.NewRouteExecutor(
				sharedprovider.RouteInfo{
					Root:      "api",
					Group:     "hello",
					Namespace: "hello",
					Service:   "HelloService",
					Operation: "HelloWay",
					RouteID:   "api.hello.get.helloway",
					Path:      "/api/hello/hello-way",
					Methods:   []string{"GET"},
					Transport: sharedprovider.TransportHTTP,
					Scope:     sharedprovider.ConnectionScope(""),
					HTTP: sharedprovider.HTTPRouteInfo{
						Request: sharedprovider.HTTPRequestInfo{
							PathParams:             []string{},
							BinaryContentEncodings: []string{},
						},
						Response: sharedprovider.HTTPResponseInfo{
							ManualResponse:  false,
							DefaultFilename: "",
						},
					},
				},
				"req=query|auth|request-signature|handle|rsp=json@CodeMessageDataEnvelope",
				impl.HelloWay,
			),
			router,
		)

	}

	return impl
}

func NewRouter(router gin.IRouter) *shared.Router {
	impl := shared.NewRouter()
	Mount(router, impl)
	return impl
}

func NewImpl(router gin.IRouter) *shared.Router {
	return NewRouter(router)
}

func isNilRouterInterface(impl shared.RouterInterface) bool {
	if impl == nil {
		return true
	}
	value := reflect.ValueOf(impl)
	switch value.Kind() {
	case reflect.Chan, reflect.Func, reflect.Interface, reflect.Map, reflect.Pointer, reflect.Slice:
		return value.IsNil()
	default:
		return false
	}
}

func shouldMountRoute(routeIDs map[string]struct{}, routeID string) bool {
	if len(routeIDs) == 0 {
		return true
	}
	_, ok := routeIDs[routeID]
	return ok
}
