// Code generated by api-blueprint (Go server); DO NOT EDIT.

package binary

const (
	RouteIDPacket              = "api.binary.post.packet"
	RouteIDAuditPacket         = "api.binary.post.auditpacket"
	RouteIDWidePacket          = "api.binary.post.widepacket"
	RouteIDAuditPacketResponse = "api.binary.get.auditpacketresponse"
)

const (
	RoutePathPacket              = "/api/binary/packet"
	RoutePathAuditPacket         = "/api/binary/audit-packet"
	RoutePathWidePacket          = "/api/binary/wide-packet"
	RoutePathAuditPacketResponse = "/api/binary/audit-packet-response"
)
