// Code generated by api-blueprint (Java server); DO NOT EDIT.
package com.example.apiblueprint.api.transports.http.api.binary;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.example.apiblueprint.api.routes.api.binary.BinaryService;
import com.example.apiblueprint.api.routes.api.binary.GenBinaryServiceStub;
import com.example.apiblueprint.api.routes.api.binary.GenBinaryTypes;
import com.example.apiblueprint.api.transports.http.GenSpringServerConfig;
import com.example.apiblueprint.api.runtime.GenApiError;
import com.example.apiblueprint.api.runtime.GenApiErrorEntry;
import com.example.apiblueprint.api.runtime.GenApiErrorPayload;
import com.example.apiblueprint.api.runtime.GenApiErrors;
import com.example.apiblueprint.api.runtime.GenApiFilePart;
import com.example.apiblueprint.api.runtime.GenApiRawResponse;
import com.example.apiblueprint.api.runtime.GenApiResponseEnvelope;
import com.example.apiblueprint.api.runtime.GenApiServerChannel;
import com.example.apiblueprint.api.runtime.GenApiServerStream;
import com.example.apiblueprint.api.runtime.GenApiStreamResponse;
import com.example.apiblueprint.api.runtime.GenApiToastPayload;
import com.example.apiblueprint.api.runtime.GenApiTypes;
import com.example.apiblueprint.api.runtime.binary.GenApiBinaryBody;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.lang.reflect.Constructor;
import java.lang.reflect.RecordComponent;
import java.nio.charset.StandardCharsets;
import java.net.URI;
import java.net.URLDecoder;
import java.net.URLEncoder;
import java.util.concurrent.BlockingQueue;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.Executor;
import java.util.concurrent.ForkJoinPool;
import java.util.concurrent.LinkedBlockingQueue;
import java.util.LinkedHashMap;
import java.util.Locale;
import java.util.Map;
import java.util.Set;
import java.util.zip.GZIPInputStream;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.core.io.InputStreamResource;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.multipart.MultipartHttpServletRequest;
import org.springframework.web.servlet.mvc.method.annotation.SseEmitter;

@RestController
public class GenBinaryController {
    private record HttpRouteInfo(HttpRequestInfo request, HttpResponseInfo response) {
    }

    private record HttpRequestInfo(Set<String> binaryContentEncodings) {
    }

    private record HttpResponseInfo(String kind, String mediaType, String defaultFilename) {
    }

    private static final HttpRouteInfo HTTP_ROUTE_API_BINARY_POST_PACKET = new HttpRouteInfo(
        new HttpRequestInfo(Set.of("identity", "gzip", "br")),
        new HttpResponseInfo(
            "json",
            "application/json",
            ""
        )
    );

    private static final HttpRouteInfo HTTP_ROUTE_API_BINARY_POST_AUDITPACKET = new HttpRouteInfo(
        new HttpRequestInfo(Set.of("identity")),
        new HttpResponseInfo(
            "json",
            "application/json",
            ""
        )
    );

    private static final HttpRouteInfo HTTP_ROUTE_API_BINARY_GET_AUDITPACKETRESPONSE = new HttpRouteInfo(
        new HttpRequestInfo(Set.of()),
        new HttpResponseInfo(
            "binary_schema",
            "application/octet-stream",
            ""
        )
    );

    private final BinaryService service;
    private final ObjectMapper objectMapper;
    private final GenSpringServerConfig serverConfig;
    private final Executor connectionExecutor;

    public GenBinaryController(
        @Autowired(required = false) BinaryService service,
        ObjectMapper objectMapper,
        @Autowired(required = false) GenSpringServerConfig serverConfig,
        @Autowired(required = false) Executor connectionExecutor
    ) {
        this.service = service == null ? new GenBinaryServiceStub() : service;
        this.objectMapper = objectMapper;
        this.serverConfig = serverConfig == null ? GenSpringServerConfig.defaults() : serverConfig;
        this.connectionExecutor = connectionExecutor == null ? ForkJoinPool.commonPool() : connectionExecutor;
    }

    @RequestMapping(path = "/api/binary/packet", method = RequestMethod.POST)
    public Object packet(
        @RequestParam Map<String, String> queryParams,
        @RequestBody(required = false) byte[] binaryBody,
        @RequestHeader(name = HttpHeaders.CONTENT_ENCODING, required = false) String contentEncoding
    ) throws Exception {
        GenBinaryTypes.PacketQuery query;
        GenBinaryTypes.DemoPacket binary;
        try {
            query = objectMapper.convertValue(queryParams, GenBinaryTypes.PacketQuery.class);
            binary = GenBinaryTypes.DemoPacketWire.parse(
                decodeBinarySchemaBody(binaryBody == null ? new byte[0] : binaryBody, contentEncoding, HTTP_ROUTE_API_BINARY_POST_PACKET.request())
            );
        } catch (PayloadTooLargeException error) {
            return payloadTooLargeResponse(error);
        } catch (UnsupportedContentEncodingException error) {
            return unsupportedContentEncodingResponse(error);
        } catch (RuntimeException error) {
            return badRequestResponse(error);
        }
        try {
            Object result = service.packet(
                query,
                binary
            );
            return wrapResponse(GenApiResponseEnvelope.of("CodeMessageDataEnvelope", "code_message_data", "nested", 0, "ok", new GenApiResponseEnvelope.Fields("code", "message", "data", "error", "ok")), result);
        } catch (GenApiError error) {
            return wrapApiErrorResponse(GenApiResponseEnvelope.of("CodeMessageDataEnvelope", "code_message_data", "nested", 0, "ok", new GenApiResponseEnvelope.Fields("code", "message", "data", "error", "ok")), error, "api.binary.post.packet");
        }
    }

    @RequestMapping(path = "/api/binary/audit-packet", method = RequestMethod.POST)
    public Object auditPacket(
        @RequestParam Map<String, String> queryParams,
        @RequestBody(required = false) byte[] binaryBody,
        @RequestHeader(name = HttpHeaders.CONTENT_ENCODING, required = false) String contentEncoding
    ) throws Exception {
        GenBinaryTypes.AuditPacketQuery query;
        GenBinaryTypes.AuditPacket binary;
        try {
            query = objectMapper.convertValue(queryParams, GenBinaryTypes.AuditPacketQuery.class);
            binary = GenBinaryTypes.AuditPacketWire.parse(
                decodeBinarySchemaBody(binaryBody == null ? new byte[0] : binaryBody, contentEncoding, HTTP_ROUTE_API_BINARY_POST_AUDITPACKET.request())
            );
        } catch (PayloadTooLargeException error) {
            return payloadTooLargeResponse(error);
        } catch (UnsupportedContentEncodingException error) {
            return unsupportedContentEncodingResponse(error);
        } catch (RuntimeException error) {
            return badRequestResponse(error);
        }
        try {
            Object result = service.auditPacket(
                query,
                binary
            );
            return wrapResponse(GenApiResponseEnvelope.of("CodeMessageDataEnvelope", "code_message_data", "nested", 0, "ok", new GenApiResponseEnvelope.Fields("code", "message", "data", "error", "ok")), result);
        } catch (GenApiError error) {
            return wrapApiErrorResponse(GenApiResponseEnvelope.of("CodeMessageDataEnvelope", "code_message_data", "nested", 0, "ok", new GenApiResponseEnvelope.Fields("code", "message", "data", "error", "ok")), error, "api.binary.post.auditpacket");
        }
    }

    @RequestMapping(path = "/api/binary/audit-packet-response", method = RequestMethod.GET)
    public Object auditPacketResponse(
        @RequestParam Map<String, String> queryParams
    ) throws Exception {
        try {
            Object result = service.auditPacketResponse(
            );
            return rawBytesResponse(HTTP_ROUTE_API_BINARY_GET_AUDITPACKETRESPONSE.response(), GenBinaryTypes.AuditPacketWire.toBinaryBody((GenBinaryTypes.AuditPacket) result).toBytes());
        } catch (GenApiError error) {
            return wrapApiErrorResponse(GenApiResponseEnvelope.of("CodeMessageDataEnvelope", "code_message_data", "nested", 0, "ok", new GenApiResponseEnvelope.Fields("code", "message", "data", "error", "ok")), error, "api.binary.get.auditpacketresponse");
        }
    }

    private static final class SpringSseStream<Message, Close> implements GenApiServerStream<Message, Close> {
        private final SseEmitter emitter;
        private final ObjectMapper objectMapper;
        private volatile boolean closed = false;

        SpringSseStream(SseEmitter emitter, ObjectMapper objectMapper) {
            this.emitter = emitter;
            this.objectMapper = objectMapper;
        }

        @Override
        public void send(Message message) throws Exception {
            if (closed) {
                return;
            }
            emitter.send(SseEmitter.event().data(message, MediaType.APPLICATION_JSON));
        }

        @Override
        public void close(Close close) throws Exception {
            if (closed) {
                return;
            }
            closed = true;
            emitter.send(SseEmitter.event().name("close").data(close, MediaType.APPLICATION_JSON));
            emitter.complete();
        }

        @Override
        public void abort(int code, String reason) throws Exception {
            if (closed) {
                return;
            }
            closed = true;
            emitter.send(SseEmitter.event().name("close").data(Map.of("code", code, "reason", reason == null ? "" : reason), MediaType.APPLICATION_JSON));
            emitter.complete();
        }

        void abortUnchecked(int code, String reason) {
            try {
                abort(code, reason);
            } catch (Exception error) {
                emitter.completeWithError(error);
            }
        }
    }

    private static Map<String, String> parseQuery(URI uri) {
        if (uri == null || uri.getRawQuery() == null || uri.getRawQuery().isBlank()) {
            return Map.of();
        }
        Map<String, String> result = new LinkedHashMap<>();
        for (String part : uri.getRawQuery().split("&")) {
            if (part.isBlank()) {
                continue;
            }
            int separator = part.indexOf('=');
            String key = separator >= 0 ? part.substring(0, separator) : part;
            String value = separator >= 0 ? part.substring(separator + 1) : "";
            result.put(
                URLDecoder.decode(key, StandardCharsets.UTF_8),
                URLDecoder.decode(value, StandardCharsets.UTF_8)
            );
        }
        return result;
    }

    private Object wrapResponse(GenApiResponseEnvelope envelopeSpec, Object data) {
        if ("none".equals(envelopeSpec.kind())) {
            return data;
        }
        Map<String, Object> envelope = new LinkedHashMap<>();
        if ("code_message_data".equals(envelopeSpec.kind())) {
            envelope.put(envelopeSpec.fields().code(), envelopeSpec.successCode());
            envelope.put(envelopeSpec.fields().message(), envelopeSpec.successMessage());
            envelope.put(envelopeSpec.fields().data(), data);
            return envelope;
        }
        if ("ok_data_error".equals(envelopeSpec.kind())) {
            envelope.put(envelopeSpec.fields().ok(), true);
            envelope.put(envelopeSpec.fields().data(), data);
            return envelope;
        }
        return envelope;
    }

    private <T> T multipartBody(MultipartHttpServletRequest request, Class<T> targetClass) throws IOException {
        Map<String, Object> values = multipartValues(request);
        if (!targetClass.isRecord()) {
            return objectMapper.convertValue(values, targetClass);
        }
        RecordComponent[] components = targetClass.getRecordComponents();
        Class<?>[] parameterTypes = new Class<?>[components.length];
        Object[] args = new Object[components.length];
        for (int index = 0; index < components.length; index++) {
            RecordComponent component = components[index];
            parameterTypes[index] = component.getType();
            String key = recordComponentWireName(component);
            Object raw = values.containsKey(key) ? values.get(key) : values.get(component.getName());
            if (raw instanceof GenApiFilePart && component.getType().equals(GenApiFilePart.class)) {
                args[index] = raw;
            } else {
                args[index] = objectMapper.convertValue(raw, component.getType());
            }
        }
        try {
            Constructor<T> constructor = targetClass.getDeclaredConstructor(parameterTypes);
            constructor.setAccessible(true);
            return constructor.newInstance(args);
        } catch (ReflectiveOperationException error) {
            throw new IllegalArgumentException("invalid multipart request", error);
        }
    }

    private Map<String, Object> multipartValues(MultipartHttpServletRequest request) throws IOException {
        Map<String, Object> result = new LinkedHashMap<>();
        if (request == null) {
            return result;
        }
        request.getParameterMap().forEach((key, values) -> {
            if (values != null && values.length > 0) {
                result.put(key, values[0]);
            }
        });
        for (Map.Entry<String, MultipartFile> entry : request.getFileMap().entrySet()) {
            MultipartFile file = entry.getValue();
            if (file.getSize() > serverConfig.multipartSingleFileBytes()) {
                throw new PayloadTooLargeException("multipart file " + entry.getKey() + " exceeds configured limit");
            }
            result.put(entry.getKey(), GenApiFilePart.ofStream(file.getOriginalFilename(), file.getContentType(), file.getSize(), file.getInputStream()));
        }
        return result;
    }

    private String recordComponentWireName(RecordComponent component) {
        JsonProperty property = component.getAnnotation(JsonProperty.class);
        return property == null || property.value().isBlank() ? component.getName() : property.value();
    }

    private byte[] decodeBinarySchemaBody(byte[] body, String contentEncoding, HttpRequestInfo requestInfo) {
        String encoding = contentEncoding == null || contentEncoding.isBlank()
            ? "identity"
            : contentEncoding.trim().toLowerCase(Locale.ROOT);
        if (!requestInfo.binaryContentEncodings().contains(encoding)) {
            throw new UnsupportedContentEncodingException("unsupported binary Content-Encoding " + encoding);
        }
        if ("identity".equals(encoding)) {
            if (serverConfig.decompressedBinaryBodyBytes() > 0 && body.length > serverConfig.decompressedBinaryBodyBytes()) {
                throw new PayloadTooLargeException("binary request body exceeds configured limit");
            }
            return body;
        }
        byte[] decoded;
        if ("gzip".equals(encoding)) {
            try (GZIPInputStream input = new GZIPInputStream(new ByteArrayInputStream(body))) {
                decoded = readLimitedStream(input, serverConfig.decompressedBinaryBodyBytes());
            } catch (IOException error) {
                throw new IllegalArgumentException("invalid gzip request body", error);
            }
        } else {
            GenSpringServerConfig.BinaryContentDecoder decoder = serverConfig.binaryContentDecoders().get(encoding);
            if (decoder == null) {
                throw new UnsupportedContentEncodingException("unsupported binary Content-Encoding " + encoding);
            }
            try {
                decoded = decoder.decode(body);
            } catch (IOException error) {
                throw new IllegalArgumentException("invalid " + encoding + " request body", error);
            }
            if (decoded == null) {
                throw new IllegalArgumentException(encoding + " decoder returned null");
            }
            if (serverConfig.decompressedBinaryBodyBytes() > 0 && decoded.length > serverConfig.decompressedBinaryBodyBytes()) {
                throw new PayloadTooLargeException("decompressed binary request body exceeds configured limit");
            }
        }
        return decoded;
    }

    private byte[] readLimitedStream(InputStream input, long maxBytes) throws IOException {
        ByteArrayOutputStream output = new ByteArrayOutputStream();
        byte[] buffer = new byte[8192];
        long total = 0;
        while (true) {
            int read = input.read(buffer);
            if (read < 0) {
                break;
            }
            if (read == 0) {
                continue;
            }
            total += read;
            if (maxBytes > 0 && total > maxBytes) {
                throw new PayloadTooLargeException("decompressed binary request body exceeds configured limit");
            }
            output.write(buffer, 0, read);
        }
        return output.toByteArray();
    }

    private ResponseEntity<?> rawResponse(HttpResponseInfo responseInfo, Object result) throws IOException {
        if (result instanceof GenApiRawResponse raw) {
            ResponseEntity.BodyBuilder builder = rawResponseBuilder(responseInfo.kind(), raw.contentType(), raw.filename().isBlank() ? responseInfo.defaultFilename() : raw.filename());
            raw.headers().forEach(builder::header);
            return builder.body(raw.body());
        }
        if (result instanceof GenApiStreamResponse stream) {
            ResponseEntity.BodyBuilder builder = rawResponseBuilder(responseInfo.kind(), stream.contentType(), responseInfo.defaultFilename());
            stream.headers().forEach(builder::header);
            return builder.body(new InputStreamResource(stream.body()));
        }
        if (result instanceof GenApiBinaryBody binary) {
            return rawResponseBuilder(responseInfo.kind(), binary.contentType(), responseInfo.defaultFilename()).body(binary.toBytes());
        }
        if (result instanceof byte[] bytes) {
            return rawResponseBuilder(responseInfo.kind(), responseInfo.mediaType(), responseInfo.defaultFilename()).body(bytes);
        }
        if (result instanceof String text) {
            return rawResponseBuilder(responseInfo.kind(), responseInfo.mediaType(), responseInfo.defaultFilename()).body(text.getBytes(StandardCharsets.UTF_8));
        }
        byte[] bytes = result == null ? new byte[0] : objectMapper.writeValueAsBytes(result);
        return rawResponseBuilder(responseInfo.kind(), responseInfo.mediaType(), responseInfo.defaultFilename()).body(bytes);
    }

    private ResponseEntity<byte[]> rawBytesResponse(HttpResponseInfo responseInfo, byte[] body) {
        return rawResponseBuilder(responseInfo.kind(), responseInfo.mediaType(), responseInfo.defaultFilename()).body(body == null ? new byte[0] : body);
    }

    private ResponseEntity.BodyBuilder rawResponseBuilder(String kind, String mediaType, String filename) {
        ResponseEntity.BodyBuilder builder = ResponseEntity.ok().contentType(MediaType.parseMediaType(mediaType));
        if ("file".equals(kind) && filename != null && !filename.isBlank()) {
            builder.header(HttpHeaders.CONTENT_DISPOSITION, "attachment; filename=\"" + escapeHeader(asciiFilename(filename)) + "\"; filename*=UTF-8''" + encodeHeaderValue(filename));
        }
        return builder;
    }

    private String asciiFilename(String filename) {
        StringBuilder result = new StringBuilder();
        for (int index = 0; index < filename.length(); index++) {
            char current = filename.charAt(index);
            if (current >= 0x20 && current < 0x7f) {
                result.append(current);
            } else {
                result.append('_');
            }
        }
        String value = result.toString();
        return value.isBlank() ? "download" : value;
    }

    private String escapeHeader(String value) {
        return value.replace("\\", "\\\\").replace("\"", "\\\"");
    }

    private String encodeHeaderValue(String value) {
        return URLEncoder.encode(value, StandardCharsets.UTF_8).replace("+", "%20");
    }

    private ResponseEntity<Map<String, Object>> badRequestResponse(Exception error) {
        return ResponseEntity.status(HttpStatus.BAD_REQUEST).body(Map.of("detail", "invalid request"));
    }

    private ResponseEntity<Map<String, Object>> payloadTooLargeResponse(Exception error) {
        return ResponseEntity.status(HttpStatus.PAYLOAD_TOO_LARGE).body(Map.of("detail", "payload too large"));
    }

    private ResponseEntity<Map<String, Object>> unsupportedContentEncodingResponse(Exception error) {
        return ResponseEntity.status(HttpStatus.UNSUPPORTED_MEDIA_TYPE).body(Map.of("detail", "unsupported content encoding"));
    }

    private static final class PayloadTooLargeException extends RuntimeException {
        PayloadTooLargeException(String message) {
            super(message);
        }
    }

    private static final class UnsupportedContentEncodingException extends RuntimeException {
        UnsupportedContentEncodingException(String message) {
            super(message);
        }
    }

    private Object wrapApiErrorResponse(GenApiResponseEnvelope envelopeSpec, GenApiError error, String routeId) {
        GenApiErrorPayload payload = normalizeApiErrorPayload(error.payload(), routeId);
        if ("none".equals(envelopeSpec.kind())) {
            return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).body(payload);
        }
        Map<String, Object> envelope = new LinkedHashMap<>();
        if ("code_message_data".equals(envelopeSpec.kind())) {
            envelope.put(envelopeSpec.fields().code(), payload.code());
            envelope.put(envelopeSpec.fields().message(), payload.message());
            envelope.put(envelopeSpec.fields().data(), null);
            if (!"none".equals(envelopeSpec.errorIdentity())) {
                envelope.put(envelopeSpec.fields().error(), payload);
            }
            return envelope;
        }
        if ("ok_data_error".equals(envelopeSpec.kind())) {
            envelope.put(envelopeSpec.fields().ok(), false);
            envelope.put(envelopeSpec.fields().error(), payload);
            return envelope;
        }
        return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).body(payload);
    }

    private GenApiErrorPayload normalizeApiErrorPayload(GenApiErrorPayload payload, String routeId) {
        if (payload == null) {
            payload = new GenApiErrorPayload("", "", "", 0, "", new GenApiToastPayload("", "error", "", ""));
        }
        GenApiErrorEntry entry = GenApiErrors.lookup(payload, routeId).orElse(null);
        int code = payload.code() != 0 ? payload.code() : entry == null ? 0 : entry.code();
        String message = !payload.message().isBlank()
            ? payload.message()
            : entry == null ? "API error " + code : entry.message();
        GenApiToastPayload toast = payload.toast() == null
            ? new GenApiToastPayload("", "error", "", "")
            : payload.toast();
        return new GenApiErrorPayload(
            payload.id().isBlank() && entry != null ? entry.id() : payload.id(),
            payload.group().isBlank() && entry != null ? entry.group() : payload.group(),
            payload.key().isBlank() && entry != null ? entry.key() : payload.key(),
            code,
            message,
            new GenApiToastPayload(
                toast.key().isBlank() && entry != null ? entry.toast().key() : toast.key(),
                toast.level().isBlank() ? (entry == null ? "error" : entry.toast().level()) : toast.level(),
                toast.defaultMessage().isBlank()
                    ? (entry == null ? message : entry.toast().defaultMessage())
                    : toast.defaultMessage(),
                toast.text()
            )
        );
    }
}
