// Code generated by api-blueprint (Swift client); DO NOT EDIT.
import Foundation

open class GenDemoAPI {
    public let transport: APITransport

    public init(transport: APITransport) {
        self.transport = transport
    }

    public func abc(
        query: DemoAbcQuery? = nil,
        options: APIRequestOptions = APIRequestOptions()
    ) async throws -> ApiDemoA {
        let jsonBody: Any? = nil
        let formBody: [String: String?]? = nil
        let multipartBody: [String: Any?]? = nil
        let binaryBody: Data? = nil
        return try await transport.request(
            APIRequest<ApiDemoA>(
                routeID: "api.demo.get.abc",
                method: "GET",
                path: "/api/demo/abc",
                query: query?.toQueryItems() ?? [],
                options: options,
                json: jsonBody,
                form: formBody,
                multipart: multipartBody,
                binary: binaryBody,
                binaryContentType: nil,
                responseMediaType: "application/json",
                responseKind: "json",
                responseEnvelope: APIResponseEnvelope(name: "CodeMessageDataEnvelope", kind: "code_message_data", errorIdentity: "nested", successCode: 0, successMessage: "ok", fields: APIResponseEnvelopeFields(code: "code", message: "message", data: "data", error: "error", ok: "ok")),
                decode: { value in try apiDecodeValue(ApiDemoA.self, from: value) }
            )
        )
    }

    public func testPost(
        json: DemoTestPostJSON? = nil,
        options: APIRequestOptions = APIRequestOptions()
    ) async throws -> DemoTestPostResponse {
        let jsonBody: Any?
        if let json {
            jsonBody = try apiEncodeJSONObject(json)
        } else {
            jsonBody = nil
        }
        let formBody: [String: String?]? = nil
        let multipartBody: [String: Any?]? = nil
        let binaryBody: Data? = nil
        return try await transport.request(
            APIRequest<DemoTestPostResponse>(
                routeID: "api.demo.post.testpost",
                method: "POST",
                path: "/api/demo/test_post",
                query: [],
                options: options,
                json: jsonBody,
                form: formBody,
                multipart: multipartBody,
                binary: binaryBody,
                binaryContentType: nil,
                responseMediaType: "application/json",
                responseKind: "json",
                responseEnvelope: APIResponseEnvelope(name: "CodeMessageDataEnvelope", kind: "code_message_data", errorIdentity: "nested", successCode: 0, successMessage: "ok", fields: APIResponseEnvelopeFields(code: "code", message: "message", data: "data", error: "error", ok: "ok")),
                decode: { value in try apiDecodeValue(DemoTestPostResponse.self, from: value) }
            )
        )
    }

    public func formSubmit(
        form: DemoFormSubmitForm? = nil,
        options: APIRequestOptions = APIRequestOptions()
    ) async throws -> DemoFormSubmitResponse {
        let jsonBody: Any? = nil
        let formBody = try form?.toFormFields()
        let multipartBody: [String: Any?]? = nil
        let binaryBody: Data? = nil
        return try await transport.request(
            APIRequest<DemoFormSubmitResponse>(
                routeID: "api.demo.post.formsubmit",
                method: "POST",
                path: "/api/demo/form-submit",
                query: [],
                options: options,
                json: jsonBody,
                form: formBody,
                multipart: multipartBody,
                binary: binaryBody,
                binaryContentType: nil,
                responseMediaType: "application/json",
                responseKind: "json",
                responseEnvelope: APIResponseEnvelope(name: "CodeMessageDataEnvelope", kind: "code_message_data", errorIdentity: "nested", successCode: 0, successMessage: "ok", fields: APIResponseEnvelopeFields(code: "code", message: "message", data: "data", error: "error", ok: "ok")),
                decode: { value in try apiDecodeValue(DemoFormSubmitResponse.self, from: value) }
            )
        )
    }

    public func requestOptions(
        query: DemoRequestOptionsQuery? = nil,
        options: APIRequestOptions = APIRequestOptions()
    ) async throws -> RequestOptionsResponse {
        let jsonBody: Any? = nil
        let formBody: [String: String?]? = nil
        let multipartBody: [String: Any?]? = nil
        let binaryBody: Data? = nil
        return try await transport.request(
            APIRequest<RequestOptionsResponse>(
                routeID: "api.demo.get.requestoptions",
                method: "GET",
                path: "/api/demo/request-options",
                query: query?.toQueryItems() ?? [],
                options: options,
                json: jsonBody,
                form: formBody,
                multipart: multipartBody,
                binary: binaryBody,
                binaryContentType: nil,
                responseMediaType: "application/json",
                responseKind: "json",
                responseEnvelope: APIResponseEnvelope(name: "CodeMessageDataEnvelope", kind: "code_message_data", errorIdentity: "nested", successCode: 0, successMessage: "ok", fields: APIResponseEnvelopeFields(code: "code", message: "message", data: "data", error: "error", ok: "ok")),
                decode: { value in try apiDecodeValue(RequestOptionsResponse.self, from: value) }
            )
        )
    }

    public func putDemo(
        query: DemoPutDemoQuery? = nil,
        json: DemoPutDemoJSON? = nil,
        options: APIRequestOptions = APIRequestOptions()
    ) async throws -> DemoPutDemoResponse {
        let jsonBody: Any?
        if let json {
            jsonBody = try apiEncodeJSONObject(json)
        } else {
            jsonBody = nil
        }
        let formBody: [String: String?]? = nil
        let multipartBody: [String: Any?]? = nil
        let binaryBody: Data? = nil
        return try await transport.request(
            APIRequest<DemoPutDemoResponse>(
                routeID: "api.demo.put.z1put",
                method: "PUT",
                path: "/api/demo/1put",
                query: query?.toQueryItems() ?? [],
                options: options,
                json: jsonBody,
                form: formBody,
                multipart: multipartBody,
                binary: binaryBody,
                binaryContentType: nil,
                responseMediaType: "application/json",
                responseKind: "json",
                responseEnvelope: APIResponseEnvelope(name: "CodeMessageDataEnvelope", kind: "code_message_data", errorIdentity: "nested", successCode: 0, successMessage: "ok", fields: APIResponseEnvelopeFields(code: "code", message: "message", data: "data", error: "error", ok: "ok")),
                decode: { value in try apiDecodeValue(DemoPutDemoResponse.self, from: value) }
            )
        )
    }

    public func delete(
        query: DemoDeleteQuery? = nil,
        options: APIRequestOptions = APIRequestOptions()
    ) async throws -> String {
        let jsonBody: Any? = nil
        let formBody: [String: String?]? = nil
        let multipartBody: [String: Any?]? = nil
        let binaryBody: Data? = nil
        return try await transport.request(
            APIRequest<String>(
                routeID: "api.demo.delete.delete",
                method: "DELETE",
                path: "/api/demo/delete$",
                query: query?.toQueryItems() ?? [],
                options: options,
                json: jsonBody,
                form: formBody,
                multipart: multipartBody,
                binary: binaryBody,
                binaryContentType: nil,
                responseMediaType: "application/xml",
                responseKind: "xml",
                responseEnvelope: APIResponseEnvelope(name: "CodeMessageDataEnvelope", kind: "code_message_data", errorIdentity: "nested", successCode: 0, successMessage: "ok", fields: APIResponseEnvelopeFields(code: "code", message: "message", data: "data", error: "error", ok: "ok")),
                decode: { value in try apiDecodeString(value) }
            )
        )
    }

    public func subscribeSweepEvents(

        openPayload: SweepOpen? = nil,
        headers: [String: String] = [:]
    ) -> APIStreamBridge<SweepStreamMessage, ConnectionClose> {
        transport.openStream(
            APIStreamConnectOptions<SweepStreamMessage, ConnectionClose>(
                routeID: "api.demo.stream.sweepevents",
                connectionKind: "stream",
                path: "/api/demo/sweep-events",
                query: openPayload?.toQueryItems() ?? [],
                open: openPayload,
                headers: headers,
                decodeMessage: { value in try apiDecodeValue(SweepStreamMessage.self, from: value) },
                decodeClose: { value in try apiDecodeValue(ConnectionClose.self, from: value) }
            )
        )
    }

    public func openAssistantSession(

        openPayload: AssistantOpen? = nil,
        headers: [String: String] = [:],
        protocols: [String] = []
    ) -> APIChannelBridge<AssistantServerMessage, AssistantClientMessage, ConnectionClose> {
        transport.openChannel(
            APIChannelConnectOptions<AssistantServerMessage, AssistantClientMessage, ConnectionClose>(
                routeID: "api.demo.channel.assistantsession",
                connectionKind: "channel",
                path: "/api/demo/assistant-session",
                query: openPayload?.toQueryItems() ?? [],
                open: openPayload,
                headers: headers,
                protocols: protocols,
                delivery: "ordered",
                decodeMessage: { value in try apiDecodeValue(AssistantServerMessage.self, from: value) },
                encodeMessage: { message in try apiEncodeJSONObject(message) },
                decodeClose: { value in try apiDecodeValue(ConnectionClose.self, from: value) }
            )
        )
    }

    public func postDeprecated(
        json: DemoPostDeprecatedJSON? = nil,
        options: APIRequestOptions = APIRequestOptions()
    ) async throws -> DemoPostDeprecatedResponse {
        let jsonBody: Any?
        if let json {
            jsonBody = try apiEncodeJSONObject(json)
        } else {
            jsonBody = nil
        }
        let formBody: [String: String?]? = nil
        let multipartBody: [String: Any?]? = nil
        let binaryBody: Data? = nil
        return try await transport.request(
            APIRequest<DemoPostDeprecatedResponse>(
                routeID: "api.demo.post.postdeprecated",
                method: "POST",
                path: "/api/demo/post_deprecated",
                query: [],
                options: options,
                json: jsonBody,
                form: formBody,
                multipart: multipartBody,
                binary: binaryBody,
                binaryContentType: nil,
                responseMediaType: "application/json",
                responseKind: "json",
                responseEnvelope: APIResponseEnvelope(name: "CodeMessageDataEnvelope", kind: "code_message_data", errorIdentity: "nested", successCode: 0, successMessage: "ok", fields: APIResponseEnvelopeFields(code: "code", message: "message", data: "data", error: "error", ok: "ok")),
                decode: { value in try apiDecodeValue(DemoPostDeprecatedResponse.self, from: value) }
            )
        )
    }

    public func raw(
        options: APIRequestOptions = APIRequestOptions()
    ) async throws -> DemoRawResponse {
        let jsonBody: Any? = nil
        let formBody: [String: String?]? = nil
        let multipartBody: [String: Any?]? = nil
        let binaryBody: Data? = nil
        return try await transport.request(
            APIRequest<DemoRawResponse>(
                routeID: "api.demo.post.raw",
                method: "POST",
                path: "/api/demo/raw",
                query: [],
                options: options,
                json: jsonBody,
                form: formBody,
                multipart: multipartBody,
                binary: binaryBody,
                binaryContentType: nil,
                responseMediaType: "application/json",
                responseKind: "json",
                responseEnvelope: APIResponseEnvelope(name: "CodeMessageDataEnvelope", kind: "code_message_data", errorIdentity: "nested", successCode: 0, successMessage: "ok", fields: APIResponseEnvelopeFields(code: "code", message: "message", data: "data", error: "error", ok: "ok")),
                decode: { value in try apiDecodeValue(DemoRawResponse.self, from: value) }
            )
        )
    }

    public func mapModel(
        options: APIRequestOptions = APIRequestOptions()
    ) async throws -> DemoMapModelResponse {
        let jsonBody: Any? = nil
        let formBody: [String: String?]? = nil
        let multipartBody: [String: Any?]? = nil
        let binaryBody: Data? = nil
        return try await transport.request(
            APIRequest<DemoMapModelResponse>(
                routeID: "api.demo.post.mapmodel",
                method: "POST",
                path: "/api/demo/map_model",
                query: [],
                options: options,
                json: jsonBody,
                form: formBody,
                multipart: multipartBody,
                binary: binaryBody,
                binaryContentType: nil,
                responseMediaType: "application/json",
                responseKind: "json",
                responseEnvelope: APIResponseEnvelope(name: "CodeMessageDataEnvelope", kind: "code_message_data", errorIdentity: "nested", successCode: 0, successMessage: "ok", fields: APIResponseEnvelopeFields(code: "code", message: "message", data: "data", error: "error", ok: "ok")),
                decode: { value in try apiDecodeValue(DemoMapModelResponse.self, from: value) }
            )
        )
    }

    public func errorDemo(
        query: DemoErrorDemoQuery? = nil,
        options: APIRequestOptions = APIRequestOptions()
    ) async throws -> DemoErrorDemoResponse {
        let jsonBody: Any? = nil
        let formBody: [String: String?]? = nil
        let multipartBody: [String: Any?]? = nil
        let binaryBody: Data? = nil
        return try await transport.request(
            APIRequest<DemoErrorDemoResponse>(
                routeID: "api.demo.get.errordemo",
                method: "GET",
                path: "/api/demo/error-demo",
                query: query?.toQueryItems() ?? [],
                options: options,
                json: jsonBody,
                form: formBody,
                multipart: multipartBody,
                binary: binaryBody,
                binaryContentType: nil,
                responseMediaType: "application/json",
                responseKind: "json",
                responseEnvelope: APIResponseEnvelope(name: "CodeMessageDataEnvelope", kind: "code_message_data", errorIdentity: "nested", successCode: 0, successMessage: "ok", fields: APIResponseEnvelopeFields(code: "code", message: "message", data: "data", error: "error", ok: "ok")),
                decode: { value in try apiDecodeValue(DemoErrorDemoResponse.self, from: value) }
            )
        )
    }

}
