/* eslint-disable */
// Code generated by api-blueprint (TypeScript); DO NOT EDIT.
export * as Api from "../(root)/(wailsv3)";
export * as Demo from "../demo/(wailsv3)";
export * as Hello from "../hello/(wailsv3)";
export * as Shared from "../(shared)/(wailsv3)";

export * from "./factory";

