/* eslint-disable */
/* istanbul ignore file */
// Code generated by api-blueprint (TypeScript); DO NOT EDIT.

import type { ApiClientConfig } from "../(shared)/client";
import type { ApiClient } from "../(root)/(wailsv3)/client";
import { createClient as createApiClient } from "../(root)/(wailsv3)/client";
import type { DemoClient } from "../demo/(wailsv3)/client";
import { createClient as createDemoClient } from "../demo/(wailsv3)/client";
import type { HelloClient } from "../hello/(wailsv3)/client";
import { createClient as createHelloClient } from "../hello/(wailsv3)/client";


export interface GeneratedClients {
  apiClient: ApiClient;
  demoClient: DemoClient;
  helloClient: HelloClient;
}

export function createClients(config: ApiClientConfig = {}): GeneratedClients {
  return {
    apiClient: createApiClient(config),
    demoClient: createDemoClient(config),
    helloClient: createHelloClient(config),
  };
}
