// Code generated by api-blueprint; DO NOT EDIT.
package com.example.apiblueprint.api.routes.api.hello

import com.example.apiblueprint.api.runtime.*

import kotlinx.serialization.builtins.*

public open class GenHelloApi internal constructor(
    private val transport: ApiTransport,
) {

    public open suspend fun abc(
        query: HelloAbcQuery,
        headers: Map<String, String> = emptyMap(),
    ): HelloAbcResponse {
        val envelope = transport.request(
            ApiRequest(
                method = "GET",
                path = "/api/hello/abc",
                query = query.toQueryMap(),
                headers = headers,
                responseSerializer = GeneralResponse.serializer(MapSerializer(String.serializer(), ApiHelloMap.serializer())),
                responseMediaType = "application/json",
            )
        )
        if (envelope.code != 0) {
            throw ApiCodeError(envelope.code, envelope.message, envelope.toast)
        }
        return envelope.data ?: throw ApiException(200, "Missing response data for /api/hello/abc")
    }

    public open suspend fun mapEnum(
        headers: Map<String, String> = emptyMap(),
    ): HelloMapEnumResponse {
        val envelope = transport.request(
            ApiRequest(
                method = "GET",
                path = "/api/hello/map-enum",
                headers = headers,
                responseSerializer = GeneralResponse.serializer(MapSerializer(String.serializer(), ApiHelloMap.serializer())),
                responseMediaType = "application/json",
            )
        )
        if (envelope.code != 0) {
            throw ApiCodeError(envelope.code, envelope.message, envelope.toast)
        }
        return envelope.data ?: throw ApiException(200, "Missing response data for /api/hello/map-enum")
    }

    public open suspend fun listEnum(
        headers: Map<String, String> = emptyMap(),
    ): HelloListEnumResponse {
        val envelope = transport.request(
            ApiRequest(
                method = "GET",
                path = "/api/hello/list-enum",
                headers = headers,
                responseSerializer = GeneralResponse.serializer(ListSerializer(MapEnum.serializer())),
                responseMediaType = "application/json",
            )
        )
        if (envelope.code != 0) {
            throw ApiCodeError(envelope.code, envelope.message, envelope.toast)
        }
        return envelope.data ?: throw ApiException(200, "Missing response data for /api/hello/list-enum")
    }

    public open suspend fun string(
        headers: Map<String, String> = emptyMap(),
    ): HelloStringResponse {
        val envelope = transport.request(
            ApiRequest(
                method = "GET",
                path = "/api/hello/string",
                headers = headers,
                responseSerializer = GeneralResponse.serializer(String.serializer()),
                responseMediaType = "application/json",
            )
        )
        if (envelope.code != 0) {
            throw ApiCodeError(envelope.code, envelope.message, envelope.toast)
        }
        return envelope.data ?: throw ApiException(200, "Missing response data for /api/hello/string")
    }

    public open suspend fun uint64(
        headers: Map<String, String> = emptyMap(),
    ): HelloUint64Response {
        val envelope = transport.request(
            ApiRequest(
                method = "GET",
                path = "/api/hello/uint64",
                headers = headers,
                responseSerializer = GeneralResponse.serializer(Long.serializer()),
                responseMediaType = "application/json",
            )
        )
        if (envelope.code != 0) {
            throw ApiCodeError(envelope.code, envelope.message, envelope.toast)
        }
        return envelope.data ?: throw ApiException(200, "Missing response data for /api/hello/uint64")
    }

    public open suspend fun stringEmun(
        headers: Map<String, String> = emptyMap(),
    ): HelloStringEmunResponse {
        val envelope = transport.request(
            ApiRequest(
                method = "GET",
                path = "/api/hello/string-emun",
                headers = headers,
                responseSerializer = GeneralResponse.serializer(MapEnum.serializer()),
                responseMediaType = "application/json",
            )
        )
        if (envelope.code != 0) {
            throw ApiCodeError(envelope.code, envelope.message, envelope.toast)
        }
        return envelope.data ?: throw ApiException(200, "Missing response data for /api/hello/string-emun")
    }

    public open suspend fun helloWay(
        query: HelloHelloWayQuery,
        headers: Map<String, String> = emptyMap(),
    ): Unit {
        val envelope = transport.request(
            ApiRequest(
                method = "GET",
                path = "/api/hello/hello-way",
                query = query.toQueryMap(),
                headers = headers,
                responseSerializer = GeneralResponse.serializer(Unit.serializer()),
                responseMediaType = "application/json",
            )
        )
        if (envelope.code != 0) {
            throw ApiCodeError(envelope.code, envelope.message, envelope.toast)
        }
        return envelope.data ?: throw ApiException(200, "Missing response data for /api/hello/hello-way")
    }

    private fun HelloAbcQuery.toQueryMap(): Map<String, String?> = mapOf(
        "arg1" to arg1?.toString(),
        "arg3" to arg3?.toString(),
        "arg2" to arg2?.toString(),
        "type" to type.wireValue.toString()
    )

    private fun HelloHelloWayQuery.toQueryMap(): Map<String, String?> = mapOf(
        "arg1" to arg1?.wireValue?.toString()
    )
}
