// Code generated by api-blueprint (Go client); DO NOT EDIT.

package static

import (
	"context"
	runtime "example.com/project/golang/client/runtime"
)

type GenStaticClient struct {
	transport runtime.Transport
}

func NewGenStaticClient(transport runtime.Transport) *GenStaticClient {
	return &GenStaticClient{transport: transport}
}

func (client *GenStaticClient) DocJson(ctx context.Context) (*RSP_DocJson_BODY, error) {
	request := runtime.Request{
		Method:          "GET",
		Path:            "/static/doc.json",
		ResponseWrapper: "NoneWrapper",
	}
	var response RSP_DocJson_BODY
	if err := client.transport.Do(ctx, request, &response); err != nil {
		return nil, err
	}
	return &response, nil
}

func (client *GenStaticClient) Dochaha(ctx context.Context) (*RSP_Dochaha_BODY, error) {
	request := runtime.Request{
		Method:          "GET",
		Path:            "/static/dochaha",
		ResponseWrapper: "NoneWrapper",
	}
	var response RSP_Dochaha_BODY
	if err := client.transport.Do(ctx, request, &response); err != nil {
		return nil, err
	}
	return &response, nil
}
