// Code generated by api-blueprint (Golang HTTP adapter); DO NOT EDIT.

package httptransport

import (
	"context"
	"fmt"
	"net/http"
	"strings"

	"github.com/coder/websocket"
	"github.com/coder/websocket/wsjson"

	"github.com/gin-gonic/gin"

	provider "demo/views/provider"
)

const GinContextMetadataKey = "api-blueprint/http/gin-context"

type ginContextCarrier interface {
	ContextKind() provider.TransportKind
	Get(string) (any, bool)
}

func RequireGin(ctx ginContextCarrier) (*gin.Context, error) {
	value, ok := ctx.Get(GinContextMetadataKey)
	if !ok {
		return nil, fmt.Errorf("[httptransport] transport[%s] does not expose *gin.Context", ctx.ContextKind())
	}
	ginCtx, ok := value.(*gin.Context)
	if !ok || ginCtx == nil {
		return nil, fmt.Errorf("[httptransport] gin context metadata has unexpected type[%T]", value)
	}
	return ginCtx, nil
}

func makeHeaders(header http.Header) map[string]string {
	headers := make(map[string]string, len(header))
	for key, values := range header {
		if len(values) == 0 {
			continue
		}
		headers[key] = values[0]
	}
	return headers
}

func bindRequest[Q, B, P any](
	ginCtx *gin.Context,
	reqProvider *provider.ReqProvider[Q, B, P],
) (*provider.REQ[Q, B], error) {
	var reqQ *Q
	var reqB *B
	if reqProvider == nil {
		return &provider.REQ[Q, B]{}, nil
	}

	if reqProvider.BindQuery {
		reqQ = new(Q)
		if err := ginCtx.ShouldBindQuery(reqQ); err != nil {
			return nil, err
		}
	}
	if reqProvider.BindJSON {
		reqB = new(B)
		if err := ginCtx.ShouldBindJSON(reqB); err != nil {
			return nil, err
		}
	} else if reqProvider.BindForm {
		reqB = new(B)
		if err := ginCtx.ShouldBind(reqB); err != nil {
			return nil, err
		}
	}

	return &provider.REQ[Q, B]{
		Q: reqQ,
		B: reqB,
	}, nil
}

func newContext[Q, B, P any](ginCtx *gin.Context, executor *provider.RouteExecutor[Q, B, P]) *provider.Context[Q, B, P] {
	ctx := provider.NewHTTPContext[Q, B, P](
		ginCtx.Request.Context(),
		makeHeaders(ginCtx.Request.Header),
		map[string]any{GinContextMetadataKey: ginCtx},
	)
	req, err := bindRequest(ginCtx, executor.Indexer.Req)
	ctx.Req = &provider.ReqContext[Q, B, P]{
		Request: req,
		Error:   err,
	}
	return ctx
}

func writeResponse[Q, B, P any](
	ginCtx *gin.Context,
	rspProvider *provider.RspProvider[Q, B, P],
	response *P,
	err error,
) {
	if ginCtx.Writer.Written() {
		return
	}
	if rspProvider == nil {
		if err != nil {
			_ = ginCtx.AbortWithError(http.StatusInternalServerError, err)
			return
		}
		ginCtx.JSON(http.StatusOK, response)
		return
	}

	switch rspProvider.Type {
	case "json":
		code, payload := provider.NewRSP_JSON(rspProvider, response, err)
		if code == 0 {
			code = http.StatusOK
		}
		ginCtx.JSON(code, payload)
	case "xml":
		code, payload := provider.NewRSP_XML(rspProvider, response, err)
		if code == 0 {
			code = http.StatusOK
		}
		ginCtx.XML(code, payload)
	default:
		if err != nil {
			_ = ginCtx.AbortWithError(http.StatusInternalServerError, err)
			return
		}
		if response == nil {
			ginCtx.String(http.StatusOK, "")
			return
		}
		ginCtx.String(http.StatusOK, fmt.Sprint(*response))
	}
}

func makeHandler[Q, B, P any](
	handler func(c *provider.Context[Q, B, P], req *provider.REQ[Q, B]) (rsp *P, err error),
	provSeq string,
) gin.HandlerFunc {
	executor := provider.NewRouteExecutor[Q, B, P](provSeq, handler)
	return func(ginCtx *gin.Context) {
		ctx := newContext(ginCtx, executor)
		execErr := executor.Run(ctx)
		response, invokeErr := ctx.HandleResult()
		if invokeErr == nil {
			invokeErr = execErr
		}
		writeResponse(ginCtx, executor.Indexer.Rsp, response, invokeErr)
	}
}

func GET[Q, B, P any](
	relativePath string,
	handler func(c *provider.Context[Q, B, P], req *provider.REQ[Q, B]) (rsp *P, err error),
	engine *gin.Engine,
	provSeq string,
) {
	engine.GET(relativePath, makeHandler[Q, B, P](handler, provSeq))
}

func POST[Q, B, P any](
	relativePath string,
	handler func(c *provider.Context[Q, B, P], req *provider.REQ[Q, B]) (rsp *P, err error),
	engine *gin.Engine,
	provSeq string,
) {
	engine.POST(relativePath, makeHandler[Q, B, P](handler, provSeq))
}

func PUT[Q, B, P any](
	relativePath string,
	handler func(c *provider.Context[Q, B, P], req *provider.REQ[Q, B]) (rsp *P, err error),
	engine *gin.Engine,
	provSeq string,
) {
	engine.PUT(relativePath, makeHandler[Q, B, P](handler, provSeq))
}

func DELETE[Q, B, P any](
	relativePath string,
	handler func(c *provider.Context[Q, B, P], req *provider.REQ[Q, B]) (rsp *P, err error),
	engine *gin.Engine,
	provSeq string,
) {
	engine.DELETE(relativePath, makeHandler[Q, B, P](handler, provSeq))
}

type HTTPWebSocketConnection struct {
	conn *websocket.Conn
}

func NewHTTPWebSocketConnection(conn *websocket.Conn) *HTTPWebSocketConnection {
	return &HTTPWebSocketConnection{conn: conn}
}

func (conn *HTTPWebSocketConnection) Transport() provider.TransportKind {
	return provider.TransportHTTP
}

func (conn *HTTPWebSocketConnection) SessionID() string {
	return ""
}

func (conn *HTTPWebSocketConnection) Subprotocol() string {
	if conn == nil || conn.conn == nil {
		return ""
	}
	return conn.conn.Subprotocol()
}

func (conn *HTTPWebSocketConnection) Underlying() any {
	if conn == nil {
		return nil
	}
	return conn.conn
}

func (conn *HTTPWebSocketConnection) ReadJSON(ctx context.Context, target any) error {
	if conn == nil || conn.conn == nil {
		return nil
	}
	return wsjson.Read(ctx, conn.conn, target)
}

func (conn *HTTPWebSocketConnection) WriteJSON(ctx context.Context, payload any) error {
	if conn == nil || conn.conn == nil {
		return nil
	}
	return wsjson.Write(ctx, conn.conn, payload)
}

func (conn *HTTPWebSocketConnection) Close(code int, reason string) error {
	if conn == nil || conn.conn == nil {
		return nil
	}
	return conn.conn.Close(websocket.StatusCode(code), reason)
}

func wsProvider[Q, B, P any](executor *provider.RouteExecutor[Q, B, P]) *provider.WsHandleProvider[Q, B, P] {
	for _, prov := range executor.Providers {
		typed, ok := prov.(*provider.WsHandleProvider[Q, B, P])
		if ok {
			return typed
		}
	}
	return nil
}

func makeWSHandler[Q, B, P any](
	handler func(c *provider.Context[Q, B, P], req *provider.REQ[Q, B]) (rsp *P, err error),
	provSeq string,
) gin.HandlerFunc {
	executor := provider.NewRouteExecutor[Q, B, P](provSeq, handler)
	wsProv := wsProvider(executor)
	return func(ginCtx *gin.Context) {
		ctx := newContext(ginCtx, executor)
		if err := executor.RunWSPreflight(ctx); err != nil {
			_ = ginCtx.AbortWithError(http.StatusBadRequest, err)
			return
		}
		if ctx.Req != nil && ctx.Req.Error != nil {
			_ = ginCtx.AbortWithError(http.StatusBadRequest, ctx.Req.Error)
			return
		}

		var subprotocols []string
		if wsProv != nil {
			for _, sub := range wsProv.Subs {
				if trimmed := strings.TrimSpace(sub); trimmed != "" {
					subprotocols = append(subprotocols, trimmed)
				}
			}
		}
		conn, err := websocket.Accept(ginCtx.Writer, ginCtx.Request, &websocket.AcceptOptions{
			Subprotocols:    subprotocols,
			CompressionMode: websocket.CompressionContextTakeover,
		})
		if err != nil {
			_ = ginCtx.AbortWithError(http.StatusBadRequest, err)
			return
		}
		if len(subprotocols) > 0 && conn.Subprotocol() == "" {
			_ = conn.Close(websocket.StatusPolicyViolation, "subprotocol required")
			return
		}
		defer conn.CloseNow()

		ctx.WsHandle = &provider.WsHandleContext[Q, B, P]{
			Conn: NewHTTPWebSocketConnection(conn),
		}
		if err := executor.RunWSHandler(ctx); err != nil {
			_ = ctx.WsHandle.Conn.Close(int(websocket.StatusInternalError), err.Error())
		}
	}
}

func WS[Q, B, P any](
	relativePath string,
	handler func(c *provider.Context[Q, B, P], req *provider.REQ[Q, B]) (rsp *P, err error),
	engine *gin.Engine,
	provSeq string,
) {
	engine.GET(relativePath, makeWSHandler[Q, B, P](handler, provSeq))
}
