// Code generated by api-blueprint (Wails V2); DO NOT EDIT.

package wailsv2

import (
	sharedroutes "demo/views/static"

	runtime "demo/views/_wailsv2/runtime"
)

type RouterInterface = sharedroutes.RouterInterface

type REQ_DocJson = sharedroutes.REQ_DocJson
type RSP_DocJson = sharedroutes.RSP_DocJson
type CTX_DocJson = sharedroutes.CTX_DocJson
type INVOKE_DocJson = runtime.InvokeEnvelope[any, any]

type REQ_Dochaha = sharedroutes.REQ_Dochaha
type RSP_Dochaha = sharedroutes.RSP_Dochaha
type CTX_Dochaha = sharedroutes.CTX_Dochaha
type INVOKE_Dochaha = runtime.InvokeEnvelope[any, any]
