# Code generated by api-blueprint (Python server); DO NOT EDIT.
from __future__ import annotations

from pathlib import Path
from typing import Any, AsyncIterable, Iterable, Protocol

from ...runtime.server import ApiRawResponse, ApiServerChannel, ApiServerStream

from .gen_types import (
    DocJsonResponse,
    DochahaResponse,
)


class StaticService(Protocol):
    async def doc_json(self) -> DocJsonResponse:
        ...

    async def dochaha(self) -> DochahaResponse:
        ...


class StaticServiceStub:
    async def doc_json(self) -> DocJsonResponse:
        raise NotImplementedError("doc_json")

    async def dochaha(self) -> DochahaResponse:
        raise NotImplementedError("dochaha")
