/* eslint-disable */
/* istanbul ignore file */
// Code generated by api-blueprint (TypeScript); DO NOT EDIT.

import type * as Models from "./models";
import type * as Shared from "../../../runtime/models";
import { ApiChannelBridge, ApiClientConfig, ApiSocketBridge, ApiStreamBridge, BaseClient } from "../../../runtime/client";

import type { ApiBinaryBody } from "../../../runtime/binary/index";
import * as Binary from "./binary";


export class BinaryClient extends BaseClient {
  constructor(config: ApiClientConfig = {}) {
    super(config);
  }


  /**
   * Binary packet example

   * Tags: api
   */

  async packet(
    request: {
      query?: Models.ReqPacketQuery;
      binary: Binary.DemoPacket;
      headers?: Record<string, string>;
    },
    init?: RequestInit,
    timeoutMs?: number,
  ): Promise<Models.RspPacket>;

  async packet(
    request: {
      query?: Models.ReqPacketQuery;
      binary: ApiBinaryBody;
      headers?: Record<string, string>;
    },
    init?: RequestInit,
    timeoutMs?: number,
  ): Promise<Models.RspPacket>;


  async packet(
    request: {
      query?: Models.ReqPacketQuery;
      binary: Binary.DemoPacket | ApiBinaryBody;
      headers?: Record<string, string>;
    },
    init: RequestInit = {},
    timeoutMs?: number,
  ): Promise<Models.RspPacket> {
    return this.request<Models.RspPacket>({
      method: "POST",
      path: "/api/binary/packet",
      service: "BinaryService",
      operation: "Packet",
      namespace: "binary",
      query: request.query as unknown as Record<string, unknown> | undefined,
      binary: Binary.DemoPacketWire.toBinaryBody(request.binary),
      headers: request.headers,
      init,
      responseType: "json",
      timeoutMs,
    });
  }

}
