/* eslint-disable */
/* istanbul ignore file */
// Code generated by api-blueprint (TypeScript client); DO NOT EDIT.
export {};

// Route Contracts

export interface AuditPacketQuery {
  /** trace id */
  trace?: string;
}

export interface AuditPacketResponse {
  /** trace id */
  trace: string;
  /** item count */
  item_count: number;
  /** checksum */
  checksum: number;
}

export interface PacketQuery {
  /** trace id */
  trace?: string;
}

export interface PacketResponse {
  /** trace id */
  trace: string;
  /** packet version */
  version: number;
  /** item count */
  item_count: number;
  /** payload */
  payload: string;
  /** score sum */
  score_sum: number;
  /** first item label */
  first_label: string;
  /** item ids */
  item_ids: Array<number>;
  /** checksum */
  checksum: number;
}
