/* eslint-disable */
/* istanbul ignore file */
// Code generated by api-blueprint (TypeScript); DO NOT EDIT.

import type {
  GeneralWrapper,
} from "../../../runtime/models";

// Route Contracts

export interface ReqPacketQuery {
  /** trace id */
  trace?: string;
}

export type RspPacket = GeneralWrapper<RspPacketJson>;

export interface RspPacketJson {
  /** trace id */
  trace: string;
  /** packet version */
  version: number;
  /** item count */
  item_count: number;
  /** payload */
  payload: string;
  /** score sum */
  score_sum: number;
  /** first item label */
  first_label: string;
  /** item ids */
  item_ids: Array<number>;
  /** checksum */
  checksum: number;
}

