// Code generated by api-blueprint (Kotlin server); DO NOT EDIT.
package com.example.apiblueprint.api.routes.api.media

import com.example.apiblueprint.api.runtime.*

public open class MediaServiceStub : GenMediaService {

    public override suspend fun mediaPreview(
        multipart: MediaPreviewRequest
    ): ApiRawResponse {
        throw NotImplementedError("api.media.post.preview is not implemented")
    }

    public override suspend fun mediaFrame(
    ): ApiRawResponse {
        throw NotImplementedError("api.media.get.frame is not implemented")
    }

    public override suspend fun mediaDownload(
    ): ApiRawResponse {
        throw NotImplementedError("api.media.get.download is not implemented")
    }

    public override suspend fun mediaDownloadDynamic(
    ): ApiRawResponse {
        throw NotImplementedError("api.media.get.downloaddynamic is not implemented")
    }

    public override suspend fun mediaDownloadFilenameEdge(
    ): ApiRawResponse {
        throw NotImplementedError("api.media.get.downloadfilenameedge is not implemented")
    }

    public override suspend fun mediaErrorFrame(
        query: MediaMediaErrorFrameQuery
    ): ApiRawResponse {
        throw NotImplementedError("api.media.get.errorframe is not implemented")
    }

    public override suspend fun mediaMjpeg(
    ): ApiStreamResponse {
        throw NotImplementedError("api.media.get.mjpeg is not implemented")
    }

}
