// Code generated by api-blueprint; DO NOT EDIT.
package com.example.apiblueprint.api.routes.api.demo

import com.example.apiblueprint.api.runtime.*
import kotlinx.serialization.builtins.*

public open class GenDemoApi internal constructor(
    private val transport: ApiTransport,
) {

    public open suspend fun abc(
        query: DemoAbcQuery,
        headers: Map<String, String> = emptyMap(),
    ): GeneralResponse<ApiDemoA> {
        return transport.request(
            ApiRequest(
                method = "GET",
                path = "/api/demo/abc",
                query = query.toQueryMap(),
                headers = headers,
                responseSerializer = GeneralResponse.serializer(ApiDemoA.serializer()),
                responseMediaType = "application/json",
            )
        )
    }

    public open suspend fun testPost(
        json: DemoTestPostJson,
        headers: Map<String, String> = emptyMap(),
    ): GeneralResponse<DemoTestPostResponse> {
        return transport.request(
            ApiRequest(
                method = "POST",
                path = "/api/demo/test_post",
                headers = headers,
                json = json,
                jsonSerializer = DemoTestPostJson.serializer(),
                responseSerializer = GeneralResponse.serializer(DemoTestPostResponse.serializer()),
                responseMediaType = "application/json",
            )
        )
    }

    public open suspend fun func1put(
        query: DemoFunc1putQuery,
        json: DemoFunc1putJson,
        headers: Map<String, String> = emptyMap(),
    ): GeneralResponse<DemoFunc1putResponse> {
        return transport.request(
            ApiRequest(
                method = "PUT",
                path = "/api/demo/1put",
                query = query.toQueryMap(),
                headers = headers,
                json = json,
                jsonSerializer = DemoFunc1putJson.serializer(),
                responseSerializer = GeneralResponse.serializer(DemoFunc1putResponse.serializer()),
                responseMediaType = "application/json",
            )
        )
    }

    public open suspend fun postDeprecated(
        json: DemoPostDeprecatedJson,
        headers: Map<String, String> = emptyMap(),
    ): GeneralResponse<DemoPostDeprecatedResponse> {
        return transport.request(
            ApiRequest(
                method = "POST",
                path = "/api/demo/post_deprecated",
                headers = headers,
                json = json,
                jsonSerializer = DemoPostDeprecatedJson.serializer(),
                responseSerializer = GeneralResponse.serializer(DemoPostDeprecatedResponse.serializer()),
                responseMediaType = "application/json",
            )
        )
    }

    public open suspend fun raw(
        headers: Map<String, String> = emptyMap(),
    ): GeneralResponse<DemoRawResponse> {
        return transport.request(
            ApiRequest(
                method = "POST",
                path = "/api/demo/raw",
                headers = headers,
                responseSerializer = GeneralResponse.serializer(DemoRawResponse.serializer()),
                responseMediaType = "application/json",
            )
        )
    }

    public open suspend fun mapModel(
        headers: Map<String, String> = emptyMap(),
    ): GeneralResponse<DemoMapModelResponse> {
        return transport.request(
            ApiRequest(
                method = "POST",
                path = "/api/demo/map_model",
                headers = headers,
                responseSerializer = GeneralResponse.serializer(MapSerializer(Int.serializer(), ApiDemoMap.serializer())),
                responseMediaType = "application/json",
            )
        )
    }

    private fun DemoAbcQuery.toQueryMap(): Map<String, String?> = mapOf(
        "arg1" to arg1?.toString(),
        "arg3" to arg3?.toString(),
        "arg2" to arg2?.toString()
    )

    private fun DemoFunc1putQuery.toQueryMap(): Map<String, String?> = mapOf(
        "arg1" to arg1?.toString(),
        "arg2" to arg2?.toString(),
        "arg3" to arg3?.toString()
    )
}
