# Code generated by api-blueprint (Python server); DO NOT EDIT.
from __future__ import annotations

from pathlib import Path
from typing import Any, AsyncIterable, Iterable, Protocol

from ....runtime.server import ApiRawResponse, ApiServerChannel, ApiServerStream

from .gen_types import (
    PacketQuery,
    PacketResponse,
    AuditPacketQuery,
    AuditPacketResponse,
    WidePacketQuery,
    WidePacketResponse,
    DemoPacket,
    AuditPacket,
    WidePacket,
)


class BinaryService(Protocol):
    async def packet(
        self,
        query: PacketQuery,
        binary: DemoPacket,
    ) -> PacketResponse:
        ...

    async def audit_packet(
        self,
        query: AuditPacketQuery,
        binary: AuditPacket,
    ) -> AuditPacketResponse:
        ...

    async def wide_packet(
        self,
        query: WidePacketQuery,
        binary: WidePacket,
    ) -> WidePacketResponse:
        ...

    async def audit_packet_response(self) -> AuditPacket:
        ...


class BinaryServiceStub:
    async def packet(
        self,
        query: PacketQuery,
        binary: DemoPacket,
    ) -> PacketResponse:
        raise NotImplementedError("packet")

    async def audit_packet(
        self,
        query: AuditPacketQuery,
        binary: AuditPacket,
    ) -> AuditPacketResponse:
        raise NotImplementedError("audit_packet")

    async def wide_packet(
        self,
        query: WidePacketQuery,
        binary: WidePacket,
    ) -> WidePacketResponse:
        raise NotImplementedError("wide_packet")

    async def audit_packet_response(self) -> AuditPacket:
        raise NotImplementedError("audit_packet_response")
