// Code generated by api-blueprint (Kotlin server); DO NOT EDIT.
package com.example.apiblueprint.alt.runtime

import kotlinx.serialization.builtins.*
import kotlinx.serialization.KSerializer
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.SerializationException
import kotlinx.serialization.descriptors.PrimitiveKind
import kotlinx.serialization.descriptors.PrimitiveSerialDescriptor
import kotlinx.serialization.descriptors.SerialDescriptor
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder

@Serializable
public data class ConflictModel(
    public val default: String,
    @SerialName("class_")
    public val `class`: String,
    public val enum: KeywordEnum
)

@Serializable
public enum class KeywordEnum(public val wireValue: String) {
    @SerialName("default")
    DEFAULT("default"),
    @SerialName("class")
    CLASS("class")
}
