// Code generated by api-blueprint (Go client); DO NOT EDIT.

package runtime

const (
	CommonErrUnknown     ApiErrorCode = -1
	CommonErrTokenExpire ApiErrorCode = 55555
)

var ErrorCatalogByID = map[string]ErrorCatalogEntry{
	"CommonErr.UNKNOWN": {
		ID:      "CommonErr.UNKNOWN",
		Group:   "CommonErr",
		Key:     "UNKNOWN",
		Code:    CommonErrUnknown,
		Message: "未知错误",
		Toast: ApiToastSpec{
			Key:     "CommonErr.UNKNOWN",
			Level:   "error",
			Default: "未知错误",
		},
	},
	"CommonErr.TOKEN_EXPIRE": {
		ID:      "CommonErr.TOKEN_EXPIRE",
		Group:   "CommonErr",
		Key:     "TOKEN_EXPIRE",
		Code:    CommonErrTokenExpire,
		Message: "token登录态失效",
		Toast: ApiToastSpec{
			Key:     "auth.token_expire",
			Level:   "warning",
			Default: "登录状态已失效，请重新登录",
		},
	},
}

var ERROR_CATALOG = ErrorCatalogByID

func LookupApiErrorByID(id string) (ErrorCatalogEntry, bool) {
	entry, ok := ErrorCatalogByID[id]
	return entry, ok
}

func LookupApiErrorByCode(code ApiErrorCode) (ErrorCatalogEntry, bool) {
	for _, entry := range ErrorCatalogByID {
		if entry.Code == code {
			return entry, true
		}
	}
	return ErrorCatalogEntry{}, false
}
