# Code generated by api-blueprint (Python server); DO NOT EDIT.
from __future__ import annotations

from .gen_errors import ApiErrorEntry, ApiErrorCode, ApiErrorPayload, ApiToastPayload, ApiToastSpec


API_ERRORS_BY_ID: dict[str, ApiErrorEntry] = {
    "CommonErr.UNKNOWN": ApiErrorEntry(
        id="CommonErr.UNKNOWN",
        group="CommonErr",
        key="UNKNOWN",
        code=-1,
        message="未知错误",
        toast=ApiToastSpec(
            key="CommonErr.UNKNOWN",
            level="error",
            default="未知错误",
        ),
    ),
    "CommonErr.TOKEN_EXPIRE": ApiErrorEntry(
        id="CommonErr.TOKEN_EXPIRE",
        group="CommonErr",
        key="TOKEN_EXPIRE",
        code=55555,
        message="token登录态失效",
        toast=ApiToastSpec(
            key="auth.token_expire",
            level="warning",
            default="登录状态已失效，请重新登录",
        ),
    ),
    "DemoErr.UNKNOWN": ApiErrorEntry(
        id="DemoErr.UNKNOWN",
        group="DemoErr",
        key="UNKNOWN",
        code=70002,
        message="demo unknown error",
        toast=ApiToastSpec(
            key="DemoErr.UNKNOWN",
            level="error",
            default="demo unknown error",
        ),
    ),
    "DemoErr.RATE_LIMITED": ApiErrorEntry(
        id="DemoErr.RATE_LIMITED",
        group="DemoErr",
        key="RATE_LIMITED",
        code=42901,
        message="请求过于频繁",
        toast=ApiToastSpec(
            key="demo.rate_limited",
            level="warning",
            default="请求过于频繁，请稍后再试",
        ),
    ),
}

ROUTE_API_ERRORS_BY_CODE: dict[str, dict[int, ApiErrorEntry]] = {
    "api.api.channel.ws": {
        -1: API_ERRORS_BY_ID["CommonErr.UNKNOWN"],
        55555: API_ERRORS_BY_ID["CommonErr.TOKEN_EXPIRE"],
    },
    "api.binary.post.packet": {
        -1: API_ERRORS_BY_ID["CommonErr.UNKNOWN"],
        55555: API_ERRORS_BY_ID["CommonErr.TOKEN_EXPIRE"],
    },
    "api.binary.post.auditpacket": {
        -1: API_ERRORS_BY_ID["CommonErr.UNKNOWN"],
        55555: API_ERRORS_BY_ID["CommonErr.TOKEN_EXPIRE"],
    },
    "api.binary.post.widepacket": {
        -1: API_ERRORS_BY_ID["CommonErr.UNKNOWN"],
        55555: API_ERRORS_BY_ID["CommonErr.TOKEN_EXPIRE"],
    },
    "api.binary.get.auditpacketresponse": {
        -1: API_ERRORS_BY_ID["CommonErr.UNKNOWN"],
        55555: API_ERRORS_BY_ID["CommonErr.TOKEN_EXPIRE"],
    },
    "api.conflict.get.default": {
        -1: API_ERRORS_BY_ID["CommonErr.UNKNOWN"],
        55555: API_ERRORS_BY_ID["CommonErr.TOKEN_EXPIRE"],
    },
    "api.demo.get.abc": {
        -1: API_ERRORS_BY_ID["CommonErr.UNKNOWN"],
        55555: API_ERRORS_BY_ID["CommonErr.TOKEN_EXPIRE"],
    },
    "api.demo.post.testpost": {
        -1: API_ERRORS_BY_ID["CommonErr.UNKNOWN"],
        55555: API_ERRORS_BY_ID["CommonErr.TOKEN_EXPIRE"],
    },
    "api.demo.post.formsubmit": {
        -1: API_ERRORS_BY_ID["CommonErr.UNKNOWN"],
        55555: API_ERRORS_BY_ID["CommonErr.TOKEN_EXPIRE"],
    },
    "api.demo.get.requestoptions": {
        -1: API_ERRORS_BY_ID["CommonErr.UNKNOWN"],
        55555: API_ERRORS_BY_ID["CommonErr.TOKEN_EXPIRE"],
    },
    "api.demo.get.pathecho_item_badge": {
        -1: API_ERRORS_BY_ID["CommonErr.UNKNOWN"],
        55555: API_ERRORS_BY_ID["CommonErr.TOKEN_EXPIRE"],
    },
    "api.demo.post.emptyresponse": {
        -1: API_ERRORS_BY_ID["CommonErr.UNKNOWN"],
        55555: API_ERRORS_BY_ID["CommonErr.TOKEN_EXPIRE"],
    },
    "api.demo.put.z1put": {
        -1: API_ERRORS_BY_ID["CommonErr.UNKNOWN"],
        55555: API_ERRORS_BY_ID["CommonErr.TOKEN_EXPIRE"],
    },
    "api.demo.delete.delete": {
        -1: API_ERRORS_BY_ID["CommonErr.UNKNOWN"],
        55555: API_ERRORS_BY_ID["CommonErr.TOKEN_EXPIRE"],
    },
    "api.demo.stream.sweepevents": {
        -1: API_ERRORS_BY_ID["CommonErr.UNKNOWN"],
        55555: API_ERRORS_BY_ID["CommonErr.TOKEN_EXPIRE"],
    },
    "api.demo.channel.assistantsession": {
        -1: API_ERRORS_BY_ID["CommonErr.UNKNOWN"],
        55555: API_ERRORS_BY_ID["CommonErr.TOKEN_EXPIRE"],
    },
    "api.demo.post.postdeprecated": {
        -1: API_ERRORS_BY_ID["CommonErr.UNKNOWN"],
        55555: API_ERRORS_BY_ID["CommonErr.TOKEN_EXPIRE"],
    },
    "api.demo.post.raw": {
        -1: API_ERRORS_BY_ID["CommonErr.UNKNOWN"],
        55555: API_ERRORS_BY_ID["CommonErr.TOKEN_EXPIRE"],
    },
    "api.demo.post.mapmodel": {
        -1: API_ERRORS_BY_ID["CommonErr.UNKNOWN"],
        55555: API_ERRORS_BY_ID["CommonErr.TOKEN_EXPIRE"],
    },
    "api.demo.get.errordemo": {
        -1: API_ERRORS_BY_ID["CommonErr.UNKNOWN"],
        55555: API_ERRORS_BY_ID["CommonErr.TOKEN_EXPIRE"],
        70002: API_ERRORS_BY_ID["DemoErr.UNKNOWN"],
        42901: API_ERRORS_BY_ID["DemoErr.RATE_LIMITED"],
    },
    "api.media.post.preview": {
        -1: API_ERRORS_BY_ID["CommonErr.UNKNOWN"],
        55555: API_ERRORS_BY_ID["CommonErr.TOKEN_EXPIRE"],
    },
    "api.media.get.frame": {
        -1: API_ERRORS_BY_ID["CommonErr.UNKNOWN"],
        55555: API_ERRORS_BY_ID["CommonErr.TOKEN_EXPIRE"],
    },
    "api.media.get.download": {
        -1: API_ERRORS_BY_ID["CommonErr.UNKNOWN"],
        55555: API_ERRORS_BY_ID["CommonErr.TOKEN_EXPIRE"],
    },
    "api.media.get.downloaddynamic": {
        -1: API_ERRORS_BY_ID["CommonErr.UNKNOWN"],
        55555: API_ERRORS_BY_ID["CommonErr.TOKEN_EXPIRE"],
    },
    "api.media.get.downloadfilenameedge": {
        -1: API_ERRORS_BY_ID["CommonErr.UNKNOWN"],
        55555: API_ERRORS_BY_ID["CommonErr.TOKEN_EXPIRE"],
    },
    "api.media.get.errorframe": {
        -1: API_ERRORS_BY_ID["CommonErr.UNKNOWN"],
        55555: API_ERRORS_BY_ID["CommonErr.TOKEN_EXPIRE"],
        70002: API_ERRORS_BY_ID["DemoErr.UNKNOWN"],
        42901: API_ERRORS_BY_ID["DemoErr.RATE_LIMITED"],
    },
    "api.media.get.mjpeg": {
        -1: API_ERRORS_BY_ID["CommonErr.UNKNOWN"],
        55555: API_ERRORS_BY_ID["CommonErr.TOKEN_EXPIRE"],
    },
    "api.hello.get.abc": {
        -1: API_ERRORS_BY_ID["CommonErr.UNKNOWN"],
        55555: API_ERRORS_BY_ID["CommonErr.TOKEN_EXPIRE"],
    },
    "api.hello.get.mapenum": {
        -1: API_ERRORS_BY_ID["CommonErr.UNKNOWN"],
        55555: API_ERRORS_BY_ID["CommonErr.TOKEN_EXPIRE"],
    },
    "api.hello.get.listenum": {
        -1: API_ERRORS_BY_ID["CommonErr.UNKNOWN"],
        55555: API_ERRORS_BY_ID["CommonErr.TOKEN_EXPIRE"],
    },
    "api.hello.get.string": {
        -1: API_ERRORS_BY_ID["CommonErr.UNKNOWN"],
        55555: API_ERRORS_BY_ID["CommonErr.TOKEN_EXPIRE"],
    },
    "api.hello.get.uint64": {
        -1: API_ERRORS_BY_ID["CommonErr.UNKNOWN"],
        55555: API_ERRORS_BY_ID["CommonErr.TOKEN_EXPIRE"],
    },
    "api.hello.get.stringemun": {
        -1: API_ERRORS_BY_ID["CommonErr.UNKNOWN"],
        55555: API_ERRORS_BY_ID["CommonErr.TOKEN_EXPIRE"],
    },
    "api.hello.get.helloway": {
        -1: API_ERRORS_BY_ID["CommonErr.UNKNOWN"],
        55555: API_ERRORS_BY_ID["CommonErr.TOKEN_EXPIRE"],
    },
}


def lookup_api_error_by_id(error_id: str) -> ApiErrorEntry | None:
    return API_ERRORS_BY_ID.get(error_id)


def lookup_api_error_by_code(code: ApiErrorCode, route_id: str | None = None) -> ApiErrorEntry | None:
    if route_id:
        route_entry = ROUTE_API_ERRORS_BY_CODE.get(route_id, {}).get(code)
        if route_entry is not None:
            return route_entry
    return next((entry for entry in API_ERRORS_BY_ID.values() if entry.code == code), None)


def lookup_api_error(payload: dict[str, object] | ApiErrorPayload | None, route_id: str | None = None) -> ApiErrorEntry | None:
    if payload is None:
        return None
    error_id = payload.id if isinstance(payload, ApiErrorPayload) else payload.get("id")
    if isinstance(error_id, str) and error_id:
        entry = lookup_api_error_by_id(error_id)
        if entry is not None:
            return entry
    code = payload.code if isinstance(payload, ApiErrorPayload) else payload.get("code")
    return lookup_api_error_by_code(code, route_id) if isinstance(code, int) else None


def make_api_error_payload(payload: dict[str, object] | None, route_id: str | None = None) -> ApiErrorPayload:
    payload = payload or {}
    entry = lookup_api_error(payload, route_id)
    code = payload.get("code")
    code_value = code if isinstance(code, int) else entry.code if entry is not None else 0
    toast = payload.get("toast")
    toast_dict = toast if isinstance(toast, dict) else {}
    return ApiErrorPayload(
        id=str(payload.get("id") or (entry.id if entry is not None else "")),
        group=str(payload.get("group") or (entry.group if entry is not None else "")),
        key=str(payload.get("key") or (entry.key if entry is not None else "")),
        code=code_value,
        message=str(payload.get("message") or (entry.message if entry is not None else f"API error {code_value}")),
        toast=ApiToastPayload(
            key=str(toast_dict.get("key") or (entry.toast.key if entry is not None else "")),
            level=str(toast_dict.get("level") or (entry.toast.level if entry is not None else "error")),
            default=str(toast_dict.get("default") or (entry.toast.default if entry is not None else "")),
            text=str(toast_dict.get("text") or ""),
        ),
    )


class CommonErr:
    UNKNOWN: ApiErrorEntry = API_ERRORS_BY_ID["CommonErr.UNKNOWN"]
    TOKEN_EXPIRE: ApiErrorEntry = API_ERRORS_BY_ID["CommonErr.TOKEN_EXPIRE"]


class DemoErr:
    UNKNOWN: ApiErrorEntry = API_ERRORS_BY_ID["DemoErr.UNKNOWN"]
    RATE_LIMITED: ApiErrorEntry = API_ERRORS_BY_ID["DemoErr.RATE_LIMITED"]


class ApiErrors:
    CommonErr = CommonErr
    DemoErr = DemoErr
