// Code generated by api-blueprint (Go server HTTP adapter); DO NOT EDIT.

package room

import (
	sharedprovider "example.com/project/golang/server/views/providers"
	shared "example.com/project/golang/server/views/routes/legacy/room"
	httptransport "example.com/project/golang/server/views/transports/http"

	"github.com/gin-gonic/gin"
)

type MountOption = httptransport.MountOption
type ErrorMapperFunc = sharedprovider.ErrorMapperFunc

func WithRouteIDs(routeIDs ...string) MountOption {
	return httptransport.WithRouteIDs(routeIDs...)
}

func WithErrorMapper(mapper ErrorMapperFunc) MountOption {
	return httptransport.WithErrorMapper(mapper)
}

const (
	RouteIDRoomList = shared.RouteIDRoomList
)

const (
	RoutePathRoomList = shared.RoutePathRoomList
)

const (
	HTTPRoutePathRoomList = "/room/list"
)

func Mount(router gin.IRouter, impl shared.RouterInterface, options ...MountOption) shared.RouterInterface {
	if httptransport.IsNilRouterImpl(impl) {
		impl = shared.NewRouter()
	}
	mountOptions := httptransport.NewMountOptions(options...)

	if mountOptions.ShouldMountRoute(RouteIDRoomList) {
		httptransport.GET(
			HTTPRoutePathRoomList,
			sharedprovider.NewRouteExecutor(
				sharedprovider.RouteInfo{
					Root:        "legacy",
					Group:       "room",
					Namespace:   "room",
					Service:     "RoomService",
					Operation:   "RoomList",
					RouteID:     RouteIDRoomList,
					Summary:     "Rootless room list example",
					Description: "Covers a second top-level group under the same logical blueprint.",
					Path:        RoutePathRoomList,
					Methods:     []string{"GET"},
					Transport:   sharedprovider.TransportHTTP,
					Scope:       sharedprovider.ConnectionScope(""),
					HTTP: sharedprovider.HTTPRouteInfo{
						Request: sharedprovider.HTTPRequestInfo{
							PathParams:             []string{},
							BinaryContentEncodings: []string{},
						},
						Response: sharedprovider.HTTPResponseInfo{
							ManualResponse:  false,
							DefaultFilename: "",
						},
					},
				},
				"req|request-signature|handle|rsp=json@CodeMessageDataEnvelope",
				impl.RoomList,
				mountOptions.RuntimeOptions()...,
			),
			router,
		)
	}

	return impl
}

func NewRouter(router gin.IRouter, options ...MountOption) *shared.Router {
	impl := shared.NewRouter()
	Mount(router, impl, options...)
	return impl
}

func NewImpl(router gin.IRouter, options ...MountOption) *shared.Router {
	return NewRouter(router, options...)
}
