// Code generated by api-blueprint (Kotlin server); DO NOT EDIT.
package com.example.apiblueprint.alt.routes.alt.conflict

import com.example.apiblueprint.alt.runtime.*

public interface GenConflictService {

    public suspend fun default(
        query: ConflictDefaultQuery
    ): ConflictModel

}
