// Code generated by api-blueprint (Wails V3); DO NOT EDIT.

package static

import (
	runtime "demo/views/_wailsv3/runtime"
	shared "demo/views/static"
	generated "demo/views/static/_wailsv3"
)

type StaticService struct {
	*generated.StaticService
}

func newGeneratedStaticService(dispatcher runtime.EventDispatcher) *StaticService {
	return &StaticService{
		StaticService: generated.NewStaticService(shared.NewRouter(), dispatcher),
	}
}
