// Code generated by api-blueprint (Java server); DO NOT EDIT.
package com.example.apiblueprint.api.runtime;

public interface ApiServerChannel<Recv, Send, Close> extends ApiServerStream<Send, Close> {
    Recv receive() throws Exception;
}