// Code generated by api-blueprint (Java server); DO NOT EDIT.
package com.example.apiblueprint.api.runtime;

import java.util.Map;

public record GenApiStreamResponse(
    byte[] body,
    String contentType,
    Map<String, String> headers
) {
    public GenApiStreamResponse {
        body = body == null ? new byte[0] : body.clone();
        contentType = contentType == null || contentType.isBlank() ? "application/octet-stream" : contentType;
        headers = headers == null ? Map.of() : Map.copyOf(headers);
    }

    @Override
    public byte[] body() {
        return body.clone();
    }

    public static GenApiStreamResponse of(byte[] body, String contentType) {
        return new GenApiStreamResponse(body, contentType, Map.of());
    }
}