// Code generated by api-blueprint (Java client); DO NOT EDIT.
package com.example.apiblueprint.static_.runtime;

public interface ApiSocketBridge<Send, Recv> {
    void send(Send message);

    void close(Integer code, String reason);

    void onMessage(java.util.function.Consumer<Recv> listener);
}