// Code generated by api-blueprint (Java client); DO NOT EDIT.
package com.example.apiblueprint.static_.runtime;

public interface ApiTransport {
    <T> T execute(ApiRequest<T> request) throws Exception;

    default <Recv, Close> ApiStreamBridge<Recv, Close> openStream(ApiRequest<?> request) {
        throw new UnsupportedOperationException("Java HTTP stream transport is not implemented by the default adapter");
    }

    default <Recv, Send, Close> ApiChannelBridge<Recv, Send, Close> openChannel(ApiRequest<?> request) {
        throw new UnsupportedOperationException("Java HTTP channel transport is not implemented by the default adapter");
    }
}