// Code generated by api-gen-golang; DO NOT EDIT.

package provider

import "strings"

const (
	PROV_WS_HANDLE = "ws_handle"
)

type WsHandleProvider[Q, F, J, P any] struct {
	Subs    []string
	Extra   string
	Handler func(c *Context[Q, F, J, P], req *REQ[Q, F, J]) (rsp *P, err error)
}

func (prov *WsHandleProvider[Q, F, J, P]) GetName() string {
	return PROV_WS_HANDLE
}

func NewWsHandleProvider[Q, F, J, P any](
	data string,
	handler func(c *Context[Q, F, J, P], req *REQ[Q, F, J]) (rsp *P, err error),
) *WsHandleProvider[Q, F, J, P] {
	subsAndExtra := strings.SplitN(data, "@", 2)
	subs := strings.Split(subsAndExtra[0], ",")
	var extra string
	if len(subsAndExtra) > 1 {
		extra = subsAndExtra[1]
	}
	return &WsHandleProvider[Q, F, J, P]{
		Subs:    subs,
		Extra:   extra,
		Handler: handler,
	}
}
