# Code generated by api-blueprint (Python server); DO NOT EDIT.
from __future__ import annotations

from dataclasses import dataclass
from enum import Enum, IntEnum, StrEnum
from typing import Any, Callable, Generic, Mapping, Protocol, Self, TypeVar
from ....runtime.server import ApiUploadFile
from ....runtime.gen_codecs import (
    _MISSING,
    _api_to_json,
    _api_to_transport,
    _decode_any,
    _decode_bool,
    _decode_bytes,
    _decode_coerce_string,
    _decode_file,
    _decode_float,
    _decode_int,
    _decode_list,
    _decode_map,
    _decode_object,
    _decode_one_of,
    _decode_optional,
    _decode_required,
    _decode_str,
    _decode_strict_bool,
    _decode_strict_float,
    _decode_strict_int,
    _field_path,
)


R = TypeVar("R")
C = TypeVar("C")


@dataclass(kw_only=True)
class LegacyJsonCompatResponse:
    target: str | list[str]
    ids: list[str | int]
    normalized_ids: list[str]

    @classmethod
    def from_mapping(cls, value: Mapping[str, Any]) -> Self:
        if not isinstance(value, Mapping):
            raise TypeError("LegacyJsonCompatResponse: expected object")
        return cls._from_mapping(value, "LegacyJsonCompatResponse")

    @classmethod
    def from_value(cls, value: object, path: str = "LegacyJsonCompatResponse") -> Self:
        if isinstance(value, cls):
            return value
        if not isinstance(value, Mapping):
            raise TypeError(f"{path}: expected object")
        return cls._from_mapping(value, path)

    @classmethod
    def _from_mapping(cls, value: Mapping[str, Any], path: str) -> Self:
        return cls(
            target=_decode_required(lambda item, path: _decode_one_of(item, path, (_decode_str, lambda item, path: _decode_list(item, path, _decode_str),)), value.get("target", _MISSING), _field_path(path, "target")),
            ids=_decode_required(lambda item, path: _decode_list(item, path, lambda item, path: _decode_one_of(item, path, (_decode_str, _decode_strict_int,))), value.get("ids", _MISSING), _field_path(path, "ids")),
            normalized_ids=_decode_required(lambda item, path: _decode_list(item, path, _decode_coerce_string), value.get("normalized_ids", _MISSING), _field_path(path, "normalized_ids")),
        )

    def to_mapping(self) -> dict[str, Any]:
        result: dict[str, Any] = {}
        result["target"] = _api_to_json(self.target)
        result["ids"] = _api_to_json(self.ids)
        result["normalized_ids"] = _api_to_json(self.normalized_ids)
        return result

    def to_transport_mapping(self) -> dict[str, Any]:
        result: dict[str, Any] = {}
        result["target"] = _api_to_transport(self.target)
        result["ids"] = _api_to_transport(self.ids)
        result["normalized_ids"] = _api_to_transport(self.normalized_ids)
        return result
