// Code generated by api-blueprint (Java server); DO NOT EDIT.
package com.example.apiblueprint.alt.routes.alt.conflict;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;

import com.example.apiblueprint.alt.runtime.ApiTypes;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;

public final class ConflictTypes {
    private ConflictTypes() {
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public record DefaultQuery(
        @JsonProperty("class_") String classValue
    ) {
    }

}
