// Code generated by api-blueprint (Go server HTTP adapter); DO NOT EDIT.

package conflict

import (
	"reflect"

	sharedprovider "example.com/project/golang/server/views/providers"
	shared "example.com/project/golang/server/views/routes/alt/conflict"
	httptransport "example.com/project/golang/server/views/transports/http"

	"github.com/gin-gonic/gin"
)

func Mount(router gin.IRouter, impl shared.RouterInterface) shared.RouterInterface {
	if isNilRouterInterface(impl) {
		impl = shared.NewRouter()
	}

	httptransport.GET(
		"/alt/conflict/default",
		sharedprovider.NewRouteExecutor(
			sharedprovider.RouteInfo{
				Root:      "alt",
				Group:     "conflict",
				Namespace: "conflict",
				Service:   "ConflictService",
				Operation: "Default",
				RouteID:   "alt.conflict.get.default",
				Path:      "/alt/conflict/default",
				Methods:   []string{"GET"},
				Transport: sharedprovider.TransportHTTP,
				Scope:     sharedprovider.ConnectionScope(""),
				HTTP: sharedprovider.HTTPRouteInfo{
					Request: sharedprovider.HTTPRequestInfo{
						BinaryContentEncodings: []string{},
					},
					Response: sharedprovider.HTTPResponseInfo{
						ManualResponse:  false,
						DefaultFilename: "",
					},
				},
			},
			"req=Q|request-signature|handle|rsp=json@OkDataErrorEnvelope",
			impl.Default,
		),
		router,
	)

	return impl
}

func NewRouter(router gin.IRouter) *shared.Router {
	impl := shared.NewRouter()
	Mount(router, impl)
	return impl
}

func NewImpl(router gin.IRouter) *shared.Router {
	return NewRouter(router)
}

func isNilRouterInterface(impl shared.RouterInterface) bool {
	if impl == nil {
		return true
	}
	value := reflect.ValueOf(impl)
	switch value.Kind() {
	case reflect.Chan, reflect.Func, reflect.Interface, reflect.Map, reflect.Pointer, reflect.Slice:
		return value.IsNil()
	default:
		return false
	}
}
