// Code generated by api-blueprint (Java server); DO NOT EDIT.
package com.example.apiblueprint.alt.transports.http.alt.conflict;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.example.apiblueprint.alt.routes.alt.conflict.ConflictService;
import com.example.apiblueprint.alt.routes.alt.conflict.GenConflictServiceStub;
import com.example.apiblueprint.alt.routes.alt.conflict.GenConflictTypes;
import com.example.apiblueprint.alt.runtime.GenApiError;
import com.example.apiblueprint.alt.runtime.GenApiErrorEntry;
import com.example.apiblueprint.alt.runtime.GenApiErrorPayload;
import com.example.apiblueprint.alt.runtime.GenApiErrors;
import com.example.apiblueprint.alt.runtime.GenApiFilePart;
import com.example.apiblueprint.alt.runtime.GenApiRawResponse;
import com.example.apiblueprint.alt.runtime.GenApiResponseEnvelope;
import com.example.apiblueprint.alt.runtime.GenApiServerChannel;
import com.example.apiblueprint.alt.runtime.GenApiServerStream;
import com.example.apiblueprint.alt.runtime.GenApiStreamResponse;
import com.example.apiblueprint.alt.runtime.GenApiToastPayload;

import com.example.apiblueprint.alt.runtime.GenApiTypes;

import com.example.apiblueprint.alt.runtime.binary.GenApiBinaryBody;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.net.URI;
import java.net.URLDecoder;
import java.net.URLEncoder;
import java.util.concurrent.BlockingQueue;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.LinkedBlockingQueue;
import java.util.LinkedHashMap;
import java.util.Map;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.core.io.InputStreamResource;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.multipart.MultipartHttpServletRequest;
import org.springframework.web.servlet.mvc.method.annotation.SseEmitter;

@RestController
public class GenConflictController {
    private final ConflictService service;
    private final ObjectMapper objectMapper;

    public GenConflictController(
        @Autowired(required = false) ConflictService service,
        ObjectMapper objectMapper
    ) {
        this.service = service == null ? new GenConflictServiceStub() : service;
        this.objectMapper = objectMapper;
    }

    @RequestMapping(path = "/alt/conflict/default", method = RequestMethod.GET)
    public Object defaultValue(
        @RequestParam Map<String, String> queryParams
    ) throws Exception {
        GenConflictTypes.DefaultQuery query;
        try {
            query = objectMapper.convertValue(queryParams, GenConflictTypes.DefaultQuery.class);
        } catch (RuntimeException error) {
            return badRequestResponse(error);
        }
        try {
            Object result = service.defaultValue(
                query
            );
            return wrapResponse(GenApiResponseEnvelope.of("OkDataErrorEnvelope", "ok_data_error", "nested", 0, "ok", new GenApiResponseEnvelope.Fields("code", "message", "data", "error", "ok")), result);
        } catch (GenApiError error) {
            return wrapApiErrorResponse(GenApiResponseEnvelope.of("OkDataErrorEnvelope", "ok_data_error", "nested", 0, "ok", new GenApiResponseEnvelope.Fields("code", "message", "data", "error", "ok")), error, "alt.conflict.get.default");
        }
    }

    private static final class SpringSseStream<Message, Close> implements GenApiServerStream<Message, Close> {
        private final SseEmitter emitter;
        private final ObjectMapper objectMapper;
        private volatile boolean closed = false;

        SpringSseStream(SseEmitter emitter, ObjectMapper objectMapper) {
            this.emitter = emitter;
            this.objectMapper = objectMapper;
        }

        @Override
        public void send(Message message) throws Exception {
            if (closed) {
                return;
            }
            emitter.send(SseEmitter.event().data(message, MediaType.APPLICATION_JSON));
        }

        @Override
        public void close(Close close) throws Exception {
            if (closed) {
                return;
            }
            closed = true;
            emitter.send(SseEmitter.event().name("close").data(close, MediaType.APPLICATION_JSON));
            emitter.complete();
        }

        @Override
        public void abort(int code, String reason) throws Exception {
            if (closed) {
                return;
            }
            closed = true;
            emitter.send(SseEmitter.event().name("close").data(Map.of("code", code, "reason", reason == null ? "" : reason), MediaType.APPLICATION_JSON));
            emitter.complete();
        }

        void abortUnchecked(int code, String reason) {
            try {
                abort(code, reason);
            } catch (Exception error) {
                emitter.completeWithError(error);
            }
        }
    }

    private static Map<String, String> parseQuery(URI uri) {
        if (uri == null || uri.getRawQuery() == null || uri.getRawQuery().isBlank()) {
            return Map.of();
        }
        Map<String, String> result = new LinkedHashMap<>();
        for (String part : uri.getRawQuery().split("&")) {
            if (part.isBlank()) {
                continue;
            }
            int separator = part.indexOf('=');
            String key = separator >= 0 ? part.substring(0, separator) : part;
            String value = separator >= 0 ? part.substring(separator + 1) : "";
            result.put(
                URLDecoder.decode(key, StandardCharsets.UTF_8),
                URLDecoder.decode(value, StandardCharsets.UTF_8)
            );
        }
        return result;
    }

    private Object wrapResponse(GenApiResponseEnvelope envelopeSpec, Object data) {
        if ("none".equals(envelopeSpec.kind())) {
            return data;
        }
        Map<String, Object> envelope = new LinkedHashMap<>();
        if ("code_message_data".equals(envelopeSpec.kind())) {
            envelope.put(envelopeSpec.fields().code(), envelopeSpec.successCode());
            envelope.put(envelopeSpec.fields().message(), envelopeSpec.successMessage());
            envelope.put(envelopeSpec.fields().data(), data);
            return envelope;
        }
        if ("ok_data_error".equals(envelopeSpec.kind())) {
            envelope.put(envelopeSpec.fields().ok(), true);
            envelope.put(envelopeSpec.fields().data(), data);
            return envelope;
        }
        return envelope;
    }

    private Map<String, Object> multipartBody(MultipartHttpServletRequest request) throws IOException {
        Map<String, Object> result = new LinkedHashMap<>();
        if (request == null) {
            return result;
        }
        request.getParameterMap().forEach((key, values) -> {
            if (values != null && values.length > 0) {
                result.put(key, values[0]);
            }
        });
        for (Map.Entry<String, MultipartFile> entry : request.getFileMap().entrySet()) {
            MultipartFile file = entry.getValue();
            result.put(
                entry.getKey(),
                GenApiFilePart.of(file.getOriginalFilename(), file.getContentType(), file.getBytes())
            );
        }
        return result;
    }

    private ResponseEntity<?> rawResponse(String kind, String mediaType, String filename, Object result) throws IOException {
        if (result instanceof GenApiRawResponse raw) {
            ResponseEntity.BodyBuilder builder = rawResponseBuilder(kind, raw.contentType(), raw.filename().isBlank() ? filename : raw.filename());
            raw.headers().forEach(builder::header);
            return builder.body(raw.body());
        }
        if (result instanceof GenApiStreamResponse stream) {
            ResponseEntity.BodyBuilder builder = rawResponseBuilder(kind, stream.contentType(), filename);
            stream.headers().forEach(builder::header);
            return builder.body(new InputStreamResource(stream.body()));
        }
        if (result instanceof GenApiBinaryBody binary) {
            return rawResponseBuilder(kind, binary.contentType(), filename).body(binary.toBytes());
        }
        if (result instanceof byte[] bytes) {
            return rawResponseBuilder(kind, mediaType, filename).body(bytes);
        }
        if (result instanceof String text) {
            return rawResponseBuilder(kind, mediaType, filename).body(text.getBytes(StandardCharsets.UTF_8));
        }
        byte[] bytes = result == null ? new byte[0] : objectMapper.writeValueAsBytes(result);
        return rawResponseBuilder(kind, mediaType, filename).body(bytes);
    }

    private ResponseEntity<byte[]> rawBytesResponse(String mediaType, String filename, byte[] body) {
        return rawResponseBuilder("bytes", mediaType, filename).body(body == null ? new byte[0] : body);
    }

    private ResponseEntity.BodyBuilder rawResponseBuilder(String kind, String mediaType, String filename) {
        ResponseEntity.BodyBuilder builder = ResponseEntity.ok().contentType(MediaType.parseMediaType(mediaType));
        if ("file".equals(kind) && filename != null && !filename.isBlank()) {
            builder.header(HttpHeaders.CONTENT_DISPOSITION, "attachment; filename=\"" + escapeHeader(asciiFilename(filename)) + "\"; filename*=UTF-8''" + encodeHeaderValue(filename));
        }
        return builder;
    }

    private String asciiFilename(String filename) {
        StringBuilder result = new StringBuilder();
        for (int index = 0; index < filename.length(); index++) {
            char current = filename.charAt(index);
            if (current >= 0x20 && current < 0x7f) {
                result.append(current);
            } else {
                result.append('_');
            }
        }
        String value = result.toString();
        return value.isBlank() ? "download" : value;
    }

    private String escapeHeader(String value) {
        return value.replace("\\", "\\\\").replace("\"", "\\\"");
    }

    private String encodeHeaderValue(String value) {
        return URLEncoder.encode(value, StandardCharsets.UTF_8).replace("+", "%20");
    }

    private ResponseEntity<Map<String, Object>> badRequestResponse(Exception error) {
        return ResponseEntity.status(HttpStatus.BAD_REQUEST).body(Map.of("detail", "invalid request"));
    }

    private Object wrapApiErrorResponse(GenApiResponseEnvelope envelopeSpec, GenApiError error, String routeId) {
        GenApiErrorPayload payload = normalizeApiErrorPayload(error.payload(), routeId);
        if ("none".equals(envelopeSpec.kind())) {
            return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).body(payload);
        }
        Map<String, Object> envelope = new LinkedHashMap<>();
        if ("code_message_data".equals(envelopeSpec.kind())) {
            envelope.put(envelopeSpec.fields().code(), payload.code());
            envelope.put(envelopeSpec.fields().message(), payload.message());
            envelope.put(envelopeSpec.fields().data(), null);
            if (!"none".equals(envelopeSpec.errorIdentity())) {
                envelope.put(envelopeSpec.fields().error(), payload);
            }
            return envelope;
        }
        if ("ok_data_error".equals(envelopeSpec.kind())) {
            envelope.put(envelopeSpec.fields().ok(), false);
            envelope.put(envelopeSpec.fields().error(), payload);
            return envelope;
        }
        return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).body(payload);
    }

    private GenApiErrorPayload normalizeApiErrorPayload(GenApiErrorPayload payload, String routeId) {
        if (payload == null) {
            payload = new GenApiErrorPayload("", "", "", 0, "", new GenApiToastPayload("", "error", "", ""));
        }
        GenApiErrorEntry entry = GenApiErrors.lookup(payload, routeId).orElse(null);
        int code = payload.code() != 0 ? payload.code() : entry == null ? 0 : entry.code();
        String message = !payload.message().isBlank()
            ? payload.message()
            : entry == null ? "API error " + code : entry.message();
        GenApiToastPayload toast = payload.toast() == null
            ? new GenApiToastPayload("", "error", "", "")
            : payload.toast();
        return new GenApiErrorPayload(
            payload.id().isBlank() && entry != null ? entry.id() : payload.id(),
            payload.group().isBlank() && entry != null ? entry.group() : payload.group(),
            payload.key().isBlank() && entry != null ? entry.key() : payload.key(),
            code,
            message,
            new GenApiToastPayload(
                toast.key().isBlank() && entry != null ? entry.toast().key() : toast.key(),
                toast.level().isBlank() ? (entry == null ? "error" : entry.toast().level()) : toast.level(),
                toast.defaultMessage().isBlank()
                    ? (entry == null ? message : entry.toast().defaultMessage())
                    : toast.defaultMessage(),
                toast.text()
            )
        );
    }
}
