// Code generated by api-blueprint (Flutter client); DO NOT EDIT.
// ignore_for_file: unused_import

import 'package:api_blueprint_example/src/legacy/runtime/gen_api_transport.dart';
import 'package:api_blueprint_example/src/legacy/runtime/gen_api_errors.dart';
import 'package:api_blueprint_example/src/legacy/runtime/gen_api_types.dart';
import 'gen_legacy_json_types.dart';

class GenLegacyJsonApi {
  final ApiTransport transport;

  GenLegacyJsonApi(this.transport);

  Future<LegacyJsonCompatPayload> legacyJsonCompat({
    ApiRequestOptions options = const ApiRequestOptions(),
  }) {
    return transport.request(
      ApiRequest<LegacyJsonCompatPayload>(
        routeId: "legacy.legacy_json.get.compat",
        method: "GET",
        path: "/legacy-json/compat",
        query: const <String, String?>{},
        options: options,
        responseMediaType: "application/json",
        responseKind: "json",
        responseEnvelope: ApiResponseEnvelope(name: "CodeMessageDataEnvelope", kind: "code_message_data", errorIdentity: "nested", successCode: 0, successMessage: "ok", fields: ApiResponseEnvelopeFields(code: "code", message: "message", data: "data", error: "error", ok: "ok")),
        decode: LegacyJsonCompatPayload.fromJsonValue,
      ),
    );
  }

}
