// Code generated by api-blueprint (Java server); DO NOT EDIT.
package com.example.apiblueprint.legacy.annotations.legacy.legacyjson;

import com.example.apiblueprint.legacy.annotations.ApiBlueprintOperation;
import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

import org.springframework.web.bind.annotation.RequestMapping;

import org.springframework.web.bind.annotation.RequestMethod;

@Target(ElementType.METHOD)
@Retention(RetentionPolicy.RUNTIME)
@RequestMapping(path = "/legacy-json/compat", method = {RequestMethod.GET})

@ApiBlueprintOperation("legacy.legacy_json.get.compat")
public @interface GenLegacyJsonCompat {
}
