// Code generated by api-blueprint (Java client); DO NOT EDIT.
package com.example.apiblueprint.api.routes.api.media;

import com.example.apiblueprint.api.runtime.GenApiChannelBridge;
import com.example.apiblueprint.api.runtime.GenApiRequest;
import com.example.apiblueprint.api.runtime.GenApiRequestBodySpec;
import com.example.apiblueprint.api.runtime.GenApiRequestOptions;
import com.example.apiblueprint.api.runtime.GenApiRawResponse;
import com.example.apiblueprint.api.runtime.GenApiResponseEnvelope;
import com.example.apiblueprint.api.runtime.GenApiResponseSpec;
import com.example.apiblueprint.api.runtime.GenApiStreamResponse;
import com.example.apiblueprint.api.runtime.GenApiStreamBridge;
import com.example.apiblueprint.api.runtime.GenApiTransport;

import com.example.apiblueprint.api.runtime.GenApiTypes;

import com.example.apiblueprint.api.runtime.binary.GenApiBinaryBody;

public class GenMediaApi {
    protected final GenApiTransport transport;

    public GenMediaApi(GenApiTransport transport) {
        this.transport = transport;
    }

    public GenApiRawResponse mediaPreview(
        GenApiTypes.MediaPreviewRequest multipart
    ) throws Exception {
        return mediaPreview(
            multipart,
            GenApiRequestOptions.none()
        );
    }

    public GenApiRawResponse mediaPreview(
        GenApiTypes.MediaPreviewRequest multipart,
        GenApiRequestOptions options
    ) throws Exception {
        GenApiRequestOptions effectiveOptions = options == null ? GenApiRequestOptions.none() : options;
        GenApiRequest<GenApiRawResponse> request = new GenApiRequest<>(
            "api.media.post.preview",
            "POST",
            "/api/media/preview",
            null,
            new GenApiRequestBodySpec(
                null,
                null,
                multipart,
                null,
                "multipart"
            ),
            new GenApiResponseSpec<>(
                GenApiResponseEnvelope.of("CodeMessageDataEnvelope", "code_message_data", "nested", 0, "ok", new GenApiResponseEnvelope.Fields("code", "message", "data", "error", "ok")),
                GenApiRawResponse.class,
                "image/jpeg",
                "bytes",
                null
            ),
            effectiveOptions.headers(),
            effectiveOptions.timeout()
        );
        return transport.execute(request);
    }

    public GenApiRawResponse mediaFrame(
    ) throws Exception {
        return mediaFrame(
            GenApiRequestOptions.none()
        );
    }

    public GenApiRawResponse mediaFrame(
        GenApiRequestOptions options
    ) throws Exception {
        GenApiRequestOptions effectiveOptions = options == null ? GenApiRequestOptions.none() : options;
        GenApiRequest<GenApiRawResponse> request = new GenApiRequest<>(
            "api.media.get.frame",
            "GET",
            "/api/media/frame",
            null,
            new GenApiRequestBodySpec(
                null,
                null,
                null,
                null,
                "none"
            ),
            new GenApiResponseSpec<>(
                GenApiResponseEnvelope.of("CodeMessageDataEnvelope", "code_message_data", "nested", 0, "ok", new GenApiResponseEnvelope.Fields("code", "message", "data", "error", "ok")),
                GenApiRawResponse.class,
                "image/jpeg",
                "bytes",
                null
            ),
            effectiveOptions.headers(),
            effectiveOptions.timeout()
        );
        return transport.execute(request);
    }

    public GenApiRawResponse mediaDownload(
    ) throws Exception {
        return mediaDownload(
            GenApiRequestOptions.none()
        );
    }

    public GenApiRawResponse mediaDownload(
        GenApiRequestOptions options
    ) throws Exception {
        GenApiRequestOptions effectiveOptions = options == null ? GenApiRequestOptions.none() : options;
        GenApiRequest<GenApiRawResponse> request = new GenApiRequest<>(
            "api.media.get.download",
            "GET",
            "/api/media/download",
            null,
            new GenApiRequestBodySpec(
                null,
                null,
                null,
                null,
                "none"
            ),
            new GenApiResponseSpec<>(
                GenApiResponseEnvelope.of("CodeMessageDataEnvelope", "code_message_data", "nested", 0, "ok", new GenApiResponseEnvelope.Fields("code", "message", "data", "error", "ok")),
                GenApiRawResponse.class,
                "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
                "file",
                null
            ),
            effectiveOptions.headers(),
            effectiveOptions.timeout()
        );
        return transport.execute(request);
    }

    public GenApiRawResponse mediaDownloadDynamic(
    ) throws Exception {
        return mediaDownloadDynamic(
            GenApiRequestOptions.none()
        );
    }

    public GenApiRawResponse mediaDownloadDynamic(
        GenApiRequestOptions options
    ) throws Exception {
        GenApiRequestOptions effectiveOptions = options == null ? GenApiRequestOptions.none() : options;
        GenApiRequest<GenApiRawResponse> request = new GenApiRequest<>(
            "api.media.get.downloaddynamic",
            "GET",
            "/api/media/download-dynamic",
            null,
            new GenApiRequestBodySpec(
                null,
                null,
                null,
                null,
                "none"
            ),
            new GenApiResponseSpec<>(
                GenApiResponseEnvelope.of("CodeMessageDataEnvelope", "code_message_data", "nested", 0, "ok", new GenApiResponseEnvelope.Fields("code", "message", "data", "error", "ok")),
                GenApiRawResponse.class,
                "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
                "file",
                null
            ),
            effectiveOptions.headers(),
            effectiveOptions.timeout()
        );
        return transport.execute(request);
    }

    public GenApiRawResponse mediaDownloadFilenameEdge(
    ) throws Exception {
        return mediaDownloadFilenameEdge(
            GenApiRequestOptions.none()
        );
    }

    public GenApiRawResponse mediaDownloadFilenameEdge(
        GenApiRequestOptions options
    ) throws Exception {
        GenApiRequestOptions effectiveOptions = options == null ? GenApiRequestOptions.none() : options;
        GenApiRequest<GenApiRawResponse> request = new GenApiRequest<>(
            "api.media.get.downloadfilenameedge",
            "GET",
            "/api/media/download-filename-edge",
            null,
            new GenApiRequestBodySpec(
                null,
                null,
                null,
                null,
                "none"
            ),
            new GenApiResponseSpec<>(
                GenApiResponseEnvelope.of("CodeMessageDataEnvelope", "code_message_data", "nested", 0, "ok", new GenApiResponseEnvelope.Fields("code", "message", "data", "error", "ok")),
                GenApiRawResponse.class,
                "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
                "file",
                null
            ),
            effectiveOptions.headers(),
            effectiveOptions.timeout()
        );
        return transport.execute(request);
    }

    public GenApiRawResponse mediaErrorFrame(
        GenMediaTypes.MediaErrorFrameQuery query
    ) throws Exception {
        return mediaErrorFrame(
            query,
            GenApiRequestOptions.none()
        );
    }

    public GenApiRawResponse mediaErrorFrame(
        GenMediaTypes.MediaErrorFrameQuery query,
        GenApiRequestOptions options
    ) throws Exception {
        GenApiRequestOptions effectiveOptions = options == null ? GenApiRequestOptions.none() : options;
        GenApiRequest<GenApiRawResponse> request = new GenApiRequest<>(
            "api.media.get.errorframe",
            "GET",
            "/api/media/error-frame",
            query,
            new GenApiRequestBodySpec(
                null,
                null,
                null,
                null,
                "none"
            ),
            new GenApiResponseSpec<>(
                GenApiResponseEnvelope.of("CodeMessageDataEnvelope", "code_message_data", "nested", 0, "ok", new GenApiResponseEnvelope.Fields("code", "message", "data", "error", "ok")),
                GenApiRawResponse.class,
                "image/jpeg",
                "bytes",
                null
            ),
            effectiveOptions.headers(),
            effectiveOptions.timeout()
        );
        return transport.execute(request);
    }

    public GenApiStreamResponse mediaMjpeg(
    ) throws Exception {
        return mediaMjpeg(
            GenApiRequestOptions.none()
        );
    }

    public GenApiStreamResponse mediaMjpeg(
        GenApiRequestOptions options
    ) throws Exception {
        GenApiRequestOptions effectiveOptions = options == null ? GenApiRequestOptions.none() : options;
        GenApiRequest<GenApiStreamResponse> request = new GenApiRequest<>(
            "api.media.get.mjpeg",
            "GET",
            "/api/media/mjpeg",
            null,
            new GenApiRequestBodySpec(
                null,
                null,
                null,
                null,
                "none"
            ),
            new GenApiResponseSpec<>(
                GenApiResponseEnvelope.of("CodeMessageDataEnvelope", "code_message_data", "nested", 0, "ok", new GenApiResponseEnvelope.Fields("code", "message", "data", "error", "ok")),
                GenApiStreamResponse.class,
                "multipart/x-mixed-replace; boundary=frame",
                "byte_stream",
                null
            ),
            effectiveOptions.headers(),
            effectiveOptions.timeout()
        );
        return transport.execute(request);
    }

}
