// Code generated by api-blueprint (Go server); DO NOT EDIT.

package legacy

import (
	"example.com/project/golang/server/views/routes/legacy/account"
	"example.com/project/golang/server/views/routes/legacy/room"
)

type Blueprint struct {
	AccountRouter *account.Router
	RoomRouter    *room.Router
}

func NewBlueprint() *Blueprint {
	return &Blueprint{
		AccountRouter: account.NewRouter(),
		RoomRouter:    room.NewRouter(),
	}
}
