// Code generated by api-blueprint (Go server); DO NOT EDIT.

package api

import (
	"fmt"
)

type _GenRouter struct{}

func (impl *_GenRouter) HelloChannel(
	ctx *CTX_HelloChannel,
	channel CHANNEL_HelloChannel,
) error {
	return fmt.Errorf("not implemented")
}
