// Code generated by api-blueprint (Go server contract metadata); DO NOT EDIT.

package api

import (
	providers "example.com/project/golang/server/views/providers"
	"example.com/project/golang/server/views/routes/api/binary"
	"example.com/project/golang/server/views/routes/api/conflict"
	"example.com/project/golang/server/views/routes/api/demo"
	"example.com/project/golang/server/views/routes/api/hello"
	"example.com/project/golang/server/views/routes/api/media"
)

func ContractRoutes() []providers.ContractRouteInfo {
	routes := []providers.ContractRouteInfo{}
	routes = append(routes, binary.ContractRoutes()...)
	routes = append(routes, conflict.ContractRoutes()...)
	routes = append(routes, demo.ContractRoutes()...)
	routes = append(routes, media.ContractRoutes()...)
	routes = append(routes, hello.ContractRoutes()...)

	return routes
}
