// Code generated by api-blueprint (Golang); DO NOT EDIT.

package api

import (
	"example.com/project/golang/server/views/routes/api/binary"
	"example.com/project/golang/server/views/routes/api/demo"
	"example.com/project/golang/server/views/routes/api/hello"
)

type Blueprint struct {
	Router       *Router
	BinaryRouter *binary.Router
	DemoRouter   *demo.Router
	HelloRouter  *hello.Router
}

func NewBlueprint() *Blueprint {
	return &Blueprint{
		Router:       NewRouter(),
		BinaryRouter: binary.NewRouter(),
		DemoRouter:   demo.NewRouter(),
		HelloRouter:  hello.NewRouter(),
	}
}
