/* eslint-disable */
/* istanbul ignore file */
// Code generated by api-blueprint (TypeScript client); DO NOT EDIT.

import type { ApiClientConfig } from "../../../../runtime/client";
import { WailsV2Transport } from "../../transport";
import { DemoClient as SharedDemoClient } from "../../../../routes/api/demo/client";

type HiddenRawWebSocketMethods =
   "connectWsRaw";

export type DemoClient = Omit<SharedDemoClient, HiddenRawWebSocketMethods>;

export function createClient(config: ApiClientConfig = {}): DemoClient {
  return new SharedDemoClient({
    ...config,
    transport: config.transport ?? new WailsV2Transport(config),
  }) as DemoClient;
}
