// Code generated by api-blueprint (Java server); DO NOT EDIT.
package com.example.apiblueprint.api.routes.api.binary;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;

import com.example.apiblueprint.api.runtime.ApiTypes;

import com.example.apiblueprint.api.runtime.binary.ApiBinaryBody;
import com.example.apiblueprint.api.runtime.binary.GenBinaryRuntime;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;

public final class BinaryTypes {
    private BinaryTypes() {
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public record PacketQuery(
        @JsonProperty("trace") String trace
    ) {
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public record PacketResponse(
        @JsonProperty("trace") String trace,
        @JsonProperty("version") Long version,
        @JsonProperty("item_count") Long itemCount,
        @JsonProperty("payload") String payload,
        @JsonProperty("score_sum") Double scoreSum,
        @JsonProperty("first_label") String firstLabel,
        @JsonProperty("item_ids") List<Long> itemIds,
        @JsonProperty("checksum") Long checksum
    ) {
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public record AuditPacketQuery(
        @JsonProperty("trace") String trace
    ) {
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public record AuditPacketResponse(
        @JsonProperty("trace") String trace,
        @JsonProperty("item_count") Long itemCount,
        @JsonProperty("checksum") Long checksum
    ) {
    }

    public static final class DemoPacketKindValues {
        private DemoPacketKindValues() {
        }

        public static final Integer METRIC = 1;

        public static final Integer DEBUG = 2;

    }

    public static final class DemoPacketFlagsValues {
        private DemoPacketFlagsValues() {
        }

        public static final Long HASPAYLOAD = 1L;

        public static final Long HASSCORES = 2L;

        public static final Long FASTPATH = 4L;

        public static final Long MODE = 24L;

        public static final Long RESERVED = 4294967264L;

    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public record DemoPacket(
        @JsonProperty("header") DemoPacketHeader header,
        @JsonProperty("body") DemoPacketBody body
    ) {
        public ApiBinaryBody toBinaryBody() {
            return DemoPacketWire.toBinaryBody(this);
        }
    }

    public static final class DemoPacketBinaryState {
        public long version = 0L;
        public long kind = 0L;
        public long flags = 0L;
        public long shortCode = 0L;
        public long signedDelta = 0L;
        public long itemCount = 0L;
        public long payloadLen = 0L;
        public long scoreCount = 0L;
        public long checksum = 0L;
        public long id = 0L;
        public long labelLen = 0L;
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public record DemoPacketHeader(
        @JsonProperty("flags") Long flags,
        @JsonProperty("short_code") Integer shortCode,
        @JsonProperty("signed_delta") Integer signedDelta,
        @JsonProperty("item_count") Integer itemCount,
        @JsonProperty("payload_len") Long payloadLen
    ) {
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public record DemoPacketBody(
        @JsonProperty("items") List<DemoPacketItem> items,
        @JsonProperty("payload") byte[] payload,
        @JsonProperty("scores") List<Double> scores,
        @JsonProperty("checksum") Long checksum
    ) {
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public record DemoPacketItem(
        @JsonProperty("id") Long id,
        @JsonProperty("enabled") Boolean enabled,
        @JsonProperty("value") Double value,
        @JsonProperty("label_len") Integer labelLen,
        @JsonProperty("label") byte[] label
    ) {
    }

    public static final class DemoPacketWire {
        public static final String CONTENT_TYPE = "application/octet-stream";
        public static final GenBinaryRuntime.BinaryEndian ENDIAN = GenBinaryRuntime.BinaryEndian.LITTLE;

        private DemoPacketWire() {
        }

        public static ApiBinaryBody toBinaryBody(DemoPacket value) {
            GenBinaryRuntime.BinaryWriter writer = new GenBinaryRuntime.BinaryWriter(ENDIAN);
            write(value, writer);
            return ApiBinaryBody.of(writer.toByteArray(), CONTENT_TYPE);
        }

        public static ApiBinaryBody toBinaryBody(byte[] bytes) {
            return ApiBinaryBody.of(bytes, CONTENT_TYPE);
        }

        public static DemoPacket parse(byte[] bytes) {
            GenBinaryRuntime.BinaryReader reader = new GenBinaryRuntime.BinaryReader(bytes, ENDIAN);
            DemoPacketBinaryState state = new DemoPacketBinaryState();
            DemoPacketHeader header;
            try {
                header = readDemoPacketHeader(reader, state, "");
            } catch (GenBinaryRuntime.BinaryDecodeException error) {
                throw GenBinaryRuntime.wrapBinaryField("DemoPacket.header", error);
            }
            DemoPacketBody body;
            try {
                body = readDemoPacketBody(reader, state, "");
            } catch (GenBinaryRuntime.BinaryDecodeException error) {
                throw GenBinaryRuntime.wrapBinaryField("DemoPacket.body", error);
            }
            reader.requireEOF("DemoPacket");
            return new DemoPacket(
                header,
                body
            );
        }

        public static void write(DemoPacket value, GenBinaryRuntime.BinaryWriter writer) {
            DemoPacketBinaryState state = new DemoPacketBinaryState();
            try {
                writeDemoPacketHeader(value.header(), writer, state, "");
            } catch (GenBinaryRuntime.BinaryEncodeException error) {
                throw GenBinaryRuntime.wrapBinaryField("DemoPacket.header", error);
            }
            try {
                writeDemoPacketBody(value.body(), writer, state, "");
            } catch (GenBinaryRuntime.BinaryEncodeException error) {
                throw GenBinaryRuntime.wrapBinaryField("DemoPacket.body", error);
            }
        }

        public static void writeDemoPacketHeader(
            DemoPacketHeader value,
            GenBinaryRuntime.BinaryWriter writer,
            DemoPacketBinaryState state
        ) {
            writeDemoPacketHeader(value, writer, state, "DemoPacketHeader");
        }

        public static void writeDemoPacketHeader(
            DemoPacketHeader value,
            GenBinaryRuntime.BinaryWriter writer,
            DemoPacketBinaryState state,
            String path
        ) {
            try {
                GenBinaryRuntime.requireBinary("magic", GenBinaryRuntime.bytesEqual(new byte[] {(byte) 65, (byte) 66, (byte) 80, (byte) 49}, new byte[] {(byte) 65, (byte) 66, (byte) 80, (byte) 49}), "const mismatch");
                GenBinaryRuntime.requireSize("magic", GenBinaryRuntime.binarySize(new byte[] {(byte) 65, (byte) 66, (byte) 80, (byte) 49}), 4L);
                writer.writeBytes("magic", new byte[] {(byte) 65, (byte) 66, (byte) 80, (byte) 49});
                GenBinaryRuntime.requireBinary("version", 1L == 1L, "const mismatch");
                writer.writeU16("version", 1);
                state.version = 1L;
                GenBinaryRuntime.requireBinary("kind", 1L == 1L, "const mismatch");
                writer.writeU16("kind", 1);
                state.kind = 1L;
                GenBinaryRuntime.requireRange("flags", value.flags().longValue(), 0L, Long.MAX_VALUE);
                GenBinaryRuntime.requireBinary("flags", (value.flags().longValue() & 4294967264L) == 0L, "reserved bits must be zero");
                writer.writeU32("flags", value.flags());
                state.flags = value.flags().longValue();
                writer.writeZeroes("header_pad", 1L);
                writer.writeZeroes("reserved0", 2L);
                GenBinaryRuntime.requireRange("short_code", value.shortCode().longValue(), 1L, Long.MAX_VALUE);
                GenBinaryRuntime.requireRange("short_code", value.shortCode().longValue(), Long.MIN_VALUE, 16777215L);
                writer.writeU24("short_code", value.shortCode());
                state.shortCode = value.shortCode().longValue();
                GenBinaryRuntime.requireRange("signed_delta", value.signedDelta().longValue(), 0L, Long.MAX_VALUE);
                GenBinaryRuntime.requireRange("signed_delta", value.signedDelta().longValue(), Long.MIN_VALUE, 8388607L);
                writer.writeI24("signed_delta", value.signedDelta());
                state.signedDelta = value.signedDelta().longValue();
                GenBinaryRuntime.requireRange("item_count", value.itemCount().longValue(), 1L, Long.MAX_VALUE);
                GenBinaryRuntime.requireRange("item_count", value.itemCount().longValue(), Long.MIN_VALUE, 8L);
                writer.writeU16("item_count", value.itemCount());
                state.itemCount = value.itemCount().longValue();
                GenBinaryRuntime.requireRange("payload_len", value.payloadLen().longValue(), 0L, Long.MAX_VALUE);
                GenBinaryRuntime.requireRange("payload_len", value.payloadLen().longValue(), Long.MIN_VALUE, 64L);
                writer.writeU32("payload_len", value.payloadLen());
                state.payloadLen = value.payloadLen().longValue();
                GenBinaryRuntime.requireBinary("score_count", 2L == 2L, "const mismatch");
                GenBinaryRuntime.requireRange("score_count", 2L, Long.MIN_VALUE, 4L);
                writer.writeU16("score_count", 2);
                state.scoreCount = 2L;
            } catch (GenBinaryRuntime.BinaryEncodeException error) {
                if (path == null || path.isEmpty()) {
                    throw error;
                }
                throw GenBinaryRuntime.wrapBinaryField(path, error);
            }
        }

        public static DemoPacketHeader readDemoPacketHeader(
            GenBinaryRuntime.BinaryReader reader,
            DemoPacketBinaryState state,
            String path
        ) {
            try {
                byte[] magic = reader.readBytes("magic", 4L);
                GenBinaryRuntime.requireDecodeBinary("magic", GenBinaryRuntime.bytesEqual(magic, new byte[] {(byte) 65, (byte) 66, (byte) 80, (byte) 49}), "const mismatch");
                Integer version = reader.readU16("version");
                GenBinaryRuntime.requireDecodeBinary("version", version.longValue() == 1L, "const mismatch");
                state.version = version.longValue();
                Integer kind = reader.readU16("kind");
                GenBinaryRuntime.requireDecodeBinary("kind", kind.longValue() == 1L, "const mismatch");
                state.kind = kind.longValue();
                Long flags = reader.readU32("flags");
                GenBinaryRuntime.requireDecodeRange("flags", flags.longValue(), 0L, Long.MAX_VALUE);
                GenBinaryRuntime.requireDecodeBinary("flags", (flags.longValue() & 4294967264L) == 0L, "reserved bits must be zero");
                state.flags = flags.longValue();
                reader.readZeroes("header_pad", 1L);
                reader.readZeroes("reserved0", 2L);
                Integer shortCode = reader.readU24("short_code");
                GenBinaryRuntime.requireDecodeRange("short_code", shortCode.longValue(), 1L, Long.MAX_VALUE);
                GenBinaryRuntime.requireDecodeRange("short_code", shortCode.longValue(), Long.MIN_VALUE, 16777215L);
                state.shortCode = shortCode.longValue();
                Integer signedDelta = reader.readI24("signed_delta");
                GenBinaryRuntime.requireDecodeRange("signed_delta", signedDelta.longValue(), 0L, Long.MAX_VALUE);
                GenBinaryRuntime.requireDecodeRange("signed_delta", signedDelta.longValue(), Long.MIN_VALUE, 8388607L);
                state.signedDelta = signedDelta.longValue();
                Integer itemCount = reader.readU16("item_count");
                GenBinaryRuntime.requireDecodeRange("item_count", itemCount.longValue(), 1L, Long.MAX_VALUE);
                GenBinaryRuntime.requireDecodeRange("item_count", itemCount.longValue(), Long.MIN_VALUE, 8L);
                state.itemCount = itemCount.longValue();
                Long payloadLen = reader.readU32("payload_len");
                GenBinaryRuntime.requireDecodeRange("payload_len", payloadLen.longValue(), 0L, Long.MAX_VALUE);
                GenBinaryRuntime.requireDecodeRange("payload_len", payloadLen.longValue(), Long.MIN_VALUE, 64L);
                state.payloadLen = payloadLen.longValue();
                Integer scoreCount = reader.readU16("score_count");
                GenBinaryRuntime.requireDecodeBinary("score_count", scoreCount.longValue() == 2L, "const mismatch");
                GenBinaryRuntime.requireDecodeRange("score_count", scoreCount.longValue(), Long.MIN_VALUE, 4L);
                state.scoreCount = scoreCount.longValue();
                return new DemoPacketHeader(
                    flags,
                    shortCode,
                    signedDelta,
                    itemCount,
                    payloadLen
                );
            } catch (GenBinaryRuntime.BinaryDecodeException error) {
                if (path == null || path.isEmpty()) {
                    throw error;
                }
                throw GenBinaryRuntime.wrapBinaryField(path, error);
            }
        }

        public static void writeDemoPacketBody(
            DemoPacketBody value,
            GenBinaryRuntime.BinaryWriter writer,
            DemoPacketBinaryState state
        ) {
            writeDemoPacketBody(value, writer, state, "DemoPacketBody");
        }

        public static void writeDemoPacketBody(
            DemoPacketBody value,
            GenBinaryRuntime.BinaryWriter writer,
            DemoPacketBinaryState state,
            String path
        ) {
            try {
                long itemsCount = state.itemCount;
                GenBinaryRuntime.requireSize("items", GenBinaryRuntime.binarySize(value.items()), itemsCount);
                for (int index = 0; index < value.items().size(); index++) {
                    try {
                        writeDemoPacketItem(value.items().get(index), writer, state, "");
                    } catch (GenBinaryRuntime.BinaryEncodeException error) {
                        throw GenBinaryRuntime.wrapBinaryIndex("items", index, error);
                    }
                }
                long payloadCount = state.payloadLen;
                GenBinaryRuntime.requireSize("payload", GenBinaryRuntime.binarySize(value.payload()), payloadCount);
                writer.writeBytes("payload", value.payload());
                long scoresCount = state.scoreCount;
                GenBinaryRuntime.requireSize("scores", GenBinaryRuntime.binarySize(value.scores()), scoresCount);
                for (int index = 0; index < value.scores().size(); index++) {
                    try {
                        writer.writeF64("", value.scores().get(index));
                    } catch (GenBinaryRuntime.BinaryEncodeException error) {
                        throw GenBinaryRuntime.wrapBinaryIndex("scores", index, error);
                    }
                }
                GenBinaryRuntime.requireBinary("checksum", value.checksum().longValue() == state.itemCount + state.payloadLen, "assert mismatch");
                writer.writeU32("checksum", value.checksum());
                state.checksum = value.checksum().longValue();
            } catch (GenBinaryRuntime.BinaryEncodeException error) {
                if (path == null || path.isEmpty()) {
                    throw error;
                }
                throw GenBinaryRuntime.wrapBinaryField(path, error);
            }
        }

        public static DemoPacketBody readDemoPacketBody(
            GenBinaryRuntime.BinaryReader reader,
            DemoPacketBinaryState state,
            String path
        ) {
            try {
                long itemsCount = state.itemCount;
                List<DemoPacketItem> items = new ArrayList<>();
                for (int index = 0; index < itemsCount; index++) {
                    try {
                        items.add(readDemoPacketItem(reader, state, ""));
                    } catch (GenBinaryRuntime.BinaryDecodeException error) {
                        throw GenBinaryRuntime.wrapBinaryIndex("items", index, error);
                    }
                }
                byte[] payload = reader.readBytes("payload", state.payloadLen);
                long scoresCount = state.scoreCount;
                List<Double> scores = new ArrayList<>();
                for (int index = 0; index < scoresCount; index++) {
                    try {
                        scores.add(reader.readF64(""));
                    } catch (GenBinaryRuntime.BinaryDecodeException error) {
                        throw GenBinaryRuntime.wrapBinaryIndex("scores", index, error);
                    }
                }
                Long checksum = reader.readU32("checksum");
                GenBinaryRuntime.requireDecodeBinary("checksum", checksum.longValue() == state.itemCount + state.payloadLen, "assert mismatch");
                state.checksum = checksum.longValue();
                return new DemoPacketBody(
                    items,
                    payload,
                    scores,
                    checksum
                );
            } catch (GenBinaryRuntime.BinaryDecodeException error) {
                if (path == null || path.isEmpty()) {
                    throw error;
                }
                throw GenBinaryRuntime.wrapBinaryField(path, error);
            }
        }

        public static void writeDemoPacketItem(
            DemoPacketItem value,
            GenBinaryRuntime.BinaryWriter writer,
            DemoPacketBinaryState state
        ) {
            writeDemoPacketItem(value, writer, state, "Item");
        }

        public static void writeDemoPacketItem(
            DemoPacketItem value,
            GenBinaryRuntime.BinaryWriter writer,
            DemoPacketBinaryState state,
            String path
        ) {
            try {
                GenBinaryRuntime.requireRange("id", value.id().longValue(), 1L, Long.MAX_VALUE);
                GenBinaryRuntime.requireRange("id", value.id().longValue(), Long.MIN_VALUE, 999L);
                writer.writeU32("id", value.id());
                state.id = value.id().longValue();
                writer.writeBool("enabled", value.enabled());
                writer.writeF64("value", value.value());
                GenBinaryRuntime.requireRange("label_len", value.labelLen().longValue(), 1L, Long.MAX_VALUE);
                GenBinaryRuntime.requireRange("label_len", value.labelLen().longValue(), Long.MIN_VALUE, 16L);
                GenBinaryRuntime.requireSize("label_len.label", GenBinaryRuntime.binarySize(value.label()), value.labelLen().longValue());
                writer.writeU8("label_len", value.labelLen());
                state.labelLen = value.labelLen().longValue();
                long labelCount = state.labelLen;
                GenBinaryRuntime.requireSize("label", GenBinaryRuntime.binarySize(value.label()), labelCount);
                writer.writeBytes("label", value.label());
            } catch (GenBinaryRuntime.BinaryEncodeException error) {
                if (path == null || path.isEmpty()) {
                    throw error;
                }
                throw GenBinaryRuntime.wrapBinaryField(path, error);
            }
        }

        public static DemoPacketItem readDemoPacketItem(
            GenBinaryRuntime.BinaryReader reader,
            DemoPacketBinaryState state,
            String path
        ) {
            try {
                Long id = reader.readU32("id");
                GenBinaryRuntime.requireDecodeRange("id", id.longValue(), 1L, Long.MAX_VALUE);
                GenBinaryRuntime.requireDecodeRange("id", id.longValue(), Long.MIN_VALUE, 999L);
                state.id = id.longValue();
                Boolean enabled = reader.readBool("enabled");
                Double value = reader.readF64("value");
                Integer labelLen = reader.readU8("label_len");
                GenBinaryRuntime.requireDecodeRange("label_len", labelLen.longValue(), 1L, Long.MAX_VALUE);
                GenBinaryRuntime.requireDecodeRange("label_len", labelLen.longValue(), Long.MIN_VALUE, 16L);
                state.labelLen = labelLen.longValue();
                byte[] label = reader.readBytes("label", state.labelLen);
                return new DemoPacketItem(
                    id,
                    enabled,
                    value,
                    labelLen,
                    label
                );
            } catch (GenBinaryRuntime.BinaryDecodeException error) {
                if (path == null || path.isEmpty()) {
                    throw error;
                }
                throw GenBinaryRuntime.wrapBinaryField(path, error);
            }
        }

    }

    public static final class AuditPacketKindValues {
        private AuditPacketKindValues() {
        }

        public static final Integer METRIC = 1;

        public static final Integer AUDIT = 2;

    }

    public static final class AuditPacketFlagsValues {
        private AuditPacketFlagsValues() {
        }

        public static final Long HASITEMS = 1L;

        public static final Long MODE = 6L;

        public static final Long RESERVED = 4294967288L;

    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public record AuditPacket(
        @JsonProperty("header") AuditPacketHeader header,
        @JsonProperty("body") AuditPacketBody body
    ) {
        public ApiBinaryBody toBinaryBody() {
            return AuditPacketWire.toBinaryBody(this);
        }
    }

    public static final class AuditPacketBinaryState {
        public long kind = 0L;
        public long flags = 0L;
        public long itemCount = 0L;
        public long checksum = 0L;
        public long id = 0L;
        public long code = 0L;
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public record AuditPacketHeader(
        @JsonProperty("flags") Long flags,
        @JsonProperty("item_count") Integer itemCount
    ) {
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public record AuditPacketBody(
        @JsonProperty("items") List<AuditPacketItem> items,
        @JsonProperty("checksum") Long checksum
    ) {
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public record AuditPacketItem(
        @JsonProperty("id") Long id,
        @JsonProperty("code") Integer code
    ) {
    }

    public static final class AuditPacketWire {
        public static final String CONTENT_TYPE = "application/octet-stream";
        public static final GenBinaryRuntime.BinaryEndian ENDIAN = GenBinaryRuntime.BinaryEndian.LITTLE;

        private AuditPacketWire() {
        }

        public static ApiBinaryBody toBinaryBody(AuditPacket value) {
            GenBinaryRuntime.BinaryWriter writer = new GenBinaryRuntime.BinaryWriter(ENDIAN);
            write(value, writer);
            return ApiBinaryBody.of(writer.toByteArray(), CONTENT_TYPE);
        }

        public static ApiBinaryBody toBinaryBody(byte[] bytes) {
            return ApiBinaryBody.of(bytes, CONTENT_TYPE);
        }

        public static AuditPacket parse(byte[] bytes) {
            GenBinaryRuntime.BinaryReader reader = new GenBinaryRuntime.BinaryReader(bytes, ENDIAN);
            AuditPacketBinaryState state = new AuditPacketBinaryState();
            AuditPacketHeader header;
            try {
                header = readAuditPacketHeader(reader, state, "");
            } catch (GenBinaryRuntime.BinaryDecodeException error) {
                throw GenBinaryRuntime.wrapBinaryField("AuditPacket.header", error);
            }
            AuditPacketBody body;
            try {
                body = readAuditPacketBody(reader, state, "");
            } catch (GenBinaryRuntime.BinaryDecodeException error) {
                throw GenBinaryRuntime.wrapBinaryField("AuditPacket.body", error);
            }
            reader.requireEOF("AuditPacket");
            return new AuditPacket(
                header,
                body
            );
        }

        public static void write(AuditPacket value, GenBinaryRuntime.BinaryWriter writer) {
            AuditPacketBinaryState state = new AuditPacketBinaryState();
            try {
                writeAuditPacketHeader(value.header(), writer, state, "");
            } catch (GenBinaryRuntime.BinaryEncodeException error) {
                throw GenBinaryRuntime.wrapBinaryField("AuditPacket.header", error);
            }
            try {
                writeAuditPacketBody(value.body(), writer, state, "");
            } catch (GenBinaryRuntime.BinaryEncodeException error) {
                throw GenBinaryRuntime.wrapBinaryField("AuditPacket.body", error);
            }
        }

        public static void writeAuditPacketHeader(
            AuditPacketHeader value,
            GenBinaryRuntime.BinaryWriter writer,
            AuditPacketBinaryState state
        ) {
            writeAuditPacketHeader(value, writer, state, "AuditPacketHeader");
        }

        public static void writeAuditPacketHeader(
            AuditPacketHeader value,
            GenBinaryRuntime.BinaryWriter writer,
            AuditPacketBinaryState state,
            String path
        ) {
            try {
                GenBinaryRuntime.requireBinary("kind", 2L == 2L, "const mismatch");
                writer.writeU16("kind", 2);
                state.kind = 2L;
                GenBinaryRuntime.requireRange("flags", value.flags().longValue(), 0L, Long.MAX_VALUE);
                GenBinaryRuntime.requireBinary("flags", (value.flags().longValue() & 4294967288L) == 0L, "reserved bits must be zero");
                writer.writeU32("flags", value.flags());
                state.flags = value.flags().longValue();
                GenBinaryRuntime.requireRange("item_count", value.itemCount().longValue(), 1L, Long.MAX_VALUE);
                GenBinaryRuntime.requireRange("item_count", value.itemCount().longValue(), Long.MIN_VALUE, 4L);
                writer.writeU16("item_count", value.itemCount());
                state.itemCount = value.itemCount().longValue();
            } catch (GenBinaryRuntime.BinaryEncodeException error) {
                if (path == null || path.isEmpty()) {
                    throw error;
                }
                throw GenBinaryRuntime.wrapBinaryField(path, error);
            }
        }

        public static AuditPacketHeader readAuditPacketHeader(
            GenBinaryRuntime.BinaryReader reader,
            AuditPacketBinaryState state,
            String path
        ) {
            try {
                Integer kind = reader.readU16("kind");
                GenBinaryRuntime.requireDecodeBinary("kind", kind.longValue() == 2L, "const mismatch");
                state.kind = kind.longValue();
                Long flags = reader.readU32("flags");
                GenBinaryRuntime.requireDecodeRange("flags", flags.longValue(), 0L, Long.MAX_VALUE);
                GenBinaryRuntime.requireDecodeBinary("flags", (flags.longValue() & 4294967288L) == 0L, "reserved bits must be zero");
                state.flags = flags.longValue();
                Integer itemCount = reader.readU16("item_count");
                GenBinaryRuntime.requireDecodeRange("item_count", itemCount.longValue(), 1L, Long.MAX_VALUE);
                GenBinaryRuntime.requireDecodeRange("item_count", itemCount.longValue(), Long.MIN_VALUE, 4L);
                state.itemCount = itemCount.longValue();
                return new AuditPacketHeader(
                    flags,
                    itemCount
                );
            } catch (GenBinaryRuntime.BinaryDecodeException error) {
                if (path == null || path.isEmpty()) {
                    throw error;
                }
                throw GenBinaryRuntime.wrapBinaryField(path, error);
            }
        }

        public static void writeAuditPacketBody(
            AuditPacketBody value,
            GenBinaryRuntime.BinaryWriter writer,
            AuditPacketBinaryState state
        ) {
            writeAuditPacketBody(value, writer, state, "AuditPacketBody");
        }

        public static void writeAuditPacketBody(
            AuditPacketBody value,
            GenBinaryRuntime.BinaryWriter writer,
            AuditPacketBinaryState state,
            String path
        ) {
            try {
                long itemsCount = state.itemCount;
                GenBinaryRuntime.requireSize("items", GenBinaryRuntime.binarySize(value.items()), itemsCount);
                for (int index = 0; index < value.items().size(); index++) {
                    try {
                        writeAuditPacketItem(value.items().get(index), writer, state, "");
                    } catch (GenBinaryRuntime.BinaryEncodeException error) {
                        throw GenBinaryRuntime.wrapBinaryIndex("items", index, error);
                    }
                }
                GenBinaryRuntime.requireBinary("checksum", value.checksum().longValue() == state.itemCount, "assert mismatch");
                writer.writeU32("checksum", value.checksum());
                state.checksum = value.checksum().longValue();
            } catch (GenBinaryRuntime.BinaryEncodeException error) {
                if (path == null || path.isEmpty()) {
                    throw error;
                }
                throw GenBinaryRuntime.wrapBinaryField(path, error);
            }
        }

        public static AuditPacketBody readAuditPacketBody(
            GenBinaryRuntime.BinaryReader reader,
            AuditPacketBinaryState state,
            String path
        ) {
            try {
                long itemsCount = state.itemCount;
                List<AuditPacketItem> items = new ArrayList<>();
                for (int index = 0; index < itemsCount; index++) {
                    try {
                        items.add(readAuditPacketItem(reader, state, ""));
                    } catch (GenBinaryRuntime.BinaryDecodeException error) {
                        throw GenBinaryRuntime.wrapBinaryIndex("items", index, error);
                    }
                }
                Long checksum = reader.readU32("checksum");
                GenBinaryRuntime.requireDecodeBinary("checksum", checksum.longValue() == state.itemCount, "assert mismatch");
                state.checksum = checksum.longValue();
                return new AuditPacketBody(
                    items,
                    checksum
                );
            } catch (GenBinaryRuntime.BinaryDecodeException error) {
                if (path == null || path.isEmpty()) {
                    throw error;
                }
                throw GenBinaryRuntime.wrapBinaryField(path, error);
            }
        }

        public static void writeAuditPacketItem(
            AuditPacketItem value,
            GenBinaryRuntime.BinaryWriter writer,
            AuditPacketBinaryState state
        ) {
            writeAuditPacketItem(value, writer, state, "Item");
        }

        public static void writeAuditPacketItem(
            AuditPacketItem value,
            GenBinaryRuntime.BinaryWriter writer,
            AuditPacketBinaryState state,
            String path
        ) {
            try {
                GenBinaryRuntime.requireRange("id", value.id().longValue(), 1L, Long.MAX_VALUE);
                writer.writeU32("id", value.id());
                state.id = value.id().longValue();
                GenBinaryRuntime.requireRange("code", value.code().longValue(), 1L, Long.MAX_VALUE);
                GenBinaryRuntime.requireRange("code", value.code().longValue(), Long.MIN_VALUE, 999L);
                writer.writeU16("code", value.code());
                state.code = value.code().longValue();
            } catch (GenBinaryRuntime.BinaryEncodeException error) {
                if (path == null || path.isEmpty()) {
                    throw error;
                }
                throw GenBinaryRuntime.wrapBinaryField(path, error);
            }
        }

        public static AuditPacketItem readAuditPacketItem(
            GenBinaryRuntime.BinaryReader reader,
            AuditPacketBinaryState state,
            String path
        ) {
            try {
                Long id = reader.readU32("id");
                GenBinaryRuntime.requireDecodeRange("id", id.longValue(), 1L, Long.MAX_VALUE);
                state.id = id.longValue();
                Integer code = reader.readU16("code");
                GenBinaryRuntime.requireDecodeRange("code", code.longValue(), 1L, Long.MAX_VALUE);
                GenBinaryRuntime.requireDecodeRange("code", code.longValue(), Long.MIN_VALUE, 999L);
                state.code = code.longValue();
                return new AuditPacketItem(
                    id,
                    code
                );
            } catch (GenBinaryRuntime.BinaryDecodeException error) {
                if (path == null || path.isEmpty()) {
                    throw error;
                }
                throw GenBinaryRuntime.wrapBinaryField(path, error);
            }
        }

    }

}
