// Code generated by api-blueprint (Java server); DO NOT EDIT.
package com.example.apiblueprint.api.routes.api.binary;

import com.example.apiblueprint.api.runtime.ApiTypes;

import com.example.apiblueprint.api.runtime.ApiServerChannel;
import com.example.apiblueprint.api.runtime.ApiServerStream;
import com.example.apiblueprint.api.runtime.binary.ApiBinaryBody;

public interface GenBinaryService {

    BinaryTypes.PacketResponse packet(
        BinaryTypes.PacketQuery query,
        BinaryTypes.DemoPacket binary
    ) throws Exception;

    BinaryTypes.AuditPacketResponse auditPacket(
        BinaryTypes.AuditPacketQuery query,
        BinaryTypes.AuditPacket binary
    ) throws Exception;

}
