// Code generated by api-blueprint (Flutter client); DO NOT EDIT.
// ignore_for_file: unused_import

import 'package:api_blueprint_example/src/api/runtime/gen_api_transport.dart';
import 'package:api_blueprint_example/src/api/runtime/gen_api_errors.dart';
import 'package:api_blueprint_example/src/api/runtime/gen_api_types.dart';
import 'gen_hello_types.dart';


class GenHelloApi {
  final ApiTransport transport;

  GenHelloApi(this.transport);



  Future<HelloAbcResponse> abc({
    HelloAbcQuery? query,
    Map<String, String> headers = const {},
  }) {
    return transport.request(
      ApiRequest<HelloAbcResponse>(
        routeId: "api.hello.get.abc",
        method: "GET",
        path: "/api/hello/abc",
        query: query?.toQueryMap() ?? const <String, String?>{},
        headers: headers,
        responseMediaType: "application/json",
        responseEnvelope: ApiResponseEnvelope(name: "CodeMessageDataEnvelope", kind: "code_message_data", errorIdentity: "nested", successCode: 0, successMessage: "ok", fields: ApiResponseEnvelopeFields(code: "code", message: "message", data: "data", error: "error", ok: "ok")),
        decode: HelloAbcResponseFromJsonValue,
      ),
    );
  }




  Future<HelloMapEnumResponse> mapEnum({
    Map<String, String> headers = const {},
  }) {
    return transport.request(
      ApiRequest<HelloMapEnumResponse>(
        routeId: "api.hello.get.mapenum",
        method: "GET",
        path: "/api/hello/map-enum",
        query: const <String, String?>{},
        headers: headers,
        responseMediaType: "application/json",
        responseEnvelope: ApiResponseEnvelope(name: "CodeMessageDataEnvelope", kind: "code_message_data", errorIdentity: "nested", successCode: 0, successMessage: "ok", fields: ApiResponseEnvelopeFields(code: "code", message: "message", data: "data", error: "error", ok: "ok")),
        decode: HelloMapEnumResponseFromJsonValue,
      ),
    );
  }




  Future<HelloListEnumResponse> listEnum({
    Map<String, String> headers = const {},
  }) {
    return transport.request(
      ApiRequest<HelloListEnumResponse>(
        routeId: "api.hello.get.listenum",
        method: "GET",
        path: "/api/hello/list-enum",
        query: const <String, String?>{},
        headers: headers,
        responseMediaType: "application/json",
        responseEnvelope: ApiResponseEnvelope(name: "CodeMessageDataEnvelope", kind: "code_message_data", errorIdentity: "nested", successCode: 0, successMessage: "ok", fields: ApiResponseEnvelopeFields(code: "code", message: "message", data: "data", error: "error", ok: "ok")),
        decode: HelloListEnumResponseFromJsonValue,
      ),
    );
  }




  Future<HelloStringResponse> string({
    Map<String, String> headers = const {},
  }) {
    return transport.request(
      ApiRequest<HelloStringResponse>(
        routeId: "api.hello.get.string",
        method: "GET",
        path: "/api/hello/string",
        query: const <String, String?>{},
        headers: headers,
        responseMediaType: "application/json",
        responseEnvelope: ApiResponseEnvelope(name: "CodeMessageDataEnvelope", kind: "code_message_data", errorIdentity: "nested", successCode: 0, successMessage: "ok", fields: ApiResponseEnvelopeFields(code: "code", message: "message", data: "data", error: "error", ok: "ok")),
        decode: HelloStringResponseFromJsonValue,
      ),
    );
  }




  Future<HelloUint64Response> uint64({
    Map<String, String> headers = const {},
  }) {
    return transport.request(
      ApiRequest<HelloUint64Response>(
        routeId: "api.hello.get.uint64",
        method: "GET",
        path: "/api/hello/uint64",
        query: const <String, String?>{},
        headers: headers,
        responseMediaType: "application/json",
        responseEnvelope: ApiResponseEnvelope(name: "CodeMessageDataEnvelope", kind: "code_message_data", errorIdentity: "nested", successCode: 0, successMessage: "ok", fields: ApiResponseEnvelopeFields(code: "code", message: "message", data: "data", error: "error", ok: "ok")),
        decode: HelloUint64ResponseFromJsonValue,
      ),
    );
  }




  Future<HelloStringEmunResponse> stringEmun({
    Map<String, String> headers = const {},
  }) {
    return transport.request(
      ApiRequest<HelloStringEmunResponse>(
        routeId: "api.hello.get.stringemun",
        method: "GET",
        path: "/api/hello/string-emun",
        query: const <String, String?>{},
        headers: headers,
        responseMediaType: "application/json",
        responseEnvelope: ApiResponseEnvelope(name: "CodeMessageDataEnvelope", kind: "code_message_data", errorIdentity: "nested", successCode: 0, successMessage: "ok", fields: ApiResponseEnvelopeFields(code: "code", message: "message", data: "data", error: "error", ok: "ok")),
        decode: HelloStringEmunResponseFromJsonValue,
      ),
    );
  }




  Future<void> helloWay({
    HelloHelloWayQuery? query,
    Map<String, String> headers = const {},
  }) {
    return transport.request(
      ApiRequest<void>(
        routeId: "api.hello.get.helloway",
        method: "GET",
        path: "/api/hello/hello-way",
        query: query?.toQueryMap() ?? const <String, String?>{},
        headers: headers,
        responseMediaType: "application/json",
        responseEnvelope: ApiResponseEnvelope(name: "CodeMessageDataEnvelope", kind: "code_message_data", errorIdentity: "nested", successCode: 0, successMessage: "ok", fields: ApiResponseEnvelopeFields(code: "code", message: "message", data: "data", error: "error", ok: "ok")),
        decode: (_) {},
      ),
    );
  }


}
