// Code generated by api-blueprint (Java server); DO NOT EDIT.
package com.example.apiblueprint.legacy.routes.legacy.account.adapters;

import com.example.apiblueprint.legacy.runtime.GenApiTypes;

import com.example.apiblueprint.legacy.runtime.GenApiRawResponse;
import com.example.apiblueprint.legacy.runtime.GenApiStreamResponse;
import com.example.apiblueprint.legacy.routes.legacy.account.types.GenAccountTypes;

public final class GenAccountAdapters {
    private GenAccountAdapters() {
    }

    public static GenApiTypes.AccountProfile accountProfileResponse(GenApiTypes.AccountProfile value) {
        return value;
    }

}
