// Code generated by api-blueprint (Golang HTTP adapter); DO NOT EDIT.

package hellohttp

import (
	httpcore "demo/views/_http"
	shared "demo/views/api/hello"

	"github.com/gin-gonic/gin"
)

func Mount(eng *gin.Engine, impl *shared.Router) *shared.Router {
	if impl == nil {
		impl = shared.NewRouter()
	}

	httpcore.GET[shared.REQ_Abc_QUERY, any, shared.RSP_Abc]("/api/hello/abc", impl.Abc, eng, "req=Q|auth|handle|rsp=json@GeneralWrapper")
	httpcore.GET[any, any, shared.RSP_MapEnum]("/api/hello/map-enum", impl.MapEnum, eng, "req|auth|handle|rsp=json@GeneralWrapper")
	httpcore.GET[any, any, shared.RSP_ListEnum]("/api/hello/list-enum", impl.ListEnum, eng, "req|auth|handle|rsp=json@GeneralWrapper")
	httpcore.GET[any, any, shared.RSP_String]("/api/hello/string", impl.String, eng, "req|auth|handle|rsp=json@GeneralWrapper")
	httpcore.GET[any, any, shared.RSP_Uint64]("/api/hello/uint64", impl.Uint64, eng, "req|auth|handle|rsp=json@GeneralWrapper")
	httpcore.GET[any, any, shared.RSP_StringEmun]("/api/hello/string-emun", impl.StringEmun, eng, "req|auth|handle|rsp=json@GeneralWrapper")
	httpcore.GET[shared.REQ_HelloWay_QUERY, any, shared.RSP_HelloWay]("/api/hello/hello-way", impl.HelloWay, eng, "req=Q|auth|handle|rsp=json@GeneralWrapper")
	return impl
}

func NewRouter(eng *gin.Engine) *shared.Router {
	return Mount(eng, shared.NewRouter())
}

func NewImpl(eng *gin.Engine) *shared.Router {
	return NewRouter(eng)
}
