// Code generated by api-blueprint; DO NOT EDIT.
package com.example.apiblueprint.static_.routes.static_;

import com.example.apiblueprint.static_.runtime.GenModels;
import com.example.apiblueprint.static_.runtime.binary.ApiBinaryBody;

public interface GenStaticService {

    GenStaticServiceModels.RspDocJson docJson(
    ) throws Exception;

    GenStaticServiceModels.RspDochaha dochaha(
    ) throws Exception;

}
