// Code generated by api-blueprint (Kotlin server); DO NOT EDIT.
package com.example.apiblueprint.api.routes.api.binary

import com.example.apiblueprint.api.runtime.*
import kotlinx.serialization.builtins.*
import kotlinx.serialization.KSerializer
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.SerializationException
import kotlinx.serialization.descriptors.PrimitiveKind
import kotlinx.serialization.descriptors.PrimitiveSerialDescriptor
import kotlinx.serialization.descriptors.SerialDescriptor
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder

import com.example.apiblueprint.api.runtime.binary.ApiBinaryBody
import com.example.apiblueprint.api.runtime.binary.BinaryEndian
import com.example.apiblueprint.api.runtime.binary.BinaryWriter
import com.example.apiblueprint.api.runtime.binary.EncodedBinaryBlock
import com.example.apiblueprint.api.runtime.binary.StreamingBinaryBody
import com.example.apiblueprint.api.runtime.binary.binarySize
import com.example.apiblueprint.api.runtime.binary.requireBinary
import com.example.apiblueprint.api.runtime.binary.requireRange
import com.example.apiblueprint.api.runtime.binary.requireSize
import okio.ByteString

@Serializable
public data class BinaryPacketQuery(
    public val trace: String? = null
)

@Serializable
public data class BinaryPacketResponse(
    public val trace: String,
    public val version: Int,
    @SerialName("item_count")
    public val itemCount: Int,
    public val payload: String,
    @SerialName("score_sum")
    public val scoreSum: Double,
    @SerialName("first_label")
    public val firstLabel: String,
    @SerialName("item_ids")
    public val itemIds: List<Int>,
    public val checksum: Int
)

public object DemoKindValues {
    public const val Metric: Int = 1
    public const val Debug: Int = 2
}

public object DemoFlagsValues {
    public const val HasPayload: Long = 1L
    public const val HasScores: Long = 2L
    public const val FastPath: Long = 4L
    public const val Mode: Long = 24L
    public const val Reserved: Long = 4294967264L
}

public data class DemoPacket(
    public val header: DemoPacketHeader,
    public val body: DemoPacketBody
)

public fun DemoPacket.toBinaryBody(): ApiBinaryBody = DemoPacketWire.toBinaryBody(this)

public class DemoPacketBinaryState {
    public var version: Long = 0L
    public var kind: Long = 0L
    public var flags: Long = 0L
    public var shortCode: Long = 0L
    public var signedDelta: Long = 0L
    public var itemCount: Long = 0L
    public var payloadLen: Long = 0L
    public var scoreCount: Long = 0L
    public var checksum: Long = 0L
    public var id: Long = 0L
    public var labelLen: Long = 0L
}

public data class DemoPacketHeader(
    public val flags: Long,
    public val shortCode: Int,
    public val signedDelta: Int,
    public val itemCount: Int,
    public val payloadLen: Long,
    public val magic: ByteArray = byteArrayOf(65, 66, 80, 49),
    public val version: Int = 1,
    public val kind: Int = 1,
    public val scoreCount: Int = 2
)

public data class DemoPacketBody(
    public val items: List<DemoPacketItem>,
    public val payload: ByteArray,
    public val scores: List<Double>,
    public val checksum: Long
)

public data class DemoPacketItem(
    public val id: Long,
    public val enabled: Boolean,
    public val value: Double,
    public val labelLen: Int,
    public val label: ByteArray
)

public object DemoPacketWire {
    public const val CONTENT_TYPE: String = "application/octet-stream"
    public val ENDIAN: BinaryEndian = BinaryEndian.LITTLE

    public fun body(
        contentLength: Long? = null,
        write: (BinaryWriter) -> Unit,
    ): ApiBinaryBody = StreamingBinaryBody(
        contentType = CONTENT_TYPE,
        contentLength = contentLength,
        endian = ENDIAN,
        write = write,
    )

    public fun toBinaryBody(value: DemoPacket): ApiBinaryBody = body { writer ->
        write(value, writer)
    }

    public fun write(value: DemoPacket, writer: BinaryWriter) {
        val state = DemoPacketBinaryState()
        writeDemoPacketHeader(value.header, writer, state, "DemoPacket.header")
        writeDemoPacketBody(value.body, writer, state, "DemoPacket.body")
    }

    public fun writeDemoPacketHeader(
        value: DemoPacketHeader,
        writer: BinaryWriter,
        state: DemoPacketBinaryState = DemoPacketBinaryState(),
        path: String = "DemoPacketHeader",
    ) {

        requireBinary("DemoPacketHeader.magic", value.magic.contentEquals(byteArrayOf(65, 66, 80, 49)), "const mismatch")

        writer.writeBytesExact("DemoPacketHeader.magic", value.magic, 4L)

        requireBinary("DemoPacketHeader.version", value.version.toLong() == 1L, "const mismatch")

        writer.writeU16("DemoPacketHeader.version", value.version)

        state.version = value.version.toLong()

        requireBinary("DemoPacketHeader.kind", value.kind.toLong() == 1L, "const mismatch")

        writer.writeU16("DemoPacketHeader.kind", value.kind)

        state.kind = value.kind.toLong()

        requireRange("DemoPacketHeader.flags", value.flags, 0L, Long.MAX_VALUE)

        requireBinary("DemoPacketHeader.flags", ((value.flags) and 4294967264L) == 0L, "reserved bits must be zero")

        writer.writeU32("DemoPacketHeader.flags", value.flags)

        state.flags = value.flags

        writer.writeZeroes("DemoPacketHeader.header_pad", 1L)

        writer.writeZeroes("DemoPacketHeader.reserved0", 2L)

        requireRange("DemoPacketHeader.short_code", value.shortCode.toLong(), 1L, Long.MAX_VALUE)

        requireRange("DemoPacketHeader.short_code", value.shortCode.toLong(), Long.MIN_VALUE, 16777215L)

        writer.writeU24("DemoPacketHeader.short_code", value.shortCode)

        state.shortCode = value.shortCode.toLong()

        requireRange("DemoPacketHeader.signed_delta", value.signedDelta.toLong(), 0L, Long.MAX_VALUE)

        requireRange("DemoPacketHeader.signed_delta", value.signedDelta.toLong(), Long.MIN_VALUE, 8388607L)

        writer.writeI24("DemoPacketHeader.signed_delta", value.signedDelta)

        state.signedDelta = value.signedDelta.toLong()

        requireRange("DemoPacketHeader.item_count", value.itemCount.toLong(), 1L, Long.MAX_VALUE)

        requireRange("DemoPacketHeader.item_count", value.itemCount.toLong(), Long.MIN_VALUE, 8L)

        writer.writeU16("DemoPacketHeader.item_count", value.itemCount)

        state.itemCount = value.itemCount.toLong()

        requireRange("DemoPacketHeader.payload_len", value.payloadLen, 0L, Long.MAX_VALUE)

        requireRange("DemoPacketHeader.payload_len", value.payloadLen, Long.MIN_VALUE, 64L)

        writer.writeU32("DemoPacketHeader.payload_len", value.payloadLen)

        state.payloadLen = value.payloadLen

        requireBinary("DemoPacketHeader.score_count", value.scoreCount.toLong() == 2L, "const mismatch")

        requireRange("DemoPacketHeader.score_count", value.scoreCount.toLong(), Long.MIN_VALUE, 4L)

        writer.writeU16("DemoPacketHeader.score_count", value.scoreCount)

        state.scoreCount = value.scoreCount.toLong()

    }

    public fun writeDemoPacketHeader(
        writer: BinaryWriter,
        flags: Long,
        shortCode: Int,
        signedDelta: Int,
        itemCount: Int,
        payloadLen: Long,
        magic: ByteArray = byteArrayOf(65, 66, 80, 49),
        version: Int = 1,
        kind: Int = 1,
        scoreCount: Int = 2,
        state: DemoPacketBinaryState = DemoPacketBinaryState(),
        path: String = "DemoPacketHeader",
    ) {

        requireBinary("DemoPacketHeader.magic", magic.contentEquals(byteArrayOf(65, 66, 80, 49)), "const mismatch")

        writer.writeBytesExact("DemoPacketHeader.magic", magic, 4L)

        requireBinary("DemoPacketHeader.version", version.toLong() == 1L, "const mismatch")

        writer.writeU16("DemoPacketHeader.version", version)

        state.version = version.toLong()

        requireBinary("DemoPacketHeader.kind", kind.toLong() == 1L, "const mismatch")

        writer.writeU16("DemoPacketHeader.kind", kind)

        state.kind = kind.toLong()

        requireRange("DemoPacketHeader.flags", flags, 0L, Long.MAX_VALUE)

        requireBinary("DemoPacketHeader.flags", ((flags) and 4294967264L) == 0L, "reserved bits must be zero")

        writer.writeU32("DemoPacketHeader.flags", flags)

        state.flags = flags

        writer.writeZeroes("DemoPacketHeader.header_pad", 1L)

        writer.writeZeroes("DemoPacketHeader.reserved0", 2L)

        requireRange("DemoPacketHeader.short_code", shortCode.toLong(), 1L, Long.MAX_VALUE)

        requireRange("DemoPacketHeader.short_code", shortCode.toLong(), Long.MIN_VALUE, 16777215L)

        writer.writeU24("DemoPacketHeader.short_code", shortCode)

        state.shortCode = shortCode.toLong()

        requireRange("DemoPacketHeader.signed_delta", signedDelta.toLong(), 0L, Long.MAX_VALUE)

        requireRange("DemoPacketHeader.signed_delta", signedDelta.toLong(), Long.MIN_VALUE, 8388607L)

        writer.writeI24("DemoPacketHeader.signed_delta", signedDelta)

        state.signedDelta = signedDelta.toLong()

        requireRange("DemoPacketHeader.item_count", itemCount.toLong(), 1L, Long.MAX_VALUE)

        requireRange("DemoPacketHeader.item_count", itemCount.toLong(), Long.MIN_VALUE, 8L)

        writer.writeU16("DemoPacketHeader.item_count", itemCount)

        state.itemCount = itemCount.toLong()

        requireRange("DemoPacketHeader.payload_len", payloadLen, 0L, Long.MAX_VALUE)

        requireRange("DemoPacketHeader.payload_len", payloadLen, Long.MIN_VALUE, 64L)

        writer.writeU32("DemoPacketHeader.payload_len", payloadLen)

        state.payloadLen = payloadLen

        requireBinary("DemoPacketHeader.score_count", scoreCount.toLong() == 2L, "const mismatch")

        requireRange("DemoPacketHeader.score_count", scoreCount.toLong(), Long.MIN_VALUE, 4L)

        writer.writeU16("DemoPacketHeader.score_count", scoreCount)

        state.scoreCount = scoreCount.toLong()

    }

    public fun newDemoPacketHeaderReserved0Block(
        bytes: ByteString,
        count: Long,
    ): EncodedBinaryBlock = EncodedBinaryBlock(
        field = "DemoPacketHeader.reserved0",
        count = count,
        bytes = bytes,
    )

    public fun writeDemoPacketHeaderReserved0Block(
        writer: BinaryWriter,
        block: EncodedBinaryBlock,
        state: DemoPacketBinaryState = DemoPacketBinaryState(),
        path: String = "DemoPacketHeader.reserved0",
    ) {
        val reserved0Count = 2L
        requireBinary(path, block.field == "DemoPacketHeader.reserved0", "block field ${block.field} does not match " + "DemoPacketHeader.reserved0")
        requireSize("$path.count", block.count, reserved0Count)

        writer.writeBlock(path, block)
    }

    public fun writeDemoPacketHeaderReserved0Fragment(
        writer: BinaryWriter,
        block: EncodedBinaryBlock,
        state: DemoPacketBinaryState = DemoPacketBinaryState(),
        path: String = "DemoPacketHeader.reserved0",
    ) {
        val reserved0Count = 2L
        requireBinary(path, block.field == "DemoPacketHeader.reserved0", "block field ${block.field} does not match " + "DemoPacketHeader.reserved0")
        requireRange("$path.count", block.count, 0L, reserved0Count)

        writer.writeBlock(path, block)
    }

    public fun writeDemoPacketBody(
        value: DemoPacketBody,
        writer: BinaryWriter,
        state: DemoPacketBinaryState = DemoPacketBinaryState(),
        path: String = "DemoPacketBody",
    ) {

        val itemsCount = state.itemCount

        requireSize("DemoPacketBody.items", binarySize(value.items), itemsCount)

        value.items.forEachIndexed { index, item ->
            writeDemoPacketItem(item, writer, state, "DemoPacketBody.items" + "[$index]")
        }

        val payloadCount = state.payloadLen

        requireSize("DemoPacketBody.payload", binarySize(value.payload), payloadCount)

        writer.writeBytes("DemoPacketBody.payload", value.payload)

        val scoresCount = state.scoreCount

        requireSize("DemoPacketBody.scores", binarySize(value.scores), scoresCount)

        value.scores.forEachIndexed { index, item ->
            writer.writeF64("DemoPacketBody.scores" + "[$index]", item)
        }

        requireBinary("DemoPacketBody.checksum", value.checksum == state.itemCount + state.payloadLen, "assert mismatch")

        writer.writeU32("DemoPacketBody.checksum", value.checksum)

        state.checksum = value.checksum

    }

    public fun newDemoPacketBodyItemsBlock(
        bytes: ByteString,
        count: Long,
    ): EncodedBinaryBlock = EncodedBinaryBlock(
        field = "DemoPacketBody.items",
        count = count,
        bytes = bytes,
    )

    public fun writeDemoPacketBodyItemsBlock(
        writer: BinaryWriter,
        block: EncodedBinaryBlock,
        state: DemoPacketBinaryState = DemoPacketBinaryState(),
        path: String = "DemoPacketBody.items",
    ) {
        val itemsCount = state.itemCount
        requireBinary(path, block.field == "DemoPacketBody.items", "block field ${block.field} does not match " + "DemoPacketBody.items")
        requireSize("$path.count", block.count, itemsCount)

        writer.writeBlock(path, block)
    }

    public fun writeDemoPacketBodyItemsFragment(
        writer: BinaryWriter,
        block: EncodedBinaryBlock,
        state: DemoPacketBinaryState = DemoPacketBinaryState(),
        path: String = "DemoPacketBody.items",
    ) {
        val itemsCount = state.itemCount
        requireBinary(path, block.field == "DemoPacketBody.items", "block field ${block.field} does not match " + "DemoPacketBody.items")
        requireRange("$path.count", block.count, 0L, itemsCount)

        writer.writeBlock(path, block)
    }

    public fun newDemoPacketBodyPayloadBlock(
        bytes: ByteString,
        count: Long,
    ): EncodedBinaryBlock = EncodedBinaryBlock(
        field = "DemoPacketBody.payload",
        count = count,
        bytes = bytes,
    )

    public fun writeDemoPacketBodyPayloadBlock(
        writer: BinaryWriter,
        block: EncodedBinaryBlock,
        state: DemoPacketBinaryState = DemoPacketBinaryState(),
        path: String = "DemoPacketBody.payload",
    ) {
        val payloadCount = state.payloadLen
        requireBinary(path, block.field == "DemoPacketBody.payload", "block field ${block.field} does not match " + "DemoPacketBody.payload")
        requireSize("$path.count", block.count, payloadCount)

        requireSize("$path.bytes", block.byteSize, block.count)

        writer.writeBlock(path, block)
    }

    public fun writeDemoPacketBodyPayloadFragment(
        writer: BinaryWriter,
        block: EncodedBinaryBlock,
        state: DemoPacketBinaryState = DemoPacketBinaryState(),
        path: String = "DemoPacketBody.payload",
    ) {
        val payloadCount = state.payloadLen
        requireBinary(path, block.field == "DemoPacketBody.payload", "block field ${block.field} does not match " + "DemoPacketBody.payload")
        requireRange("$path.count", block.count, 0L, payloadCount)

        requireSize("$path.bytes", block.byteSize, block.count)

        writer.writeBlock(path, block)
    }

    public fun newDemoPacketBodyScoresBlock(
        bytes: ByteString,
        count: Long,
    ): EncodedBinaryBlock = EncodedBinaryBlock(
        field = "DemoPacketBody.scores",
        count = count,
        bytes = bytes,
    )

    public fun writeDemoPacketBodyScoresBlock(
        writer: BinaryWriter,
        block: EncodedBinaryBlock,
        state: DemoPacketBinaryState = DemoPacketBinaryState(),
        path: String = "DemoPacketBody.scores",
    ) {
        val scoresCount = state.scoreCount
        requireBinary(path, block.field == "DemoPacketBody.scores", "block field ${block.field} does not match " + "DemoPacketBody.scores")
        requireSize("$path.count", block.count, scoresCount)

        requireSize("$path.bytes", block.byteSize, block.count * 8L)

        writer.writeBlock(path, block)
    }

    public fun writeDemoPacketBodyScoresFragment(
        writer: BinaryWriter,
        block: EncodedBinaryBlock,
        state: DemoPacketBinaryState = DemoPacketBinaryState(),
        path: String = "DemoPacketBody.scores",
    ) {
        val scoresCount = state.scoreCount
        requireBinary(path, block.field == "DemoPacketBody.scores", "block field ${block.field} does not match " + "DemoPacketBody.scores")
        requireRange("$path.count", block.count, 0L, scoresCount)

        requireSize("$path.bytes", block.byteSize, block.count * 8L)

        writer.writeBlock(path, block)
    }

    public fun writeDemoPacketItem(
        value: DemoPacketItem,
        writer: BinaryWriter,
        state: DemoPacketBinaryState = DemoPacketBinaryState(),
        path: String = "DemoPacketItem",
    ) {

        requireRange("DemoPacketItem.id", value.id, 1L, Long.MAX_VALUE)

        requireRange("DemoPacketItem.id", value.id, Long.MIN_VALUE, 999L)

        writer.writeU32("DemoPacketItem.id", value.id)

        state.id = value.id

        writer.writeBool("DemoPacketItem.enabled", value.enabled)

        writer.writeF64("DemoPacketItem.value", value.value)

        requireRange("DemoPacketItem.label_len", value.labelLen.toLong(), 1L, Long.MAX_VALUE)

        requireRange("DemoPacketItem.label_len", value.labelLen.toLong(), Long.MIN_VALUE, 16L)

        requireSize("DemoPacketItem.label_len.label", binarySize(value.label), value.labelLen.toLong())

        writer.writeU8("DemoPacketItem.label_len", value.labelLen)

        state.labelLen = value.labelLen.toLong()

        val labelCount = state.labelLen

        requireSize("DemoPacketItem.label", binarySize(value.label), labelCount)

        writer.writeBytes("DemoPacketItem.label", value.label)

    }

    public fun writeDemoPacketItem(
        writer: BinaryWriter,
        id: Long,
        enabled: Boolean,
        value: Double,
        labelLen: Int,
        label: ByteArray,
        state: DemoPacketBinaryState = DemoPacketBinaryState(),
        path: String = "DemoPacketItem",
    ) {

        requireRange("DemoPacketItem.id", id, 1L, Long.MAX_VALUE)

        requireRange("DemoPacketItem.id", id, Long.MIN_VALUE, 999L)

        writer.writeU32("DemoPacketItem.id", id)

        state.id = id

        writer.writeBool("DemoPacketItem.enabled", enabled)

        writer.writeF64("DemoPacketItem.value", value)

        requireRange("DemoPacketItem.label_len", labelLen.toLong(), 1L, Long.MAX_VALUE)

        requireRange("DemoPacketItem.label_len", labelLen.toLong(), Long.MIN_VALUE, 16L)

        requireSize("DemoPacketItem.label_len.label", binarySize(label), labelLen.toLong())

        writer.writeU8("DemoPacketItem.label_len", labelLen)

        state.labelLen = labelLen.toLong()

        val labelCount = state.labelLen

        requireSize("DemoPacketItem.label", binarySize(label), labelCount)

        writer.writeBytes("DemoPacketItem.label", label)

    }

    public fun writeDemoPacketItem(
        writer: BinaryWriter,
        id: Long,
        enabled: Boolean,
        value: Double,
        labelLen: Int,
        label: ByteString,
        state: DemoPacketBinaryState = DemoPacketBinaryState(),
        path: String = "DemoPacketItem",
    ) {

        requireRange("DemoPacketItem.id", id, 1L, Long.MAX_VALUE)

        requireRange("DemoPacketItem.id", id, Long.MIN_VALUE, 999L)

        writer.writeU32("DemoPacketItem.id", id)

        state.id = id

        writer.writeBool("DemoPacketItem.enabled", enabled)

        writer.writeF64("DemoPacketItem.value", value)

        requireRange("DemoPacketItem.label_len", labelLen.toLong(), 1L, Long.MAX_VALUE)

        requireRange("DemoPacketItem.label_len", labelLen.toLong(), Long.MIN_VALUE, 16L)

        requireSize("DemoPacketItem.label_len.label", binarySize(label), labelLen.toLong())

        writer.writeU8("DemoPacketItem.label_len", labelLen)

        state.labelLen = labelLen.toLong()

        val labelCount = state.labelLen

        requireSize("DemoPacketItem.label", binarySize(label), labelCount)

        writer.writeByteString("DemoPacketItem.label", label)

    }

    public fun newDemoPacketItemLabelBlock(
        bytes: ByteString,
        count: Long,
    ): EncodedBinaryBlock = EncodedBinaryBlock(
        field = "DemoPacketItem.label",
        count = count,
        bytes = bytes,
    )

    public fun writeDemoPacketItemLabelBlock(
        writer: BinaryWriter,
        block: EncodedBinaryBlock,
        state: DemoPacketBinaryState = DemoPacketBinaryState(),
        path: String = "DemoPacketItem.label",
    ) {
        val labelCount = state.labelLen
        requireBinary(path, block.field == "DemoPacketItem.label", "block field ${block.field} does not match " + "DemoPacketItem.label")
        requireSize("$path.count", block.count, labelCount)

        requireSize("$path.bytes", block.byteSize, block.count)

        writer.writeBlock(path, block)
    }

    public fun writeDemoPacketItemLabelFragment(
        writer: BinaryWriter,
        block: EncodedBinaryBlock,
        state: DemoPacketBinaryState = DemoPacketBinaryState(),
        path: String = "DemoPacketItem.label",
    ) {
        val labelCount = state.labelLen
        requireBinary(path, block.field == "DemoPacketItem.label", "block field ${block.field} does not match " + "DemoPacketItem.label")
        requireRange("$path.count", block.count, 0L, labelCount)

        requireSize("$path.bytes", block.byteSize, block.count)

        writer.writeBlock(path, block)
    }

}

