// Code generated by api-blueprint (Go server HTTP adapter); DO NOT EDIT.

package conflict

import (
	sharedprovider "example.com/project/golang/server/views/providers"
	shared "example.com/project/golang/server/views/routes/api/conflict"
	httptransport "example.com/project/golang/server/views/transports/http"

	"github.com/gin-gonic/gin"
)

type MountOption = httptransport.MountOption
type ErrorMapperFunc = sharedprovider.ErrorMapperFunc

func WithRouteIDs(routeIDs ...string) MountOption {
	return httptransport.WithRouteIDs(routeIDs...)
}

func WithErrorMapper(mapper ErrorMapperFunc) MountOption {
	return httptransport.WithErrorMapper(mapper)
}

const (
	RouteIDDefault = shared.RouteIDDefault
)

const (
	RoutePathDefault = shared.RoutePathDefault
)

const (
	HTTPRoutePathDefault = "/api/conflict/default"
)

func Mount(router gin.IRouter, impl shared.RouterInterface, options ...MountOption) shared.RouterInterface {
	return mount(router, impl, true, options...)
}

func MountHTTP(router gin.IRouter, impl shared.RouterInterface, options ...MountOption) shared.RouterInterface {
	return mount(router, impl, false, options...)
}

func mount(router gin.IRouter, impl shared.RouterInterface, includeChannels bool, options ...MountOption) shared.RouterInterface {
	if httptransport.IsNilRouterImpl(impl) {
		impl = shared.NewRouter()
	}
	mountOptions := httptransport.NewMountOptions(options...)

	if mountOptions.ShouldMountRoute(RouteIDDefault) {
		httptransport.GET(
			HTTPRoutePathDefault,
			sharedprovider.NewRouteExecutor(
				sharedprovider.RouteInfo{
					Root:        "api",
					Group:       "conflict",
					Namespace:   "conflict",
					Service:     "ConflictService",
					Operation:   "Default",
					RouteID:     RouteIDDefault,
					Summary:     "Naming conflict example",
					Description: "Covers reserved operation names and route-local model names",
					Path:        RoutePathDefault,
					Methods:     []string{"GET"},
					Transport:   sharedprovider.TransportHTTP,
					Scope:       sharedprovider.ConnectionScope(""),
					HTTP: sharedprovider.HTTPRouteInfo{
						Request: sharedprovider.HTTPRequestInfo{
							PathParams:             []string{},
							BinaryContentEncodings: []string{},
						},
						Response: sharedprovider.HTTPResponseInfo{
							ManualResponse:  false,
							DefaultFilename: "",
						},
					},
				},
				"req=query|auth|request-signature|handle|rsp=json@CodeMessageDataEnvelope",
				impl.Default,
				mountOptions.RuntimeOptions()...,
			),
			router,
		)
	}

	return impl
}

func NewRouter(router gin.IRouter, options ...MountOption) *shared.Router {
	impl := shared.NewRouter()
	Mount(router, impl, options...)
	return impl
}

func NewHTTPRouter(router gin.IRouter, options ...MountOption) *shared.Router {
	impl := shared.NewRouter()
	MountHTTP(router, impl, options...)
	return impl
}

func NewImpl(router gin.IRouter, options ...MountOption) *shared.Router {
	return NewRouter(router, options...)
}
