// Code generated by api-blueprint (Wails V3); DO NOT EDIT.

package static

import (
	runtime "example.com/apiblueprint/wailsv3/runtime"
)

type REQ_DocJson = runtime.REQ[
	any,
	any,
]

type RSP_DocJson_BODY struct {
}

type RSP_DocJson = RSP_DocJson_BODY

type CTX_DocJson = runtime.Context[
	any,
	any,
	RSP_DocJson_BODY,
]

type INVOKE_DocJson = runtime.InvokeEnvelope[
	any,
	any,
]

type REQ_Dochaha = runtime.REQ[
	any,
	any,
]

type RSP_Dochaha_BODY struct {
	A string `json:"a" xml:"a" form:"a"`
}

type RSP_Dochaha = RSP_Dochaha_BODY

type CTX_Dochaha = runtime.Context[
	any,
	any,
	RSP_Dochaha_BODY,
]

type INVOKE_Dochaha = runtime.InvokeEnvelope[
	any,
	any,
]
