# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: legacy/room.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'legacy/room.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11legacy/room.proto\x12\x17\x65xample.api.legacy.room\"\x11\n\x0fRoomListRequest\"G\n\x10RoomListResponse\x12\x33\n\x05rooms\x18\x01 \x03(\x0b\x32$.example.api.legacy.room.RoomSummary\"-\n\x0bRoomSummary\x12\x0f\n\x07room_id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t2n\n\x0bRoomService\x12_\n\x08RoomList\x12(.example.api.legacy.room.RoomListRequest\x1a).example.api.legacy.room.RoomListResponseB.Z,example.com/project/grpc/go/legacy/room;roomb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'legacy.room_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z,example.com/project/grpc/go/legacy/room;room'
  _globals['_ROOMLISTREQUEST']._serialized_start=46
  _globals['_ROOMLISTREQUEST']._serialized_end=63
  _globals['_ROOMLISTRESPONSE']._serialized_start=65
  _globals['_ROOMLISTRESPONSE']._serialized_end=136
  _globals['_ROOMSUMMARY']._serialized_start=138
  _globals['_ROOMSUMMARY']._serialized_end=183
  _globals['_ROOMSERVICE']._serialized_start=185
  _globals['_ROOMSERVICE']._serialized_end=295
# @@protoc_insertion_point(module_scope)
