// Code generated by api-blueprint (Java client); DO NOT EDIT.
package com.example.apiblueprint.legacy.runtime;

import java.util.function.Function;

public record GenApiResponseSpec<T>(
    GenApiResponseEnvelope envelope,
    Class<T> responseClass,
    String mediaType,
    String kind,
    Function<byte[], T> binaryDecoder
) {
    public GenApiResponseSpec {
        envelope = envelope == null ? GenApiResponseEnvelope.none() : envelope;
        mediaType = mediaType == null || mediaType.isBlank() ? "application/json" : mediaType;
        kind = kind == null || kind.isBlank() ? "json" : kind;
    }

    public static <T> GenApiResponseSpec<T> json(Class<T> responseClass) {
        return new GenApiResponseSpec<>(
            GenApiResponseEnvelope.none(),
            responseClass,
            "application/json",
            "json",
            null
        );
    }
}
