# Code generated by api-blueprint (Python server); DO NOT EDIT.
from __future__ import annotations

import asyncio
import json
from dataclasses import asdict, is_dataclass
from enum import Enum
from pathlib import Path
from typing import Any, AsyncIterable, Iterable, Mapping

from fastapi import APIRouter, WebSocket, Request, HTTPException, WebSocketDisconnect
from starlette.responses import StreamingResponse, JSONResponse, FileResponse, Response

from ...runtime.errors import ApiError, make_api_error_payload
from ...runtime.server import ApiRawResponse
from ...routes.alt.conflict.service import ConflictService, ConflictServiceStub
from ...routes.alt.conflict import gen_types as alt_conflict_types


def create_router(
    conflict_service: ConflictService | None = None,
) -> APIRouter:
    router = APIRouter()
    conflict_service_impl = conflict_service or ConflictServiceStub()

    @router.api_route("/alt/conflict/default", methods=["GET"])
    async def conflict_default(request: Request) -> Any:
        service = conflict_service_impl
        query_raw = _query_params(request)
        try:
            query = alt_conflict_types.DefaultQuery.from_value(query_raw, "query")

        except (TypeError, ValueError) as error:
            return _bad_request_response(error)

        try:
            result = await service.default(
                query=query,
            )
            return _wrap_response({"name": "OkDataErrorEnvelope", "kind": "ok_data_error", "error_identity": "nested", "success_code": 0, "success_message": "ok", "fields": {"ok": "ok", "data": "data", "error": "error"}}, result)

        except ApiError as error:
            return _wrap_api_error({"name": "OkDataErrorEnvelope", "kind": "ok_data_error", "error_identity": "nested", "success_code": 0, "success_message": "ok", "fields": {"ok": "ok", "data": "data", "error": "error"}}, error, "alt.conflict.get.default")

    return router


def _query_params(request: Request) -> dict[str, Any]:
    values = dict(request.query_params)
    return values


async def _json_body(request: Request) -> Any:
    body = await request.body()
    if not body:
        return None
    try:
        value = json.loads(body.decode("utf-8"))
    except (UnicodeDecodeError, json.JSONDecodeError) as err:
        raise HTTPException(status_code=400, detail="invalid JSON body") from err
    return value


async def _form_body(request: Request) -> dict[str, Any]:
    values = await request.form()
    result = {key: value for key, value in values.multi_items()}
    return result


async def _multipart_body(request: Request) -> dict[str, Any]:
    values = await request.form()
    return {key: value for key, value in values.multi_items()}


def _jsonable(value: Any) -> Any:
    if isinstance(value, Enum):
        return value.value
    if hasattr(value, "to_mapping"):
        return value.to_mapping()
    if is_dataclass(value):
        return _jsonable(asdict(value))
    if isinstance(value, dict):
        return {_json_key(key): _jsonable(item) for key, item in value.items() if item is not None}
    if isinstance(value, (list, tuple)):
        return [_jsonable(item) for item in value]
    if isinstance(value, bytes):
        return value.decode("utf-8")
    return value


def _json_key(value: Any) -> str:
    if isinstance(value, Enum):
        return str(value.value)
    return str(value)


def _bad_request_response(error: Exception) -> JSONResponse:
    return JSONResponse({"detail": str(error) or "invalid request"}, status_code=400)


def _wrap_response(envelope: dict[str, Any], data: Any) -> Any:
    payload = _jsonable(data)
    kind = envelope.get("kind") or "none"
    fields = envelope.get("fields") or {}
    if kind == "none":
        return payload
    if kind == "code_message_data":
        return {
            fields.get("code", "code"): envelope.get("success_code", 0),
            fields.get("message", "message"): envelope.get("success_message", "ok"),
            fields.get("data", "data"): payload,
        }
    if kind == "ok_data_error":
        return {
            fields.get("ok", "ok"): True,
            fields.get("data", "data"): payload,
        }
    return payload


def _raw_response(
    *,
    kind: str,
    content_type: str,
    filename: str | None,
    result: Any,
) -> Response:
    status = 200
    headers: Mapping[str, str] | None = None
    body = result
    effective_content_type = content_type
    effective_filename = filename
    if isinstance(result, ApiRawResponse):
        status = result.status
        headers = result.headers
        body = result.body
        effective_content_type = result.content_type or content_type
        effective_filename = result.filename or filename
    if isinstance(body, Response):
        return body
    if kind == "file":
        return FileResponse(
            path=body if isinstance(body, (str, Path)) else Path(str(body)),
            status_code=status,
            media_type=effective_content_type,
            filename=effective_filename,
            headers=dict(headers or {}),
        )
    if kind == "byte_stream":
        return StreamingResponse(
            body,
            status_code=status,
            media_type=effective_content_type,
            headers=dict(headers or {}),
        )
    if isinstance(body, str):
        content = body.encode("utf-8")
    else:
        content = bytes(body or b"")
    return Response(
        content=content,
        status_code=status,
        media_type=effective_content_type,
        headers=dict(headers or {}),
    )


def _wrap_api_error(envelope: dict[str, Any], error: ApiError, route_id: str) -> Any:
    payload = _jsonable(make_api_error_payload(_jsonable(error.payload), route_id))
    kind = envelope.get("kind") or "none"
    fields = envelope.get("fields") or {}
    if kind == "none":
        return JSONResponse(payload, status_code=500)
    if kind == "code_message_data":
        body = {
            fields.get("code", "code"): payload.get("code", 0),
            fields.get("message", "message"): payload.get("message", ""),
            fields.get("data", "data"): None,
        }
        if envelope.get("error_identity") != "none":
            body[fields.get("error", "error")] = payload
        return body
    if kind == "ok_data_error":
        return {
            fields.get("ok", "ok"): False,
            fields.get("error", "error"): payload,
        }
    return JSONResponse(payload, status_code=500)


class _SseStream:
    def __init__(self) -> None:
        self._queue: asyncio.Queue[str | None] = asyncio.Queue()
        self.closed = False

    def __aiter__(self):
        return self

    async def __anext__(self) -> str:
        item = await self._queue.get()
        if item is None:
            raise StopAsyncIteration
        return item

    async def send(self, message: Any) -> None:
        if self.closed:
            return
        await self._queue.put("data: " + json.dumps(_jsonable(message), ensure_ascii=False) + "\n\n")

    async def close(self, close: Any) -> None:
        if self.closed:
            return
        self.closed = True
        await self._queue.put(
            "event: close\n"
            + "data: "
            + json.dumps(_jsonable(close), ensure_ascii=False)
            + "\n\n"
        )
        await self._queue.put(None)

    async def abort(self, code: int = 1011, reason: str | None = None) -> None:
        await self.close({"code": code, "reason": reason or ""})


def _identity_decoder(value: Any, path: str) -> Any:
    return value


class _WebSocketChannel:
    def __init__(self, websocket: WebSocket, message_decoder=_identity_decoder) -> None:
        self.websocket = websocket
        self.message_decoder = message_decoder
        self.closed = False

    async def receive(self) -> Any:
        try:
            payload = await self.websocket.receive_text()
        except WebSocketDisconnect as err:
            self.closed = True
            raise _WebSocketClosed() from err
        try:
            value = json.loads(payload)
            return self.message_decoder(value, "message")
        except (UnicodeDecodeError, json.JSONDecodeError, TypeError, ValueError) as err:
            await self.abort(1003, "invalid WebSocket message")
            raise _WebSocketClosed() from err

    async def send(self, message: Any) -> None:
        if self.closed:
            return
        await self.websocket.send_text(
            json.dumps({"type": "message", "data": _jsonable(message)}, ensure_ascii=False)
        )

    async def close(self, close: Any) -> None:
        if self.closed:
            return
        self.closed = True
        await self._send_close(close, 1000)

    async def abort(self, code: int = 1011, reason: str | None = None) -> None:
        if self.closed:
            return
        self.closed = True
        await self._send_close({"code": code, "reason": reason or ""}, code)

    async def _send_close(self, close: Any, code: int) -> None:
        try:
            await self.websocket.send_text(
                json.dumps({"type": "close", "data": _jsonable(close)}, ensure_ascii=False)
            )
        finally:
            await self.websocket.close(code=code)


class _WebSocketClosed(Exception):
    pass
