# Code generated by api-blueprint (Python server); DO NOT EDIT.
from __future__ import annotations

from typing import Any

from fastapi import APIRouter, WebSocket
from starlette.responses import StreamingResponse

from ...routes.alt.conflict.service import ConflictService, ConflictServiceStub


def create_router(
    conflict_service: ConflictService | None = None,
) -> APIRouter:
    router = APIRouter()
    conflict_service_impl = conflict_service or ConflictServiceStub()

    @router.api_route("/alt/conflict/default", methods=["GET"])
    async def conflict_default(
        query: dict[str, Any] | None = None,
    ) -> Any:
        service = conflict_service_impl
        return await service.default(
            query=query,
        )

    return router
