// Code generated by api-blueprint (Go server); DO NOT EDIT.

package demo

type AssistantClientMessageInputCase struct {
	message *AssistantClientMessage
	data    *AssistantClientMessage_Input_DATA
	decoded bool
}

func (msg *AssistantClientMessageInputCase) Type() string {
	return AssistantClientMessageTypeInput
}

func (msg *AssistantClientMessageInputCase) Message() *AssistantClientMessage {
	if msg == nil {
		return nil
	}
	return msg.message
}

func (msg *AssistantClientMessageInputCase) RawData() []byte {
	if msg == nil || msg.message == nil {
		return nil
	}
	return []byte(msg.message.Data)
}

func (msg *AssistantClientMessageInputCase) Decode() (*AssistantClientMessage_Input_DATA, error) {
	if msg == nil || msg.message == nil {
		return nil, nil
	}
	if msg.decoded {
		return msg.data, nil
	}
	data, err := msg.message.DecodeInput()
	if err != nil {
		return nil, newAssistantClientMessageError(AssistantClientMessageErrorDecodeFailed, msg.Type(), err)
	}
	msg.data = data
	msg.decoded = true
	return data, nil
}

type AssistantClientMessageCancelCase struct {
	message *AssistantClientMessage
	data    *AssistantClientMessage_Cancel_DATA
	decoded bool
}

func (msg *AssistantClientMessageCancelCase) Type() string {
	return AssistantClientMessageTypeCancel
}

func (msg *AssistantClientMessageCancelCase) Message() *AssistantClientMessage {
	if msg == nil {
		return nil
	}
	return msg.message
}

func (msg *AssistantClientMessageCancelCase) RawData() []byte {
	if msg == nil || msg.message == nil {
		return nil
	}
	return []byte(msg.message.Data)
}

func (msg *AssistantClientMessageCancelCase) Decode() (*AssistantClientMessage_Cancel_DATA, error) {
	if msg == nil || msg.message == nil {
		return nil, nil
	}
	if msg.decoded {
		return msg.data, nil
	}
	data, err := msg.message.DecodeCancel()
	if err != nil {
		return nil, newAssistantClientMessageError(AssistantClientMessageErrorDecodeFailed, msg.Type(), err)
	}
	msg.data = data
	msg.decoded = true
	return data, nil
}
