// Code generated by api-blueprint (Go server); DO NOT EDIT.

package demo

import (
	"fmt"
)

type _GenRouter struct{}

func (impl *_GenRouter) Abc(ctx *CTX_Abc, req *REQ_Abc) (rsp *RSP_Abc, err error) {
	return nil, fmt.Errorf("not implemented")
}

func (impl *_GenRouter) TestPost(ctx *CTX_TestPost, req *REQ_TestPost) (rsp *RSP_TestPost, err error) {
	return nil, fmt.Errorf("not implemented")
}

func (impl *_GenRouter) FormSubmit(ctx *CTX_FormSubmit, req *REQ_FormSubmit) (rsp *RSP_FormSubmit, err error) {
	return nil, fmt.Errorf("not implemented")
}

func (impl *_GenRouter) RequestOptions(ctx *CTX_RequestOptions, req *REQ_RequestOptions) (rsp *RSP_RequestOptions, err error) {
	return nil, fmt.Errorf("not implemented")
}

func (impl *_GenRouter) PathEcho(ctx *CTX_PathEcho, req *REQ_PathEcho) (rsp *RSP_PathEcho, err error) {
	return nil, fmt.Errorf("not implemented")
}

func (impl *_GenRouter) EmptyResponse(ctx *CTX_EmptyResponse, req *REQ_EmptyResponse) (rsp *RSP_EmptyResponse, err error) {
	return nil, fmt.Errorf("not implemented")
}

func (impl *_GenRouter) PutDemo(ctx *CTX_PutDemo, req *REQ_PutDemo) (rsp *RSP_PutDemo, err error) {
	return nil, fmt.Errorf("not implemented")
}

func (impl *_GenRouter) Delete(ctx *CTX_Delete, req *REQ_Delete) (rsp *RSP_Delete, err error) {
	return nil, fmt.Errorf("not implemented")
}

func (impl *_GenRouter) SweepEvents(
	ctx *CTX_SweepEvents,
	stream STREAM_SweepEvents,
) error {
	return fmt.Errorf("not implemented")
}

func (impl *_GenRouter) AssistantSession(
	ctx *CTX_AssistantSession,
	channel CHANNEL_AssistantSession,
) error {
	return fmt.Errorf("not implemented")
}

func (impl *_GenRouter) PostDeprecated(ctx *CTX_PostDeprecated, req *REQ_PostDeprecated) (rsp *RSP_PostDeprecated, err error) {
	return nil, fmt.Errorf("not implemented")
}

func (impl *_GenRouter) Raw(ctx *CTX_Raw, req *REQ_Raw) (rsp *RSP_Raw, err error) {
	return nil, fmt.Errorf("not implemented")
}

func (impl *_GenRouter) MapModel(ctx *CTX_MapModel, req *REQ_MapModel) (rsp *RSP_MapModel, err error) {
	return nil, fmt.Errorf("not implemented")
}

func (impl *_GenRouter) ErrorDemo(ctx *CTX_ErrorDemo, req *REQ_ErrorDemo) (rsp *RSP_ErrorDemo, err error) {
	return nil, fmt.Errorf("not implemented")
}
