// Code generated by api-blueprint (Java server); DO NOT EDIT.
package com.example.apiblueprint.alt.routes.alt.conflict.delegates;

import com.example.apiblueprint.alt.routes.alt.conflict.types.GenConflictTypes;
import com.example.apiblueprint.alt.runtime.GenApiRawResponse;
import com.example.apiblueprint.alt.runtime.GenApiStreamResponse;
import com.example.apiblueprint.alt.runtime.GenApiTypes;
import com.example.apiblueprint.alt.spring.GenSpringRequestContext;

public interface GenConflictDelegate {

    GenApiTypes.BlueprintsAltConflictConflictModel defaultValue(
        GenConflictTypes.DefaultQuery query,
        GenSpringRequestContext context
    ) throws Exception;

}
