/* eslint-disable */
/* istanbul ignore file */
// Code generated by api-blueprint (TypeScript client); DO NOT EDIT.

import type { ApiClientConfig } from "../../../../runtime/client";
import { WailsV2Transport } from "../../transport";
import { RoomClient as SharedRoomClient } from "../../../../routes/legacy/room/client";

export type RoomClient = SharedRoomClient;

export function createClient(config: ApiClientConfig = {}): RoomClient {
  return new SharedRoomClient({
    ...config,
    transport: config.transport ?? new WailsV2Transport(config),
  }) as RoomClient;
}
