// Code generated by api-blueprint (Kotlin client); DO NOT EDIT.
package com.example.apiblueprint.legacy.runtime

import com.example.apiblueprint.legacy.routes.legacy.account.AccountApi
import com.example.apiblueprint.legacy.routes.legacy.room.RoomApi

public open class GenApiClient(
    private val transport: ApiTransport,
) {
    public val account: AccountApi = AccountApi(transport)
    public val room: RoomApi = RoomApi(transport)
}
