/* eslint-disable */
/* istanbul ignore file */
// Code generated by api-blueprint (TypeScript); DO NOT EDIT.

import type * as Models from "./models";
import type * as Shared from "../shared/models";
import { BaseClient, ApiClientConfig } from "../shared/client";

export class HelloClient extends BaseClient {
  constructor(config: ApiClientConfig = {}) {
    super(config, "http://localhost:2333");
  }


  /**
   * 这是abc的summary
   * 这是abc的description
   * Tags: api
   */
  async abc(
    request: {
      query?: Models.ReqAbcQuery;
      headers?: Record<string, string>;
    } = {},
    init: RequestInit = {},
    timeoutMs?: number,
  ): Promise<Models.RspAbc> {
    return this.request<Models.RspAbc>({
      method: "GET",
      path: "/api/hello/abc",
      query: request.query as unknown as Record<string, unknown> | undefined,
      headers: request.headers,
      init,
      responseType: "json",
      timeoutMs,
    });
  }


  /**
   * map-enum
   * map-enum
   * Tags: api
   */
  async mapEnum(
    request: {
      headers?: Record<string, string>;
    } = {},
    init: RequestInit = {},
    timeoutMs?: number,
  ): Promise<Models.RspMapenum> {
    return this.request<Models.RspMapenum>({
      method: "GET",
      path: "/api/hello/map-enum",
      headers: request.headers,
      init,
      responseType: "json",
      timeoutMs,
    });
  }


  /**
   * list-enum
   * list-enum
   * Tags: api
   */
  async listEnum(
    request: {
      headers?: Record<string, string>;
    } = {},
    init: RequestInit = {},
    timeoutMs?: number,
  ): Promise<Models.RspListenum> {
    return this.request<Models.RspListenum>({
      method: "GET",
      path: "/api/hello/list-enum",
      headers: request.headers,
      init,
      responseType: "json",
      timeoutMs,
    });
  }


  /**
   * string
   * string
   * Tags: api
   */
  async string(
    request: {
      headers?: Record<string, string>;
    } = {},
    init: RequestInit = {},
    timeoutMs?: number,
  ): Promise<Models.RspString> {
    return this.request<Models.RspString>({
      method: "GET",
      path: "/api/hello/string",
      headers: request.headers,
      init,
      responseType: "json",
      timeoutMs,
    });
  }


  /**
   * uint64
   * uint64
   * Tags: api
   */
  async uint64(
    request: {
      headers?: Record<string, string>;
    } = {},
    init: RequestInit = {},
    timeoutMs?: number,
  ): Promise<Models.RspUint64> {
    return this.request<Models.RspUint64>({
      method: "GET",
      path: "/api/hello/uint64",
      headers: request.headers,
      init,
      responseType: "json",
      timeoutMs,
    });
  }


  /**
   * string-enum
   * string-enum
   * Tags: api
   */
  async stringEmun(
    request: {
      headers?: Record<string, string>;
    } = {},
    init: RequestInit = {},
    timeoutMs?: number,
  ): Promise<Models.RspStringemun> {
    return this.request<Models.RspStringemun>({
      method: "GET",
      path: "/api/hello/string-emun",
      headers: request.headers,
      init,
      responseType: "json",
      timeoutMs,
    });
  }


  /**
   * hello-way
   * hello-way
   * Tags: api
   */
  async helloWay(
    request: {
      query?: Models.ReqHellowayQuery;
      headers?: Record<string, string>;
    } = {},
    init: RequestInit = {},
    timeoutMs?: number,
  ): Promise<Models.RspHelloway> {
    return this.request<Models.RspHelloway>({
      method: "GET",
      path: "/api/hello/hello-way",
      query: request.query as unknown as Record<string, unknown> | undefined,
      headers: request.headers,
      init,
      responseType: "json",
      timeoutMs,
    });
  }

}
