// Code generated by api-blueprint (Wails V2); DO NOT EDIT.

package status

import (
	sharedroutes "example.com/project/golang/server/views/routes/runtime/status"
	wailstransport "example.com/project/golang/server/views/transports/wailsv2"
)

type RouterInterface = sharedroutes.RouterInterface

type REQ_RuntimeCurrentStatus = sharedroutes.REQ_RuntimeCurrentStatus
type RSP_RuntimeCurrentStatus = sharedroutes.RSP_RuntimeCurrentStatus
type CTX_RuntimeCurrentStatus = sharedroutes.CTX_RuntimeCurrentStatus

type INVOKE_RuntimeCurrentStatus = wailstransport.InvokeEnvelope[any, any]
