// Code generated by api-blueprint (Go client); DO NOT EDIT.

package binary

import (
	"context"
	runtime "example.com/project/golang/client/runtime"
	runtimebinary "example.com/project/golang/client/runtime/binary"
)

type GenBinaryClient struct {
	transport runtime.Transport
}

func NewGenBinaryClient(transport runtime.Transport) *GenBinaryClient {
	return &GenBinaryClient{transport: transport}
}

type Client = GenBinaryClient

var NewClient = NewGenBinaryClient

type BinaryClient = GenBinaryClient

var NewBinaryClient = NewGenBinaryClient

func (client *GenBinaryClient) Packet(ctx context.Context, query PacketQuery, binaryBody runtimebinary.Body, opts ...runtime.RequestOption) (*PacketResponse, error) {
	request := runtime.Request{
		RouteID:          "api.binary.post.packet",
		Method:           "POST",
		Path:             "/api/binary/packet",
		ResponseEnvelope: runtime.ApiResponseEnvelope{Name: "CodeMessageDataEnvelope", Kind: "code_message_data", ErrorIdentity: "nested", SuccessCode: runtime.ApiErrorCode(0), SuccessMessage: "ok", Fields: runtime.ApiResponseEnvelopeFields{Code: "code", Message: "message", Data: "data", Error: "error", Ok: "ok"}},
		Query:            query,
		Binary:           binaryBody,
		BodyKind:         runtime.RequestBodyKind("binary_schema"),
		ResponseKind:     runtime.ResponseKind("json"),
	}
	request.ApplyOptions(opts...)
	var response PacketResponse
	if err := client.transport.Do(ctx, request, &response); err != nil {
		return nil, err
	}
	return &response, nil
}

func (client *GenBinaryClient) AuditPacket(ctx context.Context, query AuditPacketQuery, binaryBody runtimebinary.Body, opts ...runtime.RequestOption) (*AuditPacketResponse, error) {
	request := runtime.Request{
		RouteID:          "api.binary.post.auditpacket",
		Method:           "POST",
		Path:             "/api/binary/audit-packet",
		ResponseEnvelope: runtime.ApiResponseEnvelope{Name: "CodeMessageDataEnvelope", Kind: "code_message_data", ErrorIdentity: "nested", SuccessCode: runtime.ApiErrorCode(0), SuccessMessage: "ok", Fields: runtime.ApiResponseEnvelopeFields{Code: "code", Message: "message", Data: "data", Error: "error", Ok: "ok"}},
		Query:            query,
		Binary:           binaryBody,
		BodyKind:         runtime.RequestBodyKind("binary_schema"),
		ResponseKind:     runtime.ResponseKind("json"),
	}
	request.ApplyOptions(opts...)
	var response AuditPacketResponse
	if err := client.transport.Do(ctx, request, &response); err != nil {
		return nil, err
	}
	return &response, nil
}

func (client *GenBinaryClient) WidePacket(ctx context.Context, query WidePacketQuery, binaryBody runtimebinary.Body, opts ...runtime.RequestOption) (*WidePacketResponse, error) {
	request := runtime.Request{
		RouteID:          "api.binary.post.widepacket",
		Method:           "POST",
		Path:             "/api/binary/wide-packet",
		ResponseEnvelope: runtime.ApiResponseEnvelope{Name: "CodeMessageDataEnvelope", Kind: "code_message_data", ErrorIdentity: "nested", SuccessCode: runtime.ApiErrorCode(0), SuccessMessage: "ok", Fields: runtime.ApiResponseEnvelopeFields{Code: "code", Message: "message", Data: "data", Error: "error", Ok: "ok"}},
		Query:            query,
		Binary:           binaryBody,
		BodyKind:         runtime.RequestBodyKind("binary_schema"),
		ResponseKind:     runtime.ResponseKind("json"),
	}
	request.ApplyOptions(opts...)
	var response WidePacketResponse
	if err := client.transport.Do(ctx, request, &response); err != nil {
		return nil, err
	}
	return &response, nil
}

func (client *GenBinaryClient) AuditPacketResponse(ctx context.Context, opts ...runtime.RequestOption) (*AuditPacket, error) {
	request := runtime.Request{
		RouteID:          "api.binary.get.auditpacketresponse",
		Method:           "GET",
		Path:             "/api/binary/audit-packet-response",
		ResponseEnvelope: runtime.ApiResponseEnvelope{Name: "CodeMessageDataEnvelope", Kind: "code_message_data", ErrorIdentity: "nested", SuccessCode: runtime.ApiErrorCode(0), SuccessMessage: "ok", Fields: runtime.ApiResponseEnvelopeFields{Code: "code", Message: "message", Data: "data", Error: "error", Ok: "ok"}},
		BodyKind:         runtime.RequestBodyKind("none"),
		ResponseKind:     runtime.ResponseKind("binary_schema"),
	}
	request.ApplyOptions(opts...)
	var response AuditPacket
	if err := client.transport.Do(ctx, request, &response); err != nil {
		return nil, err
	}
	return &response, nil
}
