// Code generated by api-blueprint (Kotlin client); DO NOT EDIT.
package com.example.apiblueprint.alt.routes.alt.conflict

import com.example.apiblueprint.alt.runtime.*

import kotlinx.serialization.builtins.*

public open class GenConflictApi internal constructor(
    private val transport: ApiTransport,
) {

    public open suspend fun default(
        query: ConflictDefaultQuery,
        headers: Map<String, String> = emptyMap(),
    ): ConflictModel {
        return transport.request(
            ApiRequest(
                routeId = "alt.conflict.get.default",
                method = "GET",
                path = "/alt/conflict/default",
                query = query.toQueryMap(),
                headers = headers,
                responseSerializer = ConflictModel.serializer(),
                responseMediaType = "application/json",
                responseEnvelope = ApiResponseEnvelope(name = "OkDataErrorEnvelope", kind = "ok_data_error", errorIdentity = "nested", successCode = 0, successMessage = "ok", fields = ApiResponseEnvelopeFields(code = "code", message = "message", data = "data", error = "error", ok = "ok")),
                responseDecoder = null,
            )
        )
    }

    private fun ConflictDefaultQuery.toQueryMap(): Map<String, String?> = mapOf(
        "class_" to `class`?.toString()
    )
}
