// Code generated by api-blueprint (Java server); DO NOT EDIT.
package com.example.apiblueprint.api.types.api.hello;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.JsonNode;

import com.example.apiblueprint.api.runtime.GenApiTypes;

import com.example.apiblueprint.api.runtime.GenApiFilePart;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;

public final class GenHelloTypes {
    private GenHelloTypes() {
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class AbcQuery {

        @JsonProperty("arg1")
        private Boolean arg1;

        @JsonProperty("arg3")
        private String arg3;

        @JsonProperty("arg2")
        private Float arg2;

        @JsonProperty("type")
        private GenApiTypes.HelloChannelMsgTypeEnum type;

        public AbcQuery() {
        }

        public AbcQuery(
            Boolean arg1,
            String arg3,
            Float arg2,
            GenApiTypes.HelloChannelMsgTypeEnum type
        ) {
            this.arg1 = arg1;
            this.arg3 = arg3;
            this.arg2 = arg2;
            this.type = type;
        }

        @JsonProperty("arg1")
        public Boolean getArg1() {
            return arg1;
        }

        @JsonProperty("arg1")
        public void setArg1(Boolean arg1) {
            this.arg1 = arg1;
        }

        @JsonProperty("arg3")
        public String getArg3() {
            return arg3;
        }

        @JsonProperty("arg3")
        public void setArg3(String arg3) {
            this.arg3 = arg3;
        }

        @JsonProperty("arg2")
        public Float getArg2() {
            return arg2;
        }

        @JsonProperty("arg2")
        public void setArg2(Float arg2) {
            this.arg2 = arg2;
        }

        @JsonProperty("type")
        public GenApiTypes.HelloChannelMsgTypeEnum getType() {
            return type;
        }

        @JsonProperty("type")
        public void setType(GenApiTypes.HelloChannelMsgTypeEnum type) {
            this.type = type;
        }

        public static Builder builder() {
            return new Builder();
        }

        public Builder toBuilder() {
            return builder()
                .arg1(arg1)
                .arg3(arg3)
                .arg2(arg2)
                .type(type);
        }

        public static final class Builder {

            private Boolean arg1;

            private String arg3;

            private Float arg2;

            private GenApiTypes.HelloChannelMsgTypeEnum type;

            public Builder arg1(Boolean arg1) {
                this.arg1 = arg1;
                return this;
            }

            public Builder arg3(String arg3) {
                this.arg3 = arg3;
                return this;
            }

            public Builder arg2(Float arg2) {
                this.arg2 = arg2;
                return this;
            }

            public Builder type(GenApiTypes.HelloChannelMsgTypeEnum type) {
                this.type = type;
                return this;
            }

            public AbcQuery build() {

                return new AbcQuery(
                    arg1,
                    arg3,
                    arg2,
                    type
                );

            }
        }
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class AbcResponse {

        public AbcResponse() {
        }

        public static Builder builder() {
            return new Builder();
        }

        public Builder toBuilder() {
            return builder();
        }

        public static final class Builder {

            public AbcResponse build() {

                return new AbcResponse();

            }
        }
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class MapEnumResponse {

        public MapEnumResponse() {
        }

        public static Builder builder() {
            return new Builder();
        }

        public Builder toBuilder() {
            return builder();
        }

        public static final class Builder {

            public MapEnumResponse build() {

                return new MapEnumResponse();

            }
        }
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class ListEnumResponse {

        public ListEnumResponse() {
        }

        public static Builder builder() {
            return new Builder();
        }

        public Builder toBuilder() {
            return builder();
        }

        public static final class Builder {

            public ListEnumResponse build() {

                return new ListEnumResponse();

            }
        }
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class StringResponse {

        public StringResponse() {
        }

        public static Builder builder() {
            return new Builder();
        }

        public Builder toBuilder() {
            return builder();
        }

        public static final class Builder {

            public StringResponse build() {

                return new StringResponse();

            }
        }
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Uint64Response {

        public Uint64Response() {
        }

        public static Builder builder() {
            return new Builder();
        }

        public Builder toBuilder() {
            return builder();
        }

        public static final class Builder {

            public Uint64Response build() {

                return new Uint64Response();

            }
        }
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class StringEmunResponse {

        public StringEmunResponse() {
        }

        public static Builder builder() {
            return new Builder();
        }

        public Builder toBuilder() {
            return builder();
        }

        public static final class Builder {

            public StringEmunResponse build() {

                return new StringEmunResponse();

            }
        }
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class HelloWayQuery {

        @JsonProperty("arg1")
        private GenApiTypes.HelloWayEnum arg1;

        public HelloWayQuery() {
        }

        public HelloWayQuery(
            GenApiTypes.HelloWayEnum arg1
        ) {
            this.arg1 = arg1;
        }

        @JsonProperty("arg1")
        public GenApiTypes.HelloWayEnum getArg1() {
            return arg1;
        }

        @JsonProperty("arg1")
        public void setArg1(GenApiTypes.HelloWayEnum arg1) {
            this.arg1 = arg1;
        }

        public static Builder builder() {
            return new Builder();
        }

        public Builder toBuilder() {
            return builder()
                .arg1(arg1);
        }

        public static final class Builder {

            private GenApiTypes.HelloWayEnum arg1;

            public Builder arg1(GenApiTypes.HelloWayEnum arg1) {
                this.arg1 = arg1;
                return this;
            }

            public HelloWayQuery build() {

                return new HelloWayQuery(
                    arg1
                );

            }
        }
    }

}
