# Code generated by api-blueprint (Python client); DO NOT EDIT.
from __future__ import annotations

from typing import Any, Mapping

from ...runtime.client import ApiChannelBridge, ApiClientTransport, ApiRawResponse, ApiStreamBridge, ApiStreamResponse
from ...runtime.gen_codecs import (
    _api_to_json,
    _api_to_transport,
    _decode_any,
    _decode_bool,
    _decode_bytes,
    _decode_float,
    _decode_int,
    _decode_list,
    _decode_map,
    _decode_object,
    _decode_str,
)


from .gen_types import (
    HelloChannelMessage,
    HelloChannelClose,
    HelloChannelMsgTypeEnum,
)


class ApiClient:
    def __init__(self, transport: ApiClientTransport):
        self._transport = transport

    def open_hello_channel(
        self,
        headers: dict[str, str] | None = None,
        protocols: tuple[str, ...] = (),
    ) -> ApiChannelBridge[HelloChannelMessage, HelloChannelMessage, HelloChannelClose]:
        return self._transport.open_channel(
            route_id="api.api.channel.ws",
            path="/api/ws",
            headers=headers,
            protocols=protocols,
        )
