from __future__ import annotations

from typing import ClassVar, Generic, TypeVar

from .helpers import *
from api_blueprint.engine.envelope import ResponseEnvelope
from api_blueprint.engine.schema import Field, Int


TM = TypeVar("TM", bound=Model)


@pytest.mark.toolchain_smoke
def test_golang_server_can_emit_contract_metadata_without_user_impl_stubs(tmp_path):
    output_dir = tmp_path / "golang"
    output_dir.mkdir()
    (tmp_path / "go.mod").write_text(
        """
module example.com/generated

go 1.23.8
        """.strip()
        + "\n",
        encoding="utf-8",
    )

    class ListQuery(Model):
        page = String(description="page")

    class ListResponse(Model):
        total = String(description="total")

    bp = Blueprint(root="/api")
    bp.GET("/status").RSP(ListResponse)
    with bp.group("/demo") as views:
        views.GET("/list").ARGS(ListQuery).RSP(ListResponse)
        views.POST("/empty").REQ(ListQuery).RSP()
        views.GET("/download").RSP_FILE(content_type="text/plain", filename="x.txt")

    writer = GolangWriter(
        output_dir,
        enabled_transports=(),
        emit_contract_metadata=True,
        emit_impl_stubs=False,
    )
    writer.register(bp)
    writer.gen()

    provider_contract = (output_dir / "providers" / "gen_contract_types.go").read_text(encoding="utf-8")
    global_contract = (output_dir / "routes" / "gen_contract.go").read_text(encoding="utf-8")
    root_contract = (output_dir / "routes" / "api" / "gen_contract.go").read_text(encoding="utf-8")
    demo_contract = (output_dir / "routes" / "api" / "demo" / "gen_contract.go").read_text(encoding="utf-8")
    generated_impl = (output_dir / "routes" / "api" / "demo" / "gen_impl.go").read_text(encoding="utf-8")

    assert (output_dir / "routes" / "api" / "demo" / "impl.go").exists() is False
    assert not (output_dir / "providers" / "gen_contract.go").exists()
    assert "type ContractRouteInfo struct" in provider_contract
    assert "func ContractRoutes" not in provider_contract
    assert "routes/api/demo" not in provider_contract
    assert "package routes" in global_contract
    assert 'apiRoutes "example.com/generated/golang/routes/api"' in global_contract
    assert "routes = append(routes, apiRoutes.ContractRoutes()...)" in global_contract
    assert "func ContractRoutes() []providers.ContractRouteInfo" in root_contract
    assert 'Path:         "/api/status"' in root_contract
    assert 'Path:         "/api/demo/list"' not in root_contract
    assert "routes = append(routes, demo.ContractRoutes()...)" in root_contract
    assert "func ContractRoutes() []providers.ContractRouteInfo" in demo_contract
    assert 'Path:         "/api/demo/list"' in demo_contract
    assert 'Path:         "/api/status"' not in demo_contract
    assert 'RequestKind:  "query"' in demo_contract
    assert 'ResponseKind: "json"' in demo_contract
    assert 'Envelope:     "CodeMessageDataEnvelope"' in demo_contract
    assert '{Key: "page", Kind: "string", Type: "string", TagSource: "query"}' in demo_contract
    assert "Repeated:  false" not in demo_contract
    assert 'ItemKind:  ""' not in demo_contract
    assert 'Path:         "/api/demo/download"' in demo_contract
    assert "Native:       true" in demo_contract
    assert "type Router struct" in generated_impl
    assert "func NewRouter() *Router" in generated_impl

    result = subprocess.run(
        ["go", "test", "./..."],
        cwd=tmp_path,
        text=True,
        capture_output=True,
        check=False,
    )
    assert result.returncode == 0, result.stdout + result.stderr


def test_golang_server_contract_metadata_is_opt_in(tmp_path):
    output_dir = tmp_path / "golang"
    output_dir.mkdir()
    (tmp_path / "go.mod").write_text("module example.com/generated\n\ngo 1.23.8\n", encoding="utf-8")
    provider_dir = output_dir / "providers"
    routes_dir = output_dir / "routes"
    route_dir = output_dir / "routes" / "api" / "demo"
    root_dir = output_dir / "routes" / "api"
    provider_dir.mkdir(parents=True)
    route_dir.mkdir(parents=True)
    (provider_dir / "gen_contract.go").write_text(
        "// Code generated by api-blueprint (old); DO NOT EDIT.\n\npackage providers\n",
        encoding="utf-8",
    )
    (provider_dir / "gen_contract_types.go").write_text(
        "// Code generated by api-blueprint (old); DO NOT EDIT.\n\npackage providers\n",
        encoding="utf-8",
    )
    (routes_dir / "gen_contract.go").write_text(
        "// Code generated by api-blueprint (old); DO NOT EDIT.\n\npackage routes\n",
        encoding="utf-8",
    )
    (root_dir / "gen_contract.go").write_text(
        "// Code generated by api-blueprint (old); DO NOT EDIT.\n\npackage api\n",
        encoding="utf-8",
    )
    (route_dir / "gen_contract.go").write_text(
        "// Code generated by api-blueprint (old); DO NOT EDIT.\n\npackage demo\n",
        encoding="utf-8",
    )

    bp = Blueprint(root="/api")
    with bp.group("/demo") as views:
        views.GET("/ping").RSP()

    writer = GolangWriter(output_dir)
    writer.register(bp)
    writer.gen()

    assert not (output_dir / "providers" / "gen_contract.go").exists()
    assert not (output_dir / "providers" / "gen_contract_types.go").exists()
    assert not (output_dir / "routes" / "gen_contract.go").exists()
    assert not (output_dir / "routes" / "api" / "gen_contract.go").exists()
    assert not (output_dir / "routes" / "api" / "demo" / "gen_contract.go").exists()
    assert (output_dir / "routes" / "api" / "demo" / "impl.go").exists()


def test_golang_server_preserves_existing_route_impl_go(tmp_path):
    output_dir = tmp_path / "golang"
    route_dir = output_dir / "routes" / "api" / "demo"
    route_dir.mkdir(parents=True)
    (route_dir / "impl.go").write_text(
        "package demo\n\nconst userOwnedImplementation = true\n",
        encoding="utf-8",
    )
    (tmp_path / "go.mod").write_text("module example.com/generated\n\ngo 1.23.8\n", encoding="utf-8")

    bp = Blueprint(root="/api")
    with bp.group("/demo") as views:
        views.GET("/ping").RSP()

    writer = GolangWriter(output_dir, emit_impl_stubs=True)
    writer.register(bp)
    writer.gen()

    assert (route_dir / "impl.go").read_text(encoding="utf-8") == "package demo\n\nconst userOwnedImplementation = true\n"
    assert "func (impl *_GenRouter) Ping" in (route_dir / "gen_impl.go").read_text(encoding="utf-8")


def test_golang_server_wrapper_uses_envelope_wire_field_names(tmp_path):
    output_dir = tmp_path / "golang"
    output_dir.mkdir()
    (tmp_path / "go.mod").write_text("module example.com/generated\n\ngo 1.23.8\n", encoding="utf-8")

    class MsgEnvelope(ResponseEnvelope, Generic[TM]):
        code = Int(description="status")
        msg = String(description="message")
        data: TM = Field(description="payload")

        __envelope_kind__: ClassVar[str] = "code_message_data"
        __error_identity__: ClassVar[str] = "none"
        __success_code__: ClassVar[int] = 200
        __success_message__: ClassVar[str] = ""
        __envelope_fields__: ClassVar[dict[str, str]] = {
            "code": "code",
            "message": "msg",
            "data": "data",
        }

        @classmethod
        def create(cls, data_cls: type[Model]) -> type[ResponseEnvelope]:
            return cls

        @classmethod
        def on_error(cls, err: Error) -> tuple[str, dict[str, object]]:
            return "error", {"code": err.code, "msg": err.message, "data": None}

    class DemoResponse(Model):
        name = String(description="name")

    bp = Blueprint(root="/api", response_envelope=MsgEnvelope)
    with bp.group("/demo") as views:
        views.GET("/item").RSP(DemoResponse)

    writer = GolangWriter(output_dir)
    writer.register(bp)
    writer.gen()

    wrapper_text = (output_dir / "providers" / "gen_wrapper.go").read_text(encoding="utf-8")
    assert "Msg: " in wrapper_text
    assert "Message: " not in wrapper_text
