// Code generated by api-blueprint (Java client); DO NOT EDIT.
package com.example.apiblueprint.alt.runtime;

public record ApiToastSpec(
    String key,
    String level,
    String defaultMessage
) {
}