// Code generated by api-blueprint (Golang HTTP adapter); DO NOT EDIT.

package api

import (
	sharedprovider "demo/views/providers"
	shared "demo/views/routes/api"
	httptransport "demo/views/transports/http"

	"github.com/gin-gonic/gin"
)

func Mount(eng *gin.Engine, impl *shared.Router) *shared.Router {
	if impl == nil {
		impl = shared.NewRouter()
	}

	httptransport.WS(
		"/api/ws",
		sharedprovider.NewRouteExecutor(
			sharedprovider.RouteInfo{
				Root:      "api",
				Group:     "",
				Namespace: "api",
				Service:   "ApiService",
				Operation: "Ws",
				RouteID:   "api.api.ws.ws",
				Path:      "/api/ws",
				Methods:   []string{"WS"},
				Transport: sharedprovider.TransportHTTP,
				Scope:     sharedprovider.ConnectionScope(""),
			},
			"req|auth|ws_handle|rsp=json@GeneralWrapper",
			impl.Ws,
		),
		eng,
	)

	return impl
}

func NewRouter(eng *gin.Engine) *shared.Router {
	return Mount(eng, shared.NewRouter())
}

func NewImpl(eng *gin.Engine) *shared.Router {
	return NewRouter(eng)
}
