[blueprint]
entrypoints = ["blueprints.app:bp"]

[golang]
codegen_output = "golang"
module = "example.com/api-blueprint/wails-hello/golang"

[typescript]
codegen_output = "typescript"

[[transport.targets]]
id = "hello.v3"
kind = "wails"
version = "v3"
overlay_name = "wailsv3"
frontend_mode = "external"
