/* eslint-disable */
// Code generated by api-blueprint (TypeScript); DO NOT EDIT.

import type { ApiErrorCatalogEntry, ApiErrorCode } from "./gen_errors";

export const ErrorCatalogByID = {
} as const satisfies Record<string, ApiErrorCatalogEntry>;

export const ERROR_CATALOG = ErrorCatalogByID;

export function lookupApiErrorByID(id: string): ApiErrorCatalogEntry | undefined {
  return (ErrorCatalogByID as Record<string, ApiErrorCatalogEntry>)[id];
}

export function lookupApiErrorByCode(code: ApiErrorCode): ApiErrorCatalogEntry | undefined {
  return Object.values(ErrorCatalogByID as Record<string, ApiErrorCatalogEntry>).find((entry) => entry.code === code);
}

