// Code generated by api-blueprint (Java client); DO NOT EDIT.
package com.example.apiblueprint.legacy.routes.legacy.account;

import com.example.apiblueprint.legacy.runtime.GenApiChannelBridge;
import com.example.apiblueprint.legacy.runtime.GenApiRequest;
import com.example.apiblueprint.legacy.runtime.GenApiRequestBodySpec;
import com.example.apiblueprint.legacy.runtime.GenApiRequestOptions;
import com.example.apiblueprint.legacy.runtime.GenApiRawResponse;
import com.example.apiblueprint.legacy.runtime.GenApiResponseEnvelope;
import com.example.apiblueprint.legacy.runtime.GenApiResponseSpec;
import com.example.apiblueprint.legacy.runtime.GenApiStreamResponse;
import com.example.apiblueprint.legacy.runtime.GenApiStreamBridge;
import com.example.apiblueprint.legacy.runtime.GenApiTransport;

import com.example.apiblueprint.legacy.runtime.GenApiTypes;

import com.example.apiblueprint.legacy.runtime.binary.GenApiBinaryBody;

public class GenAccountApi {
    protected final GenApiTransport transport;

    public GenAccountApi(GenApiTransport transport) {
        this.transport = transport;
    }

    public GenApiTypes.AccountProfile accountProfile(
    ) throws Exception {
        return accountProfile(
            GenApiRequestOptions.none()
        );
    }

    public GenApiTypes.AccountProfile accountProfile(
        GenApiRequestOptions options
    ) throws Exception {
        GenApiRequestOptions effectiveOptions = options == null ? GenApiRequestOptions.none() : options;
        GenApiRequest<GenApiTypes.AccountProfile> request = new GenApiRequest<>(
            "legacy.account.get.profile",
            "GET",
            "/account/profile",
            null,
            null,
            new GenApiRequestBodySpec(
                null,
                null,
                null,
                null,
                "none"
            ),
            new GenApiResponseSpec<>(
                GenApiResponseEnvelope.of("CodeMessageDataEnvelope", "code_message_data", "nested", 0, "ok", new GenApiResponseEnvelope.Fields("code", "message", "data", "error", "ok")),
                GenApiTypes.AccountProfile.class,
                "application/json",
                "json",
                null
            ),
            effectiveOptions.headers(),
            effectiveOptions.timeout()
        );
        return transport.execute(request);
    }

}
