// Code generated by api-blueprint (Java client); DO NOT EDIT.
package com.example.apiblueprint.legacy.routes.legacy.account;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;

import com.example.apiblueprint.legacy.runtime.GenApiTypes;

import com.example.apiblueprint.legacy.runtime.GenApiFilePart;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;

public final class GenAccountTypes {
    private GenAccountTypes() {
    }

}
