// Code generated by api-blueprint (Java server); DO NOT EDIT.
package com.example.apiblueprint.api.routes.api.media;

import com.example.apiblueprint.api.runtime.GenApiTypes;

import com.example.apiblueprint.api.runtime.GenApiRawResponse;
import com.example.apiblueprint.api.runtime.GenApiServerChannel;
import com.example.apiblueprint.api.runtime.GenApiServerStream;
import com.example.apiblueprint.api.runtime.GenApiStreamResponse;
import com.example.apiblueprint.api.runtime.binary.GenApiBinaryBody;

public interface GenMediaService {

    GenApiRawResponse mediaPreview(
        GenApiTypes.MediaPreviewRequest multipart
    ) throws Exception;

    GenApiRawResponse mediaFrame(
    ) throws Exception;

    GenApiRawResponse mediaDownload(
    ) throws Exception;

    GenApiRawResponse mediaDownloadDynamic(
    ) throws Exception;

    GenApiRawResponse mediaDownloadFilenameEdge(
    ) throws Exception;

    GenApiRawResponse mediaErrorFrame(
        GenMediaTypes.MediaErrorFrameQuery query
    ) throws Exception;

    GenApiStreamResponse mediaMjpeg(
    ) throws Exception;

}
