// Code generated by api-blueprint (Java server); DO NOT EDIT.
package com.example.apiblueprint.api.routes.api.media;

import com.example.apiblueprint.api.runtime.ApiTypes;

import com.example.apiblueprint.api.runtime.ApiRawResponse;
import com.example.apiblueprint.api.runtime.ApiServerChannel;
import com.example.apiblueprint.api.runtime.ApiServerStream;
import com.example.apiblueprint.api.runtime.ApiStreamResponse;
import com.example.apiblueprint.api.runtime.binary.ApiBinaryBody;

public class MediaServiceStub implements MediaService {

    @Override
    public ApiRawResponse mediaPreview(
        ApiTypes.MediaPreviewRequest multipart
    ) throws Exception {
        throw new UnsupportedOperationException("mediaPreview");
    }

    @Override
    public ApiRawResponse mediaFrame(
    ) throws Exception {
        throw new UnsupportedOperationException("mediaFrame");
    }

    @Override
    public ApiRawResponse mediaDownload(
    ) throws Exception {
        throw new UnsupportedOperationException("mediaDownload");
    }

    @Override
    public ApiRawResponse mediaDownloadDynamic(
    ) throws Exception {
        throw new UnsupportedOperationException("mediaDownloadDynamic");
    }

    @Override
    public ApiStreamResponse mediaMjpeg(
    ) throws Exception {
        throw new UnsupportedOperationException("mediaMjpeg");
    }

}
