// Code generated by api-blueprint; DO NOT EDIT.
package com.example.apiblueprint.api.runtime

import com.example.apiblueprint.api.routes.api.demo.DemoApi
import com.example.apiblueprint.api.routes.api.hello.HelloApi


public open class GenApiClient(
    private val transport: ApiTransport,
) {
    public val demo: DemoApi = DemoApi(transport)
    public val hello: HelloApi = HelloApi(transport)
}
