// Code generated by api-blueprint (Flutter client); DO NOT EDIT.
import 'gen_api_errors.dart';

class ApiErrorCode {
  const ApiErrorCode._();

  static const commonErrUnknown = -1;

  static const tokenExpire = 55555;

  static const demoErrUnknown = 70002;

  static const rateLimited = 42901;
}

final apiErrorsById = <String, ApiErrorPayload>{
  "CommonErr.UNKNOWN": ApiErrorPayload(
    id: "CommonErr.UNKNOWN",
    group: "CommonErr",
    key: "UNKNOWN",
    code: -1,
    message: "\u672a\u77e5\u9519\u8bef",
    toast: ApiToastPayload(
      key: "CommonErr.UNKNOWN",
      level: "error",
      defaultMessage: "\u672a\u77e5\u9519\u8bef",
    ),
  ),
  "CommonErr.TOKEN_EXPIRE": ApiErrorPayload(
    id: "CommonErr.TOKEN_EXPIRE",
    group: "CommonErr",
    key: "TOKEN_EXPIRE",
    code: 55555,
    message: "token\u767b\u5f55\u6001\u5931\u6548",
    toast: ApiToastPayload(
      key: "auth.token_expire",
      level: "warning",
      defaultMessage: "\u767b\u5f55\u72b6\u6001\u5df2\u5931\u6548\uff0c\u8bf7\u91cd\u65b0\u767b\u5f55",
    ),
  ),
  "DemoErr.UNKNOWN": ApiErrorPayload(
    id: "DemoErr.UNKNOWN",
    group: "DemoErr",
    key: "UNKNOWN",
    code: 70002,
    message: "demo unknown error",
    toast: ApiToastPayload(
      key: "DemoErr.UNKNOWN",
      level: "error",
      defaultMessage: "demo unknown error",
    ),
  ),
  "DemoErr.RATE_LIMITED": ApiErrorPayload(
    id: "DemoErr.RATE_LIMITED",
    group: "DemoErr",
    key: "RATE_LIMITED",
    code: 42901,
    message: "\u8bf7\u6c42\u8fc7\u4e8e\u9891\u7e41",
    toast: ApiToastPayload(
      key: "demo.rate_limited",
      level: "warning",
      defaultMessage: "\u8bf7\u6c42\u8fc7\u4e8e\u9891\u7e41\uff0c\u8bf7\u7a0d\u540e\u518d\u8bd5",
    ),
  ),
};

final routeApiErrorsByCode = <String, Map<int, ApiErrorPayload>>{
  "legacy.account.get.profile": {
  },
  "legacy.room.get.list": {
  },
  "legacy.legacy_json.get.compat": {
  },
};

final apiErrorsByCode = <int, ApiErrorPayload>{
  -1: apiErrorsById["CommonErr.UNKNOWN"]!,
  55555: apiErrorsById["CommonErr.TOKEN_EXPIRE"]!,
  70002: apiErrorsById["DemoErr.UNKNOWN"]!,
  42901: apiErrorsById["DemoErr.RATE_LIMITED"]!,
};

ApiErrorPayload lookupApiError(ApiErrorPayload payload) {
  if (payload.id.isNotEmpty && apiErrorsById.containsKey(payload.id)) {
    return mergeApiErrorPayload(apiErrorsById[payload.id]!, payload);
  }
  final routeMatch = routeApiErrorsByCode[payload.routeId]?[payload.code];
  if (routeMatch != null) {
    return mergeApiErrorPayload(routeMatch, payload);
  }
  final codeMatch = apiErrorsByCode[payload.code];
  if (codeMatch != null) {
    return mergeApiErrorPayload(codeMatch, payload);
  }
  return payload;
}

ApiErrorPayload mergeApiErrorPayload(ApiErrorPayload known, ApiErrorPayload payload) {
  return ApiErrorPayload(
    id: payload.id.isNotEmpty ? payload.id : known.id,
    group: payload.group.isNotEmpty ? payload.group : known.group,
    key: payload.key.isNotEmpty ? payload.key : known.key,
    code: payload.code != 0 ? payload.code : known.code,
    message: payload.message.isNotEmpty ? payload.message : known.message,
    toast: ApiToastPayload(
      key: payload.toast.key.isNotEmpty ? payload.toast.key : known.toast.key,
      level: payload.toast.level.isNotEmpty ? payload.toast.level : known.toast.level,
      defaultMessage: payload.toast.defaultMessage.isNotEmpty
          ? payload.toast.defaultMessage
          : known.toast.defaultMessage,
      text: payload.toast.text.isNotEmpty ? payload.toast.text : known.toast.text,
    ),
    routeId: payload.routeId,
  );
}
